# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class mdpConsumedServiceDef(ManagedObject):
    """ACI Managed Object: ``mdpConsumedServiceDef`` — Consumer of MDP Service (resolved).

    RN format: ``consumedsrvdef-[{mdp_consumed_service_def_dn}]``
    """

    _aci_class: ClassVar[str] = "mdpConsumedServiceDef"
    _rn_format: ClassVar[str] = "consumedsrvdef-[{mdp_consumed_service_def_dn}]"
    _naming_props: ClassVar[list[str]] = ["mdp_consumed_service_def_dn"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "mdpConsumerEPgInfoRef",
            "mdpConsumerVnInfoRef",
            "mdpRsToMdpServiceDef",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-ext-connectivity"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    mdp_consumed_service_def_dn: Annotated[
        str, Field(validation_alias="mdpServiceDefDn", serialization_alias="mdpServiceDefDn")
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
