# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class pkiWebTokenData(ManagedObject):
    """ACI Managed Object: ``pkiWebTokenData`` — Web Token Data.

    RN format: ``webtokendata``
    """

    _aci_class: ClassVar[str] = "pkiWebTokenData"
    _rn_format: ClassVar[str] = "webtokendata"
    _naming_props: ClassVar[list[str]] = []
    _secure_props: ClassVar[frozenset[str]] = frozenset(["jwt_private_key"])
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["aaa", "admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Create-only (ignored by APIC on modification) ─────────────────────────
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    jwt_api_key: Annotated[str, Field(max_length=512, alias="jwtApiKey")] = ""
    jwt_private_key: Annotated[str, Field(alias="jwtPrivateKey", repr=False)] = ""
    jwt_public_key: str = Field(default="", alias="jwtPublicKey")
    maximum_validity_period_in_hours: str = Field(default="", alias="maximumValidityPeriod")
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="ownerKey"
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(max_length=64, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="ownerTag"),
    ] = ""
    session_recording_options: str = Field(default="", alias="sessionRecordFlags")
    gui_idle_timeout_in_seconds: str = Field(default="", alias="uiIdleTimeoutSeconds")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    timeout_in_seconds: str = Field(default="", alias="webtokenTimeoutSeconds")
