# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import BeforeValidator, Field

from niwaki.models._wire import Flags, parse_flags
from niwaki.models._generated.enums.PkiSessionRecordFlags import PkiSessionRecordFlags

from niwaki.models.base import ManagedObject


class pkiWebTokenData(ManagedObject):
    """ACI Managed Object: ``pkiWebTokenData`` — Web Token Data.

    The cryptographic data used for generating and verifying web tokens.

    RN format: ``webtokendata``
    """

    _aci_class: ClassVar[str] = "pkiWebTokenData"
    _rn_format: ClassVar[str] = "webtokendata"
    _naming_props: ClassVar[list[str]] = []
    _secure_props: ClassVar[frozenset[str]] = frozenset(["jwt_private_key"])
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["aaa", "admin"])
    _is_creatable: ClassVar[bool] = False
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Create-only (ignored by APIC on modification) ─────────────────────────
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    jwt_api_key: Annotated[
        str, Field(max_length=512, validation_alias="jwtApiKey", serialization_alias="jwtApiKey")
    ] = ""
    jwt_private_key: Annotated[
        str,
        Field(validation_alias="jwtPrivateKey", serialization_alias="jwtPrivateKey", repr=False),
    ] = ""
    jwt_public_key: str = Field(
        default="", validation_alias="jwtPublicKey", serialization_alias="jwtPublicKey"
    )
    maximum_validity_period_in_hours: Annotated[
        int,
        Field(
            ge=4,
            le=24,
            validation_alias="maximumValidityPeriod",
            serialization_alias="maximumValidityPeriod",
            description="The maximum validity period for a webt oken.",
        ),
    ] = 24
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerKey",
            serialization_alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerTag",
            serialization_alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    session_recording_options: Annotated[
        Flags[PkiSessionRecordFlags], BeforeValidator(parse_flags)
    ] = Field(
        default_factory=lambda: frozenset(),
        validation_alias="sessionRecordFlags",
        serialization_alias="sessionRecordFlags",
        description="Enables or disables a refresh in the session records.",
    )
    gui_idle_timeout_in_seconds: Annotated[
        int,
        Field(
            ge=60,
            le=65525,
            validation_alias="uiIdleTimeoutSeconds",
            serialization_alias="uiIdleTimeoutSeconds",
            description="The maximum interval time the GUI remains idle before login needs to be refreshed.",
        ),
    ] = 1200
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    timeout_in_seconds: Annotated[
        int,
        Field(
            ge=300,
            le=9600,
            validation_alias="webtokenTimeoutSeconds",
            serialization_alias="webtokenTimeoutSeconds",
            description="The web token timeout interval.",
        ),
    ] = 600
