# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.SnmpNotificationType import SnmpNotificationType
from niwaki.models._generated.enums.SnmpV3SecLvl import SnmpV3SecLvl
from niwaki.models._generated.enums.SnmpVersion import SnmpVersion

from niwaki.models.base import ManagedObject


class snmpTrapDest(ManagedObject):
    """ACI Managed Object: ``snmpTrapDest`` — SNMP Trap Destination.

    A destination to which traps and informs are sent.

    RN format: ``trapdest-{host}-port-{port}``
    """

    _aci_class: ClassVar[str] = "snmpTrapDest"
    _rn_format: ClassVar[str] = "trapdest-{host}-port-{port}"
    _naming_props: ClassVar[list[str]] = ["host", "port"]
    _fault_codes: ClassVar[dict[str, str]] = {
        "F1449": "fltSnmpTrapDestSnmpTrapDestVrfName",
        "F1450": "fltSnmpTrapDestSnmpTrapDestEpgDn",
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "fileRsARemoteHostToEpg",
            "fileRsARemoteHostToEpp",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    host: Annotated[
        str,
        Field(
            description="The host for the SNMP trap destination. SNMP traps enable an agent to notify the management station of significant events by way of an unsolicited SNMP message."
        ),
    ]
    port: Annotated[
        int,
        Field(
            ge=1,
            le=65535,
            description="The service port of the SNMP trap destination. SNMP traps enable an agent to notify the management station of significant events by way of an unsolicited SNMP message.",
        ),
    ] = 162

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    notif_t: SnmpNotificationType = Field(
        default=SnmpNotificationType.TRAPS, validation_alias="notifT", serialization_alias="notifT"
    )
    security_name: str = Field(
        default="",
        validation_alias="secName",
        serialization_alias="secName",
        description="The SNMP destination security name.",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    v3_security_level: SnmpV3SecLvl = Field(
        default=SnmpV3SecLvl.NOAUTH,
        validation_alias="v3SecLvl",
        serialization_alias="v3SecLvl",
        description="The SNMP V3 security level for the destination path.",
    )
    version: SnmpVersion = Field(
        default=SnmpVersion.V2C,
        validation_alias="ver",
        serialization_alias="ver",
        description="The CDP version supported by the device.",
    )
