# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import BeforeValidator, Field

from niwaki.models._wire import Flags, parse_flags
from niwaki.models._generated.enums.ConditionSeverity import ConditionSeverity
from niwaki.models._generated.enums.MonInclAction import MonInclAction

from niwaki.models.base import ManagedObject


class snmpSrc(ManagedObject):
    """ACI Managed Object: ``snmpSrc`` — SNMP Source.

    The SNMP source profile determines the fault information, severity level, and destination for sending messages to the SNMP destination. SNMP is an application-layer protocol that provides a message format for communication between SNMP managers and agents.

    RN format: ``snmpsrc-{name}``
    """

    _aci_class: ClassVar[str] = "snmpSrc"
    _rn_format: ClassVar[str] = "snmpsrc-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "monMonObjDn",
            "snmpRsDestGroup",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The name for the SNMP source. This name can be between 1 and 64 alphanumeric characters.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    include_action: Annotated[Flags[MonInclAction], BeforeValidator(parse_flags)] = Field(
        default_factory=lambda: frozenset({MonInclAction.ALL}),
        validation_alias="incl",
        serialization_alias="incl",
        description="The options to include for the SNMP source.",
    )
    min_severity: ConditionSeverity = Field(
        default=ConditionSeverity.INFO,
        validation_alias="minSev",
        serialization_alias="minSev",
        description="The minimum severity level of SNMP traps. SNMP traps enable an agent to notify the management station of significant events by way of an unsolicited SNMP message.",
    )
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
