# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.HsrpGroupAf import HsrpGroupAf
from niwaki.models._generated.enums.HsrpGrpIpObtainMode import HsrpGrpIpObtainMode

from niwaki.models.base import ManagedObject


class hsrpGroupP(ManagedObject):
    """ACI Managed Object: ``hsrpGroupP`` — HSRP Group Profile.

    Hsrp Group Profile

    RN format: ``hsrpGroupP-{name}``

    The APIC can flag these accepted-but-inconsistent states on this class
    (read-only ``configIssues``):

    - ``GroupMac-Conflicts-Other-Group`` — GroupMac Conflicts Other Group
    - ``GroupName-Conflicts-Other-Group`` — GroupName Conflicts Other Group
    - ``GroupVIP-Conflicts-Other-Group`` — GroupVIP Conflicts Other Group
    - ``Multiple-Version-On-Interface`` — Multiple hsrp version configured on Interface
    - ``Secondary-vip-conflicts-if-ip`` — SecVip Conflicts Interface Ip
    - ``Secondary-vip-subnet-mismatch`` — SecVip RsPathL3OutAtt Subnet Misconfiguration
    - ``group-vip-conflicts-if-ip`` — hsrpGroupP Ip Conflict
    - ``group-vip-subnet-mismatch`` — hsrpGroupP RsPathL3OutAtt Subnet Misconfiguration
    """

    _aci_class: ClassVar[str] = "hsrpGroupP"
    _rn_format: ClassVar[str] = "hsrpGroupP-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _config_issues: ClassVar[dict[str, str]] = {
        "group-vip-conflicts-if-ip": "hsrpGroupP Ip Conflict",
        "group-vip-subnet-mismatch": "hsrpGroupP RsPathL3OutAtt Subnet Misconfiguration",
        "GroupMac-Conflicts-Other-Group": "GroupMac Conflicts Other Group",
        "GroupName-Conflicts-Other-Group": "GroupName Conflicts Other Group",
        "GroupVIP-Conflicts-Other-Group": "GroupVIP Conflicts Other Group",
        "Multiple-Version-On-Interface": "Multiple hsrp version configured on Interface",
        "none": "",
        "Secondary-vip-conflicts-if-ip": "SecVip Conflicts Interface Ip",
        "Secondary-vip-subnet-mismatch": "SecVip RsPathL3OutAtt Subnet Misconfiguration",
    }
    _fault_codes: ClassVar[dict[str, str]] = {
        "F2451": "fltHsrpGroupPGroupVipSubnetMismatch",
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "hsrpRsGroupPol",
            "hsrpSecVip",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "tenant-ext-connectivity", "tenant-ext-protocol"]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The name of the object.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    group_vip_misconfiguration: str = Field(
        default="",
        alias="configIssues",
        description="Bitmask representation of the configuration issues found during the endpoint group deployment.",
    )
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    group_af: HsrpGroupAf = Field(
        default=HsrpGroupAf.IPV4, alias="groupAf", description="HSRP Group Type"
    )
    group_id: str = Field(default="", alias="groupId", description="HSRP Group ID")
    group_name: Annotated[
        str, Field(max_length=512, alias="groupName", description="Redundancy name string")
    ] = ""
    primary_ip_address: Annotated[
        str,
        Field(
            pattern="^[0-9a-fA-F.:/ ]+$",
            alias="ip",
            description="HSRP primary Virtual IP address (VIP)",
        ),
    ] = ""
    vip_obtain_mode: HsrpGrpIpObtainMode = Field(
        default=HsrpGrpIpObtainMode.ADMIN,
        alias="ipObtainMode",
        description="HSRP primary Virtual IP Obtain Mode",
    )
    configured_mac_address_for_the_group: Annotated[
        str,
        Field(
            pattern="^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$",
            alias="mac",
            description="HSRP VMAC for the group",
        ),
    ] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
