"""Generate docs/reference/vocabulary/ — the curated vocabulary book.

Usage (from repo root):
    uv run python -m niwaki._codegen.generate_docs

Inputs:
    src/niwaki/domain/vocabulary.yaml      (curated vocabulary)
    domain/_child_map.py                   (REFERENCE_MAP / TARGET_SUBCLASSES)
    the generated Pydantic models          (introspected: RN formats, naming)

Output:
    docs/reference/vocabulary/index.md + one page per design domain
    (tenant.md, infra.md, fabric.md, controller.md)

This is the documentation no generic tool can produce: for every curated
position — "I'm on an AAEP, what can I write?" — the maker signature, the
``bind()`` aliases with their flavor (name vs DN) and relation class, the
contract verbs, the sugar parameters, and the atomicity notes, all derived
from the same tables the runtime uses, so the book cannot drift from the
code.  ``tests/design/test_docs_generator.py`` guards the committed pages
against stale regeneration.
"""

from __future__ import annotations

from pathlib import Path

from niwaki._codegen._field_docs import (
    FieldDoc,
    class_definition,
    enum_anchor,
    enum_members,
    field_docs,
    position_anchor,
    position_slug,
)
from niwaki._codegen.generate_design import _cursor_names, _Position, _positions
from niwaki.design._cursor import _load_class, _tables

_REPO_ROOT = Path(__file__).parent.parent.parent.parent
OUTPUT_DIR = _REPO_ROOT / "docs" / "reference" / "vocabulary"

_HEADER = """<!--
Generated by niwaki generate_docs — do not edit manually.
Re-generate: uv run python -m niwaki._codegen.generate_docs
-->
"""

# Domain roots, in walkthrough order: (position key, page title, blurb).
_DOMAINS = [
    (
        "fabric",
        "fabric — fabric policies",
        "NTP, DNS, syslog, BGP route reflectors, vPC protection — everything "
        "under `uni/fabric`.  Root factory: `fabric()`.",
    ),
    (
        "infra",
        "infra — access policies",
        "Interface policies, VLAN pools, AAEPs, policy groups, interface and "
        "switch profiles — everything under `uni/infra`.  Root factory: "
        "`infra()`.",
    ),
    (
        "tenant",
        "tenant — logical networking",
        "VRFs, bridge domains, application profiles, EPGs, contracts and "
        "filters — one `uni/tn-*` subtree per tenant.  Root factory: "
        "`tenant(name)`.",
    ),
    (
        "controller",
        "controller — controller policies",
        "Fabric membership (node registration) under `uni/controller`.  "
        "Root factory: `controller()`.",
    ),
    (
        "vmm_provider",
        "vmm_provider — VMM domains",
        "Virtual Machine Manager domains under `uni/vmmp-<vendor>`: the domain, "
        "its vCenter/SCVMM controller, credentials and vSwitch policies.  Reached "
        "as `design().vmm_provider(vendor)`.  Pushing lands the APIC-side config; "
        "a reachable controller is required before inventory actually syncs.",
    ),
]


_DOMAIN_ROOTS = tuple(root for root, _, _ in _DOMAINS)


def _uni_keys() -> tuple[str, ...]:
    """The ``uni``-level domains: every polUni maker that is not a design root.

    Derived, not enumerated — curating a new domain under ``polUni``
    (``l2_dom`` after ``phys_dom`` and ``l3_dom``) gives it a page without
    touching the generator.
    """
    from niwaki.design._cursor import _tables

    return tuple(
        label for label in _tables().makers.get("polUni", {}) if label not in _DOMAIN_ROOTS
    )


def _resolve_edge(owner_aci: str, target_aci: str) -> tuple[str, str, str] | None:
    """Resolve a curated bind edge to ``(rs_class, flavor, direction)``.

    Mirrors the runtime resolver: direct entries first (Rs under the owner),
    inverse otherwise (Rs under the target); abstract targets span their
    concrete subclasses.
    """
    from niwaki.domain._child_map import REFERENCE_MAP, TARGET_SUBCLASSES

    candidates = [target_aci, *TARGET_SUBCLASSES.get(target_aci, ())]
    direct = {
        entry for c in candidates if (entry := REFERENCE_MAP.get(owner_aci, {}).get(c)) is not None
    }
    if len(direct) == 1:
        rs, flavor = next(iter(direct))
        return rs, flavor, "direct"
    inverse = {
        entry for c in candidates if (entry := REFERENCE_MAP.get(c, {}).get(owner_aci)) is not None
    }
    if len(inverse) == 1:
        rs, flavor = next(iter(inverse))
        return rs, flavor, "inverse"
    return None


def _maker_signature(label: str, child_aci: str) -> str:
    """Abbreviated maker signature: naming positionally, attributes summarised."""
    cls = _load_class(child_aci)
    naming = list(cls._naming_props)  # pyright: ignore[reportPrivateUsage]
    sugar = list(_tables().sugar.get(child_aci, {}))
    parts = [*naming, *sugar, "**attrs"]
    return f"{label}({', '.join(parts)})"


def _subtree(root_key: str, positions: dict[str, _Position]) -> list[_Position]:
    """Positions of one domain, depth-first in maker-declaration order."""
    makers = _tables().makers

    def _walk(key: str) -> list[_Position]:
        pos = positions[key]
        out = [pos]
        for label in makers.get(pos.aci_class, {}):
            child_key = f"{key}.{label}"
            if child_key in positions:
                out.extend(_walk(child_key))
        return out

    return _walk(root_key)


def _attribute_table(docs: list[FieldDoc], used_enums: set[str]) -> list[str]:
    """Render the attribute table of a position (and collect the enums used)."""
    lines = [
        "| parameter | wire | type | values | default | description |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for doc in docs:
        name = f"`{doc.name}`" + (" *(positional)*" if doc.kind == "naming" else "")
        if doc.enum:
            used_enums.add(doc.enum)
            type_txt = f"{{ref}}`{doc.enum} <{enum_anchor(doc.enum)}>`"
            values = ", ".join(f"`{v}`" for v in doc.values)
        else:
            type_txt = f"`{doc.type_str}`"
            values = "—"
        wire = f"`{doc.wire}`" if doc.wire != "—" else "—"
        default = f"`{doc.default}`" if doc.default else "—"
        description = doc.description.replace("|", "\\|") or "—"
        lines.append(f"| {name} | {wire} | {type_txt} | {values} | {default} | {description} |")
    lines.append("")
    return lines


def _render_position_page(
    pos: _Position,
    positions: dict[str, _Position],
    names: dict[str, str],
    used_enums: set[str],
) -> str:
    """Render the full reference page of one curated position."""
    tables = _tables()
    cls = _load_class(pos.aci_class)
    rn_format = cls._rn_format  # pyright: ignore[reportPrivateUsage]
    label = pos.key.rsplit(".", 1)[-1]

    lines = [
        _HEADER,
        f"({position_anchor(pos.key)})=",
        "",
        f"# `{pos.key}`",
        "",
    ]

    if blurb := class_definition(cls):
        lines += [blurb, ""]

    atomic_txt = "yes — the subtree ships in one request" if pos.aci_class in tables.atomic else "—"
    parent_txt = "—"
    if pos.parent_key is not None:
        parent = positions[pos.parent_key]
        parent_txt = (
            f"{{ref}}`{parent.key} <{position_anchor(parent.key)}>`"
            if parent.key
            else "`design()` root"
        )
    lines += [
        "| | |",
        "| --- | --- |",
        f"| ACI class | `{pos.aci_class}` |",
        f"| RN | `{rn_format}` |",
        f"| Cursor | `{names[pos.key]}` |",
        f"| Parent | {parent_txt} |",
        f"| Atomic | {atomic_txt} |",
        "",
    ]

    docs = field_docs(cls, tables.sugar.get(pos.aci_class, {}))
    naming = [d.name for d in docs if d.kind == "naming"]
    call = f".{label}({', '.join(naming)})" if pos.parent_key is not None else f"{label}()"

    lines += [
        "## Attributes",
        "",
        f"Accepted as keyword arguments of `{call}` and of `.set(**attrs)` on this "
        "cursor.  Enum parameters also accept the plain string.",
        "",
    ]
    lines += _attribute_table(docs, used_enums)

    if makers := tables.makers.get(pos.aci_class, {}):
        lines += [
            "## Children",
            "",
            "| maker | creates | position |",
            "| --- | --- | --- |",
        ]
        for maker_label, child in makers.items():
            child_key = f"{pos.key}.{maker_label}" if pos.key else maker_label
            ref = f"{{ref}}`{child_key} <{position_anchor(child_key)}>`"
            lines.append(f"| `.{_maker_signature(maker_label, child)}` | `{child}` | {ref} |")
        lines.append("")

    if binds := tables.binds.get(pos.aci_class, {}):
        lines += [
            "## Bind aliases",
            "",
            "Lazy references, resolved closed-world at push time.",
            "",
            "| alias | target | flavor | relation |",
            "| --- | --- | --- | --- |",
        ]
        for alias, target in binds.items():
            edge = _resolve_edge(pos.aci_class, target)
            if edge is None:  # pragma: no cover — the curation test forbids this
                continue
            rs, flavor, direction = edge
            from niwaki.domain._child_map import TARGET_SUBCLASSES

            target_txt = f"`{target}`"
            if subs := TARGET_SUBCLASSES.get(target):
                target_txt += f" *(abstract: {', '.join(f'`{s}`' for s in subs[:4])}…)*"
            note = " (on the target side)" if direction == "inverse" else ""
            flavor_txt = "name" if flavor == "name" else "DN — `bind_dn()` allowed"
            lines.append(f"| `{alias}=` | {target_txt} | {flavor_txt} | `{rs}`{note} |")
        lines.append("")

    if verbs := tables.verbs.get(pos.aci_class, {}):
        lines += ["## Verbs", ""]
        for verb, spec in verbs.items():
            lines.append(f"- `.{verb}(name)` → `{spec['rs']}` targeting `{spec['target']}`")
        lines.append("")

    issues = cls._config_issues  # pyright: ignore[reportPrivateUsage]
    faults = cls._fault_codes  # pyright: ignore[reportPrivateUsage]
    healthy = {"ok", "none", "N/A", "not-applicable"}
    issue_rows = [(c, d) for c, d in sorted(issues.items()) if c not in healthy]
    if issue_rows or faults:
        lines += [
            "## APIC diagnostics",
            "",
            "States the APIC can flag on this class — it accepts the configuration "
            "and reports the inconsistency afterwards.",
            "",
        ]
        if issue_rows:
            lines += ["**Config issues**", "", "| code | meaning |", "| --- | --- |"]
            lines += [f"| `{code}` | {desc or '—'} |" for code, desc in issue_rows]
            lines.append("")
        if faults:
            lines += ["**Faults**", "", "| code | condition |", "| --- | --- |"]
            lines += [f"| `{code}` | `{name}` |" for code, name in sorted(faults.items())]
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_domain(root_key: str, title: str, blurb: str) -> str:
    """Render a domain index: the position tree plus a toctree of its pages."""
    positions = _positions()
    subtree = _subtree(root_key, positions)
    lines = [_HEADER, f"# {title}", "", blurb, "", "## Positions", ""]

    for pos in subtree:
        depth = pos.key.count(".") - root_key.count(".")
        indent = "  " * depth
        cls = _load_class(pos.aci_class)
        n_fields = len(field_docs(cls, _tables().sugar.get(pos.aci_class, {})))
        lines.append(
            f"{indent}- {{ref}}`{pos.key} <{position_anchor(pos.key)}>` "
            f"— `{pos.aci_class}`, {n_fields} attributes"
        )
    lines += [
        "",
        "```{toctree}",
        ":maxdepth: 1",
        ":hidden:",
        "",
        *(f"{root_key}/{position_slug(pos.key)}" for pos in subtree),
        "```",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _render_enums(used_enums: set[str]) -> str:
    """Render the enums reachable from the curated vocabulary."""
    from niwaki.models._generated.enums import _all as enums_module

    positions = _positions()
    by_enum: dict[str, list[str]] = {}
    for pos in positions.values():
        if not pos.key:
            continue
        cls = _load_class(pos.aci_class)
        for doc in field_docs(cls, _tables().sugar.get(pos.aci_class, {})):
            if doc.enum:
                by_enum.setdefault(doc.enum, []).append(pos.key)

    lines = [
        _HEADER,
        "# Enums",
        "",
        f"The {len(by_enum)} enum types reachable from the curated vocabulary — "
        "every constrained parameter of every maker.  A parameter typed as an "
        "enum also accepts the plain string; the value is validated at the call "
        "site either way.",
        "",
        "The remaining generated enums back the non-curated classes and live in "
        "`niwaki.models._generated.enums`.",
        "",
    ]
    for enum_name in sorted(by_enum):
        enum_cls = getattr(enums_module, enum_name)
        lines += [
            f"({enum_anchor(enum_name)})=",
            "",
            f"## `{enum_name}`",
            "",
            "| value | meaning |",
            "| --- | --- |",
        ]
        for value, meaning in enum_members(enum_cls):
            lines.append(f"| `{value}` | {meaning or '—'} |")
        used_by = sorted(set(by_enum[enum_name]))
        shown = ", ".join(f"{{ref}}`{key} <{position_anchor(key)}>`" for key in used_by[:8])
        more = f" *(+{len(used_by) - 8} more)*" if len(used_by) > 8 else ""
        lines += ["", f"Used by: {shown}{more}", ""]
    return "\n".join(lines).rstrip() + "\n"


def _render_navigation() -> str:
    """Render the read-side vocabulary: which name descends into which class."""
    from niwaki.domain._child_map import CHILD_MAP

    positions = _positions()
    lines = [
        _HEADER,
        "# Navigation vocabulary",
        "",
        "The facade resolves operator names into typed child handles — "
        '`aci.tenant("prod").bd("web")` walks the APIC containment model, one '
        "name at a time.  The table below lists the navigation names of every "
        "curated position (the read side accepts far more: any child name in the "
        "APIC model resolves, curated or not).",
        "",
        "| from | name | descends into |",
        "| --- | --- | --- |",
    ]
    for key in sorted(positions):
        pos = positions[key]
        parent_class = "_root" if not key else pos.aci_class
        children = CHILD_MAP.get(parent_class, {})
        if not key:
            continue
        for name, child in sorted(children.items()):
            child_positions = [p.key for p in positions.values() if p.aci_class == child and p.key]
            if not child_positions:
                continue
            ref = f"{{ref}}`{child_positions[0]} <{position_anchor(child_positions[0])}>`"
            lines.append(f"| `{pos.key}` | `.{name}(…)` | `{child}` — {ref} |")
    return "\n".join(lines).rstrip() + "\n"


def _render_index() -> str:
    tables = _tables()
    positions = _positions()
    lines = [
        _HEADER,
        "# Vocabulary book",
        "",
        "The curated design surface, generated from `domain/vocabulary.yaml` "
        "and the schema-derived reference map — the same tables the runtime "
        "uses, so this book cannot drift from the code.",
        "",
        "Every design is rooted at `polUni` (`design()`); the pages below "
        "cover one domain each.  Anything outside this vocabulary stays "
        "reachable through `.mo(Class, ...)` and `bind_dn(alias=dn)`.",
        "",
        "**Root makers** (available on `design()` and, via implicit pop, from any cursor):",
        "",
    ]
    for label, child in tables.makers.get("polUni", {}).items():
        sig = _maker_signature(label, child)
        lines.append(f"- `.{sig}` → `{child}`")

    # Standalone uni-level domains (physical/routed domains) with their binds.
    lines += ["", "**Domains under `uni`**", ""]
    for key in _uni_keys():
        pos = positions[key]
        for alias, target in tables.binds.get(pos.aci_class, {}).items():
            edge = _resolve_edge(pos.aci_class, target)
            if edge:
                rs, flavor, _ = edge
                lines.append(
                    f"- `{key}(name).bind({alias}=...)` → `{rs}` "
                    f"({'name' if flavor == 'name' else 'DN'} flavor, target `{target}`)"
                )

    lines += [
        "",
        "```{toctree}",
        ":maxdepth: 2",
        "",
        *(root_key for root_key, _, _ in _DOMAINS),
        "uni",
        "enums",
        "navigation",
        "coverage",
        "```",
    ]
    return "\n".join(lines).rstrip() + "\n"


# Frequently requested areas that are not curated yet — shown on the coverage
# page next to the escape hatches, so the boundary is explicit.  Each entry
# names representative ACI classes; the docs-generator test asserts none of them
# is a curated position, so this list can never claim as "raw ACI" something the
# vocabulary has since grown a maker for (ESGs and L3Out internals did exactly
# that, and the list lied about them until this guard existed).
_NOT_CURATED = [
    (
        "Simplified interface configuration",
        "the post-5.2 per-port `infraPortConfig` model (parallel to profiles/selectors)",
        ("infraPortConfig", "infraNodeConfig"),
    ),
    (
        "Service graphs",
        "`vnsAbsGraph`, `vnsLDevVip` and the L4-L7 device chain",
        ("vnsAbsGraph", "vnsLDevVip"),
    ),
]


def _coverage_row(pos: _Position) -> str:
    """One coverage-matrix row for a curated position."""
    tables = _tables()
    makers = tables.makers.get(pos.aci_class, {})
    binds = tables.binds.get(pos.aci_class, {})
    verbs = tables.verbs.get(pos.aci_class, {})
    sugar = tables.sugar.get(pos.aci_class, {})
    ref = f"{{ref}}`{pos.key} <{position_anchor(pos.key)}>`"
    return (
        f"| {ref} | `{pos.aci_class}` | {len(makers) or '—'} "
        f"| {', '.join(f'`{a}=`' for a in binds) or '—'} "
        f"| {', '.join(f'`.{v}()`' for v in verbs) or '—'} "
        f"| {', '.join(f'`{s}=`' for s in sugar) or '—'} "
        f"| {'✓' if pos.aci_class in tables.atomic else '—'} |"
    )


def curated_position_count() -> int:
    """Total number of curated positions (the coverage-matrix figure).

    The single source of truth for every "N curated positions" number: the
    coverage matrix uses it, and ``docs/conf.py`` injects it as the MyST
    substitution ``{{ positions }}`` so the narrative documentation can never
    drift from the generated vocabulary.

    Returns:
        The count of curated positions across the four design domains plus
        the ``uni``-level domains (the ``polUni`` root itself is not counted).
    """
    positions = _positions()
    in_domains = sum(len(_subtree(root_key, positions)) for root_key, _, _ in _DOMAINS)
    return in_domains + len(_uni_keys())


def _render_coverage() -> str:
    """The coverage matrix: every curated position, one row each."""
    positions = _positions()
    domain_rows = {
        root_key: [_coverage_row(pos) for pos in _subtree(root_key, positions)]
        for root_key, _, _ in _DOMAINS
    }
    uni_rows = [_coverage_row(positions[key]) for key in _uni_keys()]
    total = curated_position_count()

    table_header = [
        "| position | ACI class | makers | bind aliases | verbs | sugar | atomic |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    lines = [
        _HEADER,
        "# Coverage matrix",
        "",
        f"**{total} curated positions** across the four design domains plus "
        "the `uni`-level domains.  Everything else in the 2,222 generated "
        "classes stays reachable through `.mo(Class, ...)` and "
        "`bind_dn(alias=dn)` — see the design guide.",
        "",
    ]
    for root_key, title, _ in _DOMAINS:
        lines += [f"## {title.split(' — ')[0]}", "", *table_header, *domain_rows[root_key], ""]
    lines += ["## domains under `uni`", "", *table_header, *uni_rows, ""]

    lines += [
        "## Not curated yet",
        "",
        "Commonly requested areas that still speak raw ACI (`.mo()` / `bind_dn()`) today:",
        "",
        *(f"- **{title}** — {detail}" for title, detail, _ in _NOT_CURATED),
        "",
        "Curation grows by demand: if one of these (or anything else) is your "
        "daily work, open a "
        "[vocabulary request](https://github.com/k3l0-dev/niwaki/issues/new/choose).",
    ]
    return "\n".join(lines).rstrip() + "\n"


_UNI_DOMAIN = (
    "uni",
    "uni — domains",
    "Physical and routed domains, declared directly under `uni` — the bridge "
    "between access policies and the tenant world.",
)


def render_all() -> dict[str, str]:
    """Render every reference page as ``{relative path: content}``.

    One page per curated position (under its domain folder), one index per
    domain, plus the enums, the navigation vocabulary and the coverage matrix.
    """
    positions = _positions()
    names = _cursor_names(positions)
    used_enums: set[str] = set()

    pages: dict[str, str] = {}
    for root_key, title, blurb in [*_DOMAINS, _UNI_DOMAIN]:
        if root_key == "uni":
            subtree = [positions[key] for key in _uni_keys()]
            pages["uni.md"] = _render_uni_domain(subtree)
        else:
            subtree = _subtree(root_key, positions)
            pages[f"{root_key}.md"] = _render_domain(root_key, title, blurb)
        folder = root_key
        for pos in subtree:
            path = f"{folder}/{position_slug(pos.key)}.md"
            pages[path] = _render_position_page(pos, positions, names, used_enums)

    pages["index.md"] = _render_index()
    pages["enums.md"] = _render_enums(used_enums)
    pages["navigation.md"] = _render_navigation()
    pages["coverage.md"] = _render_coverage()
    return pages


def _render_uni_domain(subtree: list[_Position]) -> str:
    """Index of the ``uni``-level domains (physical / routed)."""
    lines = [
        _HEADER,
        f"# {_UNI_DOMAIN[1]}",
        "",
        _UNI_DOMAIN[2],
        "",
        "## Positions",
        "",
    ]
    for pos in subtree:
        cls = _load_class(pos.aci_class)
        n_fields = len(field_docs(cls, _tables().sugar.get(pos.aci_class, {})))
        lines.append(
            f"- {{ref}}`{pos.key} <{position_anchor(pos.key)}>` "
            f"— `{pos.aci_class}`, {n_fields} attributes"
        )
    lines += [
        "",
        "```{toctree}",
        ":maxdepth: 1",
        ":hidden:",
        "",
        *(f"uni/{position_slug(pos.key)}" for pos in subtree),
        "```",
    ]
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    """Generate and write the DSL reference (removing stale pages first)."""
    import shutil

    for folder in [*(root for root, _, _ in _DOMAINS), "uni"]:
        shutil.rmtree(OUTPUT_DIR / folder, ignore_errors=True)

    pages = render_all()
    for path, content in pages.items():
        target = OUTPUT_DIR / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    print(f"generate_docs: wrote {len(pages)} pages to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
