# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.CommAdminState import CommAdminState

from niwaki.models.base import ManagedObject


class commShellinabox(ManagedObject):
    """ACI Managed Object: ``commShellinabox`` — Shellinabox Service.

    RN format: ``shellinabox``
    """

    _aci_class: ClassVar[str] = "commShellinabox"
    _rn_format: ClassVar[str] = "shellinabox"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["aaa", "admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    admin_state: CommAdminState = Field(
        default=CommAdminState.DISABLED,
        validation_alias="adminSt",
        serialization_alias="adminSt",
        description="The administrative state of the object or policy.",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="The description of this configuration item.",
        ),
    ] = ""
    name: Annotated[
        str,
        Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", description="The name of the object."),
    ] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
