# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.RtctrlSetType import RtctrlSetType
from niwaki.models._generated.enums.RtmapSetCriteria import RtmapSetCriteria

from niwaki.models.base import ManagedObject


class rtctrlSetAddComm(ManagedObject):
    """ACI Managed Object: ``rtctrlSetAddComm``.

    RN format: ``saddcomm-{community}``
    """

    _aci_class: ClassVar[str] = "rtctrlSetAddComm"
    _rn_format: ClassVar[str] = "saddcomm-{community}"
    _naming_props: ClassVar[list[str]] = ["community"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-ext-connectivity"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    community: Annotated[str, Field(description="Community value")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    set_criteria: RtmapSetCriteria = Field(
        default=RtmapSetCriteria.APPEND,
        validation_alias="setCriteria",
        serialization_alias="setCriteria",
        description="setCriteria value",
    )
    type: RtctrlSetType = RtctrlSetType.COMMUNITY
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
