# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.DhcpOwner import DhcpOwner
from niwaki.models._generated.enums.DhcpRelayVisibility import DhcpRelayVisibility

from niwaki.models.base import ManagedObject


class dhcpRelayP(ManagedObject):
    """ACI Managed Object: ``dhcpRelayP`` — DHCP Relay Policy.

    RN format: ``relayp-{name}``
    """

    _aci_class: ClassVar[str] = "dhcpRelayP"
    _rn_format: ClassVar[str] = "relayp-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "dhcpRsProv",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "custom-port-privilege", "tenant-protocol"]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    relay_mode: DhcpRelayVisibility = Field(default=DhcpRelayVisibility.VISIBLE, alias="mode")
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    owner: DhcpOwner = DhcpOwner.INFRA
    owner_key: Annotated[
        str,
        Field(
            max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="ownerKey"
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(max_length=64, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="ownerTag"),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
