# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class igmpSnoopStaticGroup(ManagedObject):
    """ACI Managed Object: ``igmpSnoopStaticGroup`` — IGMP Snooping Static Membership configuration.

    Representation of an IGMP snooping static (*,G) or (S,G) membership

    RN format: ``group-[{multicast_group_ip}]-source-[{multicast_source_ip}]``
    """

    _aci_class: ClassVar[str] = "igmpSnoopStaticGroup"
    _rn_format: ClassVar[str] = "group-[{multicast_group_ip}]-source-[{multicast_source_ip}]"
    _naming_props: ClassVar[list[str]] = ["multicast_group_ip", "multicast_source_ip"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "tenant-epg", "tenant-network-profile", "tenant-protocol"]
    )
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    multicast_group_ip: Annotated[
        str,
        Field(
            pattern="^[0-9a-fA-F.:/ ]+$",
            alias="group",
            description="Group Address of IGMP snooping Static Entry",
        ),
    ]
    multicast_source_ip: Annotated[
        str,
        Field(
            pattern="^[0-9a-fA-F.:/ ]+$",
            alias="source",
            description="Source Address of IGMP snooping Static Entry, 0 in case of (*,G) entry",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", description="null")] = (
        ""
    )
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
