# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Literal, Annotated
from pydantic import AfterValidator, Field

from niwaki.models._wire import named_number
from niwaki.models.base import ManagedObject


class igmpStateLPol(ManagedObject):
    """ACI Managed Object: ``igmpStateLPol`` — State Limit Policy.

    RN format: ``igmpstateLPol``
    """

    _aci_class: ClassVar[str] = "igmpStateLPol"
    _rn_format: ClassVar[str] = "igmpstateLPol"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "rtdmcRsFilterToRtMapPol",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-ext-protocol"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    maximum_multicast_entries: Annotated[
        Annotated[int, Field(ge=1, le=4294967295)] | Literal["unlimited"],
        AfterValidator(named_number({"4294967295": "unlimited"})),
        Field(validation_alias="max", serialization_alias="max"),
    ] = "unlimited"
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    reserved_multicast_entries: Annotated[
        Annotated[int, Field(ge=1, le=4294967295)] | Literal["undefined"],
        AfterValidator(named_number({"0": "undefined"})),
        Field(validation_alias="rsvd", serialization_alias="rsvd"),
    ] = "undefined"
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
