# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class fvRsBDToProfile(ManagedObject):
    """ACI Managed Object: ``fvRsBDToProfile`` — Route Control Profile.

    A source relation to external networks that are routed via Layer 3 networks outside the fabric that are reachable by a tenant's applications. This is an internal object.

    RN format: ``rsBDToProfile``
    """

    _aci_class: ClassVar[str] = "fvRsBDToProfile"
    _rn_format: ClassVar[str] = "rsBDToProfile"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-connectivity"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    tn_l3ext_out_name: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            alias="tnL3extOutName",
            description="The layer 3 outside interface identifier controlling connectivity to outside networks.",
        ),
    ] = ""
    name: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            alias="tnRtctrlProfileName",
            description="The associated route profile name.",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
