# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.QosTenantPrio import QosTenantPrio
from niwaki.models._generated.enums.VzIntent import VzIntent
from niwaki.models._generated.enums.VzMatchT import VzMatchT

from niwaki.models.base import ManagedObject


class fvRsProv(ManagedObject):
    """ACI Managed Object: ``fvRsProv`` — Contract Provider.

    A contract for which the EPG will be a provider.

    RN format: ``rsprov-{name}``
    """

    _aci_class: ClassVar[str] = "fvRsProv"
    _rn_format: ClassVar[str] = "rsprov-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _fault_codes: ClassVar[dict[str, str]] = {
        "F0974": "fltFvRsProvResolveFail",
    }
    _relation_info: ClassVar[dict[str, str | bool]] = {
        "cardinality": "n-to-m",
        "enforceable": True,
        "resolvable": True,
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagExtMngdInst",
            "tagInst",
            "tagTag",
            "vzProvLbl",
            "vzProvSubjLbl",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "tenant-epg", "tenant-network-profile"]
    )
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            validation_alias="tnVzBrCPName",
            serialization_alias="tnVzBrCPName",
            description="The provider contract name.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    intent: VzIntent = VzIntent.INSTALL
    match_t: VzMatchT = Field(
        default=VzMatchT.ATLEASTONE,
        validation_alias="matchT",
        serialization_alias="matchT",
        description="The matched EPG type.",
    )
    priority: QosTenantPrio = Field(
        default=QosTenantPrio.UNSPECIFIED,
        validation_alias="prio",
        serialization_alias="prio",
        description="The system class determines the quality of service and priority for the consumer traffic.",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
