# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class apBasePackage(ManagedObject):
    """ACI Managed Object: ``apBasePackage`` — Information about APIC Base Package.

    BasePackage Info

    RN format: ``basepkg-{app_ctx_root}``
    """

    _aci_class: ClassVar[str] = "apBasePackage"
    _rn_format: ClassVar[str] = "basepkg-{app_ctx_root}"
    _naming_props: ClassVar[list[str]] = ["app_ctx_root"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "nw-svc-policy"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    app_ctx_root: Annotated[
        str, Field(min_length=1, max_length=512, alias="appCtxRoot", description="app Context Root")
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    apps: Annotated[str, Field(max_length=512, description="Apps in Package")] = ""
    name: Annotated[str, Field(min_length=1, max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    num_apps: Annotated[int, Field(alias="numApps")] = 0
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
