# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.ApAppType import ApAppType
from niwaki.models._generated.enums.ApClusterManagerType import ApClusterManagerType
from niwaki.models._generated.enums.ApConfSt import ApConfSt
from niwaki.models._generated.enums.ApPluginState import ApPluginState
from niwaki.models._generated.enums.ApPluginType import ApPluginType

from niwaki.models.base import ManagedObject


class apPlugin(ManagedObject):
    """ACI Managed Object: ``apPlugin`` — Information about APIC app.

    RN format: ``plugin-{app_ctx_root}``
    """

    _aci_class: ClassVar[str] = "apPlugin"
    _rn_format: ClassVar[str] = "plugin-{app_ctx_root}"
    _naming_props: ClassVar[list[str]] = ["app_ctx_root"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "apAnomaly",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "nw-svc-policy"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    app_ctx_root: Annotated[str, Field(min_length=1, max_length=512, alias="appCtxRoot")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    app_type: ApAppType = Field(default=ApAppType.REGULAR, alias="appType")
    cluster_manager_type: ApClusterManagerType = Field(
        default=ApClusterManagerType.NONE, alias="clusterManagerType"
    )
    config_st: ApConfSt = Field(default=ApConfSt.NONE, alias="configSt")
    name: Annotated[str, Field(min_length=1, max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    plugin_st: ApPluginState = Field(default=ApPluginState.INACTIVE, alias="pluginSt")
    plugin_type: ApPluginType = Field(default=ApPluginType.STATELESS, alias="pluginType")
    role: Annotated[str, Field(max_length=512)] = ""
    security_domains: Annotated[str, Field(max_length=512, alias="securityDomains")] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    username: Annotated[str, Field(max_length=512)] = ""
