# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class fabricRsApplTechSupPSched(ManagedObject):
    """ACI Managed Object: ``fabricRsApplTechSupPSched`` — Tech Support Policy.

    RN format: ``rsapplTechSupPSched-{name}``
    """

    _aci_class: ClassVar[str] = "fabricRsApplTechSupPSched"
    _rn_format: ClassVar[str] = "rsapplTechSupPSched-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _fault_codes: ClassVar[dict[str, str]] = {
        "F3716": "fltFabricRsApplTechSupPSchedResolveFail",
    }
    _relation_info: ClassVar[dict[str, str | bool]] = {
        "cardinality": "n-to-m",
        "enforceable": True,
        "resolvable": True,
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "fabric-connectivity", "fabric-equipment", "fabric-protocol"]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            validation_alias="tnDbgexpTechSupPName",
            serialization_alias="tnDbgexpTechSupPName",
            description="The name of the tech support export policy. This name can be up to 64 characters. Note that you cannot change this name after the object has been saved.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
