# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class fabricRsLeCardPGrp(ManagedObject):
    """ACI Managed Object: ``fabricRsLeCardPGrp`` — Leaf Module Policy Group.

    A source relation to the leaf card policy group.

    RN format: ``rsleCardPGrp``
    """

    _aci_class: ClassVar[str] = "fabricRsLeCardPGrp"
    _rn_format: ClassVar[str] = "rsleCardPGrp"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "fabric-equipment"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    target_dn: str = Field(
        default="", alias="tDn", description="The distinguished name of the leaf card policy group."
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
