# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class cloudAD(ManagedObject):
    """ACI Managed Object: ``cloudAD`` — Active Directory.

    Azure Active Directory

    RN format: ``ad-{ad_id}``
    """

    _aci_class: ClassVar[str] = "cloudAD"
    _rn_format: ClassVar[str] = "ad-{ad_id}"
    _naming_props: ClassVar[list[str]] = ["ad_id"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    ad_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=512,
            validation_alias="id",
            serialization_alias="id",
            description="AAD ID",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    name: Annotated[
        str,
        Field(max_length=16, pattern="^[a-zA-Z0-9_.:-]+$", description="The name of the object."),
    ] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
