# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class eqptdiagpRsExtChCardOdDiag(ManagedObject):
    """ACI Managed Object: ``eqptdiagpRsExtChCardOdDiag`` — Relation to Extended Chassis Module.

    A source relation to the extended chassis. An extended chassis is an extension of the fabric. Note that this relation is an internal object.

    RN format: ``rsextChCardOdDiag-[{target_dn}]``
    """

    _aci_class: ClassVar[str] = "eqptdiagpRsExtChCardOdDiag"
    _rn_format: ClassVar[str] = "rsextChCardOdDiag-[{target_dn}]"
    _naming_props: ClassVar[list[str]] = ["target_dn"]
    _relation_info: ClassVar[dict[str, str | bool]] = {
        "cardinality": "1-to-m",
        "enforceable": True,
        "resolvable": True,
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["access-connectivity", "access-equipment", "admin"]
    )
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    target_dn: Annotated[str, Field(alias="tDn", description="The target FEX module.")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
