# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import BeforeValidator, Field

from niwaki.models._wire import Flags, parse_flags
from niwaki.models._generated.enums.EqptdiagLeOdLcTestBmT import EqptdiagLeOdLcTestBmT
from niwaki.models._generated.enums.EqptdiagpAdminSt import EqptdiagpAdminSt

from niwaki.models.base import ManagedObject


class eqptdiagpLeTsOdLc(ManagedObject):
    """ACI Managed Object: ``eqptdiagpLeTsOdLc`` — Leaf Linecard On-demand Diags.

    The diagnostic on-demand test set for leaf fabric nodes to run on line cards (I/O cards).

    RN format: ``leOdLcDiags-{name}``
    """

    _aci_class: ClassVar[str] = "eqptdiagpLeTsOdLc"
    _rn_format: ClassVar[str] = "leOdLcDiags-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "eqptdiagpRsLcOdDiag",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "fabric-connectivity", "fabric-equipment", "ops"]
    )
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The name of the diagnostic test set.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    administrative_state: EqptdiagpAdminSt = Field(
        default=EqptdiagpAdminSt.START,
        validation_alias="adminSt",
        serialization_alias="adminSt",
        description="Administrative state of the diag policy",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    bitmask_of_diagnostics_tests_to_be_run: Annotated[
        Flags[EqptdiagLeOdLcTestBmT], BeforeValidator(parse_flags)
    ] = Field(
        default_factory=lambda: frozenset({EqptdiagLeOdLcTestBmT.NONE}),
        validation_alias="diagsBm",
        serialization_alias="diagsBm",
        description="The bitmask of diagnostic test groups that are enabled.",
    )
    full_diagnostics: Annotated[Flags[EqptdiagLeOdLcTestBmT], BeforeValidator(parse_flags)] = Field(
        default_factory=lambda: frozenset({EqptdiagLeOdLcTestBmT.NONE}),
        validation_alias="fullBm",
        serialization_alias="fullBm",
        description="A bitmask of test groups for which a full set of tests are enabled.",
    )
    include_disruptive_tests_in_the_grp: bool = Field(
        default=False,
        validation_alias="inclDisruptive",
        serialization_alias="inclDisruptive",
        description="Flag to control if disruptive tests from the group should be run or not. Default value is false.",
    )
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerKey",
            serialization_alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerTag",
            serialization_alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
