# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Literal, Annotated
from pydantic import AfterValidator, Field

from niwaki.models._wire import named_number
from niwaki.models._generated.enums.DatetimeAdminState import DatetimeAdminState

from niwaki.models.base import ManagedObject


class datetimePol(ManagedObject):
    """ACI Managed Object: ``datetimePol`` — Date and Time Policy.

    The date time policy is based on international time zones and a defined NTP server. Before configuring a date and time policy under a domain group, this policy must first be created. Policies under the Domain Groups root were already created by the system and ready to configure.

    RN format: ``time-{name}``
    """

    _aci_class: ClassVar[str] = "datetimePol"
    _rn_format: ClassVar[str] = "time-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "datetimeNtpAuthKey",
            "datetimeNtpIFFClientKey",
            "datetimeNtpProv",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "fabric-protocol"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The user-configured date/time policy name. This value can be between 1 and 64 alphanumeric characters. Note that you cannot change this name after the object has been saved.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    ntp_stratum_value_see_ntp_rfc_5905: Annotated[
        Annotated[int, Field(ge=1, le=14)] | Literal["primary"],
        AfterValidator(named_number({"1": "primary"})),
        Field(
            validation_alias="StratumValue",
            serialization_alias="StratumValue",
            description="NTP Stratum value, see RFC 5905",
        ),
    ] = 8
    admin_state: DatetimeAdminState = Field(
        default=DatetimeAdminState.ENABLED,
        validation_alias="adminSt",
        serialization_alias="adminSt",
        description="A property that indicates if the NTP protocol is enabled or disabled.",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    authentication_state: DatetimeAdminState = Field(
        default=DatetimeAdminState.DISABLED,
        validation_alias="authSt",
        serialization_alias="authSt",
        description="A property that indicates if the Datetime policy authentication is enabled or disabled.",
    )
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    master_clock_mode_toggle: DatetimeAdminState = Field(
        default=DatetimeAdminState.DISABLED,
        validation_alias="masterMode",
        serialization_alias="masterMode",
        description="Toggle between master clock mode",
    )
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerKey",
            serialization_alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerTag",
            serialization_alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    server_mode: DatetimeAdminState = Field(
        default=DatetimeAdminState.DISABLED,
        validation_alias="serverState",
        serialization_alias="serverState",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
