# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.GenericsFetchingOperation import GenericsFetchingOperation

from niwaki.models.base import ManagedObject


class genericsNode(ManagedObject):
    """ACI Managed Object: ``genericsNode`` — Generic Node.

    RN format: ``node-{class_}-{node_tag}``
    """

    _aci_class: ClassVar[str] = "genericsNode"
    _rn_format: ClassVar[str] = "node-{class_}-{node_tag}"
    _naming_props: ClassVar[list[str]] = ["class_", "node_tag"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    class_: Annotated[str, Field(min_length=1, max_length=512, alias="class")]
    node_tag: Annotated[str, Field(min_length=1, max_length=512, alias="tag")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    fetch_from_node_tag: Annotated[str, Field(max_length=512, alias="fetchFrom")] = ""
    fetching_operation: GenericsFetchingOperation = Field(
        default=GenericsFetchingOperation.ANCESTOR, alias="fetchUsing"
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
