# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.FteDefPolicyT import FteDefPolicyT
from niwaki.models._generated.enums.FteDirectionT import FteDirectionT
from niwaki.models._generated.enums.FteFltType import FteFltType

from niwaki.models.base import ManagedObject


class fteFwdInstTarget(ManagedObject):
    """ACI Managed Object: ``fteFwdInstTarget`` — Forward Instance Target.

    Forwarding instance based target

    RN format: ``fwdinst-{identifier}``
    """

    _aci_class: ClassVar[str] = "fteFwdInstTarget"
    _rn_format: ClassVar[str] = "fwdinst-{identifier}"
    _naming_props: ClassVar[list[str]] = ["identifier"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "fteRsMonitorAtt",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    identifier: Annotated[int, Field(ge=0, le=16777215, alias="id", description="Identifier")] = 0

    # ── Configurable ───────────────────────────────────────────────────────────
    default_filtering_policy: FteDefPolicyT = Field(
        default=FteDefPolicyT.PERMIT, alias="DefPolicy", description="Default filtering policy"
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    timestamp_shift_value_for_burst_interval: str = Field(
        default="", alias="burstIntvlShift", description="Burst interval shift"
    )
    collect_interval_in_milliseconds: Annotated[
        int, Field(ge=100, le=64000, alias="collectIntvl", description="Collect interval")
    ] = 100
    collector_id: Annotated[
        int,
        Field(
            ge=0,
            le=65535,
            alias="collectorId",
            description="Collector identifier provided by the analytics controller",
        ),
    ] = 0
    direction: FteDirectionT = Field(default=FteDirectionT.IN, alias="dir", description="Direction")
    netflow_fte_type: FteFltType = Field(
        default=FteFltType.IPV4, alias="fltType", description="IP filter type"
    )
    ip_packet_id_shift: str = Field(
        default="", alias="ipPktIdShift", description="IP packet id shift"
    )
    mtu: Annotated[str, Field(description="Collector export packet MTU")] = ""
    sequence_number_guess_threshold_high: Annotated[
        int,
        Field(
            ge=0,
            le=4294967295,
            alias="seqNumGuessThreshHi",
            description="Sequence number guess threshold high",
        ),
    ] = 0
    sequence_number_guess_threshold_low: Annotated[
        int,
        Field(
            ge=0,
            le=4294967295,
            alias="seqNumGuessThreshLo",
            description="Sequence number guess threshold low",
        ),
    ] = 0
    source_l4_port: Annotated[
        int, Field(ge=1, le=65535, alias="srcPort", description="Source port")
    ] = 0
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
