# ruff: noqa
# Generated ACI package: health
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

_CLASSES: dict[str, str] = {
    "CtrlrRetP": "healthCtrlrRetP",
    "EvalP": "healthEvalP",
    "LevelP": "healthLevelP",
    "LevelsP": "healthLevelsP",
    "Pol": "healthPol",
    "PolCont": "healthPolCont",
    "RecalcP": "healthRecalcP",
    "SwRetP": "healthSwRetP",
}


def __getattr__(name: str) -> type:
    full = _CLASSES.get(name)
    if full is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    mod = import_module(f".{full}", __name__)
    cls = getattr(mod, full)
    globals()[name] = cls
    return cls


__all__ = list(_CLASSES)
