# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.RtctrlRedistributeSrcType import RtctrlRedistributeSrcType

from niwaki.models.base import ManagedObject


class l3extRsRedistributePol(ManagedObject):
    """ACI Managed Object: ``l3extRsRedistributePol`` — Context Policy for OSPF, EIGRP or Static Routes Redistribution.

    RN format: ``rsredistributePol-[{name}]-{src}``
    """

    _aci_class: ClassVar[str] = "l3extRsRedistributePol"
    _rn_format: ClassVar[str] = "rsredistributePol-[{name}]-{src}"
    _naming_props: ClassVar[list[str]] = ["name", "src"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-ext-connectivity"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    src: RtctrlRedistributeSrcType = RtctrlRedistributeSrcType.STATIC
    name: Annotated[
        str,
        Field(
            min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", alias="tnRtctrlProfileName"
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
