# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class l3extRsInstPToNatMappingEPg(ManagedObject):
    """ACI Managed Object: ``l3extRsInstPToNatMappingEPg`` — Relation to NAT Mapping EPg.

    RN format: ``rsInstPToNatMappingEPg``
    """

    _aci_class: ClassVar[str] = "l3extRsInstPToNatMappingEPg"
    _rn_format: ClassVar[str] = "rsInstPToNatMappingEPg"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagExtMngdInst",
            "tagInst",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-ext-connectivity"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    target_dn: str = Field(default="", alias="tDn")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
