# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class mplsNodeSidP(ManagedObject):
    """ACI Managed Object: ``mplsNodeSidP`` — Node Sid Profile.

    RN format: ``nodesidp-{srgb_index}``
    """

    _aci_class: ClassVar[str] = "mplsNodeSidP"
    _rn_format: ClassVar[str] = "nodesidp-{srgb_index}"
    _naming_props: ClassVar[list[str]] = ["srgb_index"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-ext-connectivity"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    srgb_index: Annotated[int, Field(alias="sidoffset")] = 0

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    loopback_address_for_mpls_data_plane: Annotated[
        str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="loopbackAddr")
    ] = ""
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
