# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class syntheticClusterTestShardInstance(ManagedObject):
    """ACI Managed Object: ``syntheticClusterTestShardInstance`` — Test Object to Represent a Shard Instance.

    RN format: ``cltsi-{service_name}-{shard_id}-{system_id}``
    """

    _aci_class: ClassVar[str] = "syntheticClusterTestShardInstance"
    _rn_format: ClassVar[str] = "cltsi-{service_name}-{shard_id}-{system_id}"
    _naming_props: ClassVar[list[str]] = ["service_name", "shard_id", "system_id"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    shard_id: Annotated[str, Field(alias="shard")]
    service_name: Annotated[str, Field(min_length=1, max_length=512, alias="svc")]
    system_id: Annotated[int, Field(alias="systemId")] = 0

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
