# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.ActionAdminSt import ActionAdminSt
from niwaki.models._generated.enums.ActionType import ActionType

from niwaki.models.base import ManagedObject


class l1EthIfSetInServiceLTask(ManagedObject):
    """ACI Managed Object: ``l1EthIfSetInServiceLTask``.

    A task object to put a port in-service (allow it to forward data traffic) or out-of-service (prevent it from forwarding any data traffic).

    RN format: ``l1EthIfSetInServiceLTask``
    """

    _aci_class: ClassVar[str] = "l1EthIfSetInServiceLTask"
    _rn_format: ClassVar[str] = "l1EthIfSetInServiceLTask"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    admin_state: ActionAdminSt = Field(
        default=ActionAdminSt.UNKNOWN,
        alias="adminSt",
        description="The administrative state of the object or policy.",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    task_frequency: str = Field(
        default="", alias="freq", description="Frequency at which tasks are executed"
    )
    type: ActionType = Field(
        default=ActionType.INTERFACE_IN_SERVICE,
        description="The specific type of the object or component.",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
