# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.ActionAdminSt import ActionAdminSt
from niwaki.models._generated.enums.ActionType import ActionType

from niwaki.models.base import ManagedObject


class topSystemPingLTask(ManagedObject):
    """ACI Managed Object: ``topSystemPingLTask``.

    RN format: ``topSystemPingLTask``
    """

    _aci_class: ClassVar[str] = "topSystemPingLTask"
    _rn_format: ClassVar[str] = "topSystemPingLTask"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-connectivity"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    admin_state: ActionAdminSt = Field(
        default=ActionAdminSt.UNKNOWN,
        alias="adminSt",
        description="The administrative state of the object or policy.",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    ctrl: str = ""
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    dst_ip: Annotated[str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="dstIp")] = ""
    task_frequency: str = Field(
        default="", alias="freq", description="Frequency at which tasks are executed"
    )
    num_pkt: str = Field(default="", alias="numPkt")
    pkt_sz: str = Field(default="", alias="pktSz")
    send_intvl: str = Field(default="", alias="sendIntvl")
    src_if: str = Field(default="", alias="srcIf")
    src_ip: Annotated[str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="srcIp")] = ""
    timeout: str = ""
    tos: str = ""
    ttl: str = ""
    type: ActionType = Field(
        default=ActionType.CLEAR, description="The specific type of the object or component."
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    vrf: Annotated[str, Field(max_length=512)] = ""
