# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.EigrpDelayUnit import EigrpDelayUnit
from niwaki.models._generated.enums.EigrpIfAfControl import EigrpIfAfControl

from niwaki.models.base import ManagedObject


class eigrpIfPol(ManagedObject):
    """ACI Managed Object: ``eigrpIfPol`` — EIGRP Interface Policy.

    RN format: ``eigrpIfPol-{name}``
    """

    _aci_class: ClassVar[str] = "eigrpIfPol"
    _rn_format: ClassVar[str] = "eigrpIfPol-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-ext-protocol"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    eigrp_interface_bandwidth: Annotated[int, Field(ge=0, le=2560000000, alias="bw")] = 0
    interface_controls: EigrpIfAfControl = Field(default=EigrpIfAfControl.BFD, alias="ctrl")
    eigrp_interface_delay: Annotated[int, Field(ge=0, alias="delay")] = 0
    units_for_eigrp_interface_delay: EigrpDelayUnit = Field(
        default=EigrpDelayUnit.TENS_OF_MICRO, alias="delayUnit"
    )
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    hello_interval: str = Field(default="", alias="helloIntvl")
    hold_interval: str = Field(default="", alias="holdIntvl")
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="ownerKey"
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(max_length=64, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="ownerTag"),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
