# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.LicenseAdminState import LicenseAdminState
from niwaki.models._generated.enums.LicenseFeatureLicense import LicenseFeatureLicense
from niwaki.models._generated.enums.LicenseFeatureMode import LicenseFeatureMode

from niwaki.models.base import ManagedObject


class licenseFeature(ManagedObject):
    """ACI Managed Object: ``licenseFeature`` — Licensed Feature.

    RN format: ``feature-{entitlement_tag_name}``
    """

    _aci_class: ClassVar[str] = "licenseFeature"
    _rn_format: ClassVar[str] = "feature-{entitlement_tag_name}"
    _naming_props: ClassVar[list[str]] = ["entitlement_tag_name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "licenseFeatureEntitlement",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    entitlement_tag_name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=512,
            validation_alias="featureName",
            serialization_alias="featureName",
            description="Name of the feature",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    entitlement_tag_description: LicenseAdminState = Field(
        default=LicenseAdminState.DISABLED,
        validation_alias="adminSt",
        serialization_alias="adminSt",
        description="Admin State of the app that says if it is enabled/disabled",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    feature_license_type: LicenseFeatureLicense = Field(
        default=LicenseFeatureLicense.NONE,
        validation_alias="licenseType",
        serialization_alias="licenseType",
        description="Defines if the license type of the feature is leaf-based or not",
    )
    mode: LicenseFeatureMode = Field(
        default=LicenseFeatureMode.NONE,
        description='Feature mode defines if the feature is running in basic/advanced/single mode "single" means feature has only one mode',
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
