# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class pimExtP(ManagedObject):
    """ACI Managed Object: ``pimExtP`` — External Profile.

    OSPF external profile.

    RN format: ``pimextp``

    The APIC can flag these accepted-but-inconsistent states on this class
    (read-only ``configIssues``):

    - ``csw-invalid-pod-id``
    - ``intervrf-route-map-empty``
    - ``missing-rp-group-range``
    - ``pim-not-supported-in-vpc-mode``
    - ``pim-not-supported-on-ext-svi``
    - ``pim-not-supported-on-floating-svi``
    - ``src-only-route-map-allowed``
    """

    _aci_class: ClassVar[str] = "pimExtP"
    _rn_format: ClassVar[str] = "pimextp"
    _naming_props: ClassVar[list[str]] = []
    _config_issues: ClassVar[dict[str, str]] = {
        "csw-invalid-pod-id": "",
        "intervrf-route-map-empty": "",
        "missing-rp-group-range": "",
        "ok": "",
        "pim-not-supported-in-vpc-mode": "",
        "pim-not-supported-on-ext-svi": "",
        "pim-not-supported-on-floating-svi": "",
        "src-only-route-map-allowed": "",
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "tenant-ext-connectivity", "tenant-ext-protocol"]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    enabled_pim_address_families: str = Field(
        default="", alias="enabledAf", description="Enabled Multicast Address Families"
    )
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
