# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.ApphostingAdminState import ApphostingAdminState
from niwaki.models._generated.enums.ApphostingSignOption import ApphostingSignOption

from niwaki.models.base import ManagedObject


class apphostingAppGlobalCfg(ManagedObject):
    """ACI Managed Object: ``apphostingAppGlobalCfg`` — App hosting global config.

    1.3 app hosting global config MO1.3 AppGlobalCfg [dn] /sys/apphosting/globalcfg

    RN format: ``globalcfg``
    """

    _aci_class: ClassVar[str] = "apphostingAppGlobalCfg"
    _rn_format: ClassVar[str] = "globalcfg"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "ops"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    admin_st: ApphostingAdminState = Field(
        default=ApphostingAdminState.ENABLED,
        validation_alias="adminSt",
        serialization_alias="adminSt",
        description='Admin state to configure mo "',
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    enable_or_disable_signed_verification: ApphostingSignOption = Field(
        default=ApphostingSignOption.ENABLE,
        validation_alias="signVerify",
        serialization_alias="signVerify",
        description="properties to enable or disable signed verification",
    )
    storage_limit: Annotated[
        int,
        Field(
            ge=0,
            le=2147483647,
            validation_alias="storageLimit",
            serialization_alias="storageLimit",
            description="properties to set bootflash backend storage limit.",
        ),
    ] = 0
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
