# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.ApphostingAdminState import ApphostingAdminState

from niwaki.models.base import ManagedObject


class apphostingAppResourceCfg(ManagedObject):
    """ACI Managed Object: ``apphostingAppResourceCfg`` — App resource profile table.

    RN format: ``resource``
    """

    _aci_class: ClassVar[str] = "apphostingAppResourceCfg"
    _rn_format: ClassVar[str] = "resource"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "ops"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    admin_st: ApphostingAdminState = Field(default=ApphostingAdminState.ENABLED, alias="adminSt")
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    cpu_unit_allocation_for_this_profile: Annotated[int, Field(alias="cpu")] = 0
    disk_usg: str = Field(default="", alias="diskUsg")
    memory_allocation_for_this_profile: str = Field(default="", alias="memory")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
