# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.Dot1xMacAuth import Dot1xMacAuth

from niwaki.models.base import ManagedObject


class l2PortAuthCfgPol(ManagedObject):
    """ACI Managed Object: ``l2PortAuthCfgPol`` — 802.1x Port Authentication Configuration Policy.

    RN format: ``portauthcfgpol``
    """

    _aci_class: ClassVar[str] = "l2PortAuthCfgPol"
    _rn_format: ClassVar[str] = "portauthcfgpol"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["access-connectivity", "access-protocol", "admin", "custom-port-privilege"]
    )
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    mac_auth: Dot1xMacAuth = Field(
        default=Dot1xMacAuth.EAP,
        validation_alias="macAuth",
        serialization_alias="macAuth",
        description="MAC Auth",
    )
    max_reauth_request: Annotated[
        int,
        Field(
            ge=1,
            le=10,
            validation_alias="maxReauthReq",
            serialization_alias="maxReauthReq",
            description="Max Reauth Request",
        ),
    ] = 2
    max_request: Annotated[
        int,
        Field(
            ge=2,
            le=10,
            validation_alias="maxReq",
            serialization_alias="maxReq",
            description="Max Request",
        ),
    ] = 2
    re_authentication: bool = Field(
        default=False,
        validation_alias="reAuth",
        serialization_alias="reAuth",
        description="Re-authentication",
    )
    re_auth_period: Annotated[
        int,
        Field(
            ge=1,
            le=2147483,
            validation_alias="reAuthPeriod",
            serialization_alias="reAuthPeriod",
            description="Re-auth Period",
        ),
    ] = 3600
    server_timeout: Annotated[
        int,
        Field(
            ge=1,
            le=65535,
            validation_alias="serverTimeout",
            serialization_alias="serverTimeout",
            description="Server Timeout",
        ),
    ] = 30
    supplicant_timeout: Annotated[
        int,
        Field(
            ge=1,
            le=65535,
            validation_alias="suppTimeout",
            serialization_alias="suppTimeout",
            description="Supplicant Timeout",
        ),
    ] = 30
    tx_period: Annotated[
        int,
        Field(
            ge=1,
            le=65535,
            validation_alias="txPeriod",
            serialization_alias="txPeriod",
            description="Tx Period",
        ),
    ] = 30
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
