# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class firmwareFirmware(ManagedObject):
    """ACI Managed Object: ``firmwareFirmware`` — Firmware.

    The firmware specification.

    RN format: ``fw-{name}``
    """

    _aci_class: ClassVar[str] = "firmwareFirmware"
    _rn_format: ClassVar[str] = "fw-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(min_length=1, max_length=512, description="The firmware name.")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    action_to_delete: bool = Field(
        default=False,
        validation_alias="deleteIt",
        serialization_alias="deleteIt",
        description="A property for deleting firmware (when set to true). For internal use only.",
    )
    whether_latest: bool = Field(
        default=False,
        validation_alias="latest",
        serialization_alias="latest",
        description="A property that indicates whether the latest minor version.",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
