# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.QospPfcEnableScope import QospPfcEnableScope

from niwaki.models.base import ManagedObject


class qosPfcPol(ManagedObject):
    """ACI Managed Object: ``qosPfcPol`` — QOS Priority Flow Control Policy.

    RN format: ``pfcpol-{name}``
    """

    _aci_class: ClassVar[str] = "qosPfcPol"
    _rn_format: ClassVar[str] = "pfcpol-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["access-connectivity", "access-qos", "admin"]
    )
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The name of the object.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    priority_flow_control_admin_state: bool = Field(
        default=False,
        alias="adminSt",
        description="enable is for no drop policy, disable is for drop policy",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    priority_flow_control_enable_scope: QospPfcEnableScope = Field(
        default=QospPfcEnableScope.TOR, alias="enableScope"
    )
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    bitmap_of_nodrop_cos: str = Field(default="", alias="noDropCos")
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
