# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.HcisakmpAuthMethod import HcisakmpAuthMethod
from niwaki.models._generated.enums.HcisakmpDhGroup import HcisakmpDhGroup
from niwaki.models._generated.enums.HcisakmpEncrAlgo import HcisakmpEncrAlgo
from niwaki.models._generated.enums.HcisakmpHash import HcisakmpHash

from niwaki.models.base import ManagedObject


class isakmpPolicy(ManagedObject):
    """ACI Managed Object: ``isakmpPolicy`` — Isakmp Policy.

    Holds Isakmp Policy information

    RN format: ``policy-{priority}``
    """

    _aci_class: ClassVar[str] = "isakmpPolicy"
    _rn_format: ClassVar[str] = "policy-{priority}"
    _naming_props: ClassVar[list[str]] = ["priority"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    priority: Annotated[int, Field(ge=1, le=10000, description="IsaKmp Policy Priority")] = 1

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    auth_method: HcisakmpAuthMethod = Field(
        default=HcisakmpAuthMethod.PRE_SHARE,
        validation_alias="authMethod",
        serialization_alias="authMethod",
        description="Auth Type",
    )
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    diffie_hellman_group: HcisakmpDhGroup = Field(
        default=HcisakmpDhGroup._1,
        validation_alias="dhGroup",
        serialization_alias="dhGroup",
        description="Diffie Hellman Group",
    )
    encryption: HcisakmpEncrAlgo = Field(
        default=HcisakmpEncrAlgo.DES, description="Encryption algorithm for protection suite"
    )
    hash_algorithm: HcisakmpHash = Field(
        default=HcisakmpHash.MD5,
        validation_alias="hash",
        serialization_alias="hash",
        description="Hash for ISAKMP security association",
    )
    lifetime_for_isakmp_security_association: Annotated[
        int,
        Field(
            ge=60,
            le=86400,
            validation_alias="lifetime",
            serialization_alias="lifetime",
            description="lifetime for ISAKMP security association",
        ),
    ] = 28000
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerKey",
            serialization_alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerTag",
            serialization_alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
