# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Literal, Annotated
from pydantic import AfterValidator, Field

from niwaki.models._wire import named_number
from niwaki.models.base import ManagedObject


class segrtSrgb(ManagedObject):
    """ACI Managed Object: ``segrtSrgb`` — Segment Routing Global Block.

    Segment Routing Global Block

    RN format: ``srgb-{srgb_identifier}``
    """

    _aci_class: ClassVar[str] = "segrtSrgb"
    _rn_format: ClassVar[str] = "srgb-{srgb_identifier}"
    _naming_props: ClassVar[list[str]] = ["srgb_identifier"]
    _fault_codes: ClassVar[dict[str, str]] = {
        "F3725": "fltSegrtSrgbSrgbAllocationFailed",
        "F3726": "fltSegrtSrgbSrgbCleanupFailed",
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["access-protocol", "admin", "fabric-protocol", "tenant-ext-protocol", "tenant-protocol"]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    srgb_identifier: Annotated[
        int,
        Field(
            ge=1,
            le=64,
            validation_alias="localId",
            serialization_alias="localId",
            description="SRGB identifier",
        ),
    ] = 0

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    srgb_minimum_label: Annotated[
        Annotated[int, Field(ge=16000, le=471804)] | Literal["unspecified"],
        AfterValidator(named_number({"0": "unspecified"})),
        Field(
            validation_alias="srLblMax",
            serialization_alias="srLblMax",
            description="SRGB maximum label",
        ),
    ] = 23999
    sr_lbl_min: Annotated[
        Annotated[int, Field(ge=16000, le=471804)] | Literal["unspecified"],
        AfterValidator(named_number({"0": "unspecified"})),
        Field(
            validation_alias="srLblMin",
            serialization_alias="srLblMin",
            description="SRGB minimum label",
        ),
    ] = 16000
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
