# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.EdmCfgPreserveMode import EdmCfgPreserveMode
from niwaki.models._generated.enums.EdmEncapDeployMode import EdmEncapDeployMode

from niwaki.models.base import ManagedObject


class extdevSwMgrFlags(ManagedObject):
    """ACI Managed Object: ``extdevSwMgrFlags`` — Container for domain relations.

    Container for Switch Manager Policies

    RN format: ``fl``
    """

    _aci_class: ClassVar[str] = "extdevSwMgrFlags"
    _rn_format: ClassVar[str] = "fl"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["access-equipment", "admin", "fabric-equipment", "fabric-protocol"]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    dyn_loose_node_discovery: bool = Field(
        default=True,
        validation_alias="dynLooseNodeDiscovery",
        serialization_alias="dynLooseNodeDiscovery",
        description="Used to determine how Encaps are deployed to the target EDMGR",
    )
    encap_deploy_mode: EdmEncapDeployMode = Field(
        default=EdmEncapDeployMode.PREPROVISION,
        validation_alias="encapDeployMode",
        serialization_alias="encapDeployMode",
        description="Encap Deploy Mode",
    )
    nic_prof_cfg_preserve_mode: EdmCfgPreserveMode = Field(
        default=EdmCfgPreserveMode.PRESERVE,
        validation_alias="nicProfCfgPreserveMode",
        serialization_alias="nicProfCfgPreserveMode",
        description="NIC Profile Config Preservation Mode",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
