# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.ActionType import ActionType
from niwaki.models._generated.enums.EptrkOperStQual import EptrkOperStQual

from niwaki.models.base import ManagedObject


class eptrkMacEpRslt(ManagedObject):
    """ACI Managed Object: ``eptrkMacEpRslt`` — MAC EP Tracking Result.

    RN format: ``macrslt-{mac_address}``
    """

    _aci_class: ClassVar[str] = "eptrkMacEpRslt"
    _rn_format: ClassVar[str] = "macrslt-{mac_address}"
    _naming_props: ClassVar[list[str]] = ["mac_address"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "eptrkCompInfo",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "fabric-protocol", "tenant-ext-connectivity", "tenant-protocol"]
    )
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    mac_address: Annotated[
        str,
        Field(
            pattern="^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$",
            validation_alias="addr",
            serialization_alias="addr",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    ack: bool = Field(
        default=False,
        description="The acknowledgement status of the fault. If a fault is acknowledged and cleared, it is immediately deleted. If a fault is not acknowledged and cleared, it is deleted after the retention interval.",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    debug_internal_data: str = Field(
        default="", validation_alias="dbgInternalData", serialization_alias="dbgInternalData"
    )
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
        ),
    ] = ""
    trkendpoint_encap: str = Field(
        default="",
        validation_alias="encap",
        serialization_alias="encap",
        description="The port encapsulation.",
    )
    operational_state_qualifier: EptrkOperStQual = Field(
        default=EptrkOperStQual.OK,
        validation_alias="operStQual",
        serialization_alias="operStQual",
        description="The chassis operational status qualifier.",
    )
    type: ActionType = Field(
        default=ActionType.CLEAR, description="The specific type of the object or component."
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
