# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.VzMatchT import VzMatchT
from niwaki.models._generated.enums.VzPrefGrMemb import VzPrefGrMemb

from niwaki.models.base import ManagedObject


class vzAny(ManagedObject):
    """ACI Managed Object: ``vzAny`` — Any.

    vzAny associates all endpoint groups (EPGs) in a context (fvCtx) to one or more contracts (vzBrCP), rather than creating a separate contract relation for each EPG. EPGs can only communicate with other EPGs according to contract rules.

    RN format: ``any``
    """

    _aci_class: ClassVar[str] = "vzAny"
    _rn_format: ClassVar[str] = "any"
    _naming_props: ClassVar[list[str]] = []
    _fault_codes: ClassVar[dict[str, str]] = {
        "F0418": "fltVzAnyConfigurationFailed",
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
            "vzConsCtrctLbl",
            "vzConsLbl",
            "vzConsSubjLbl",
            "vzProvCtrctLbl",
            "vzProvLbl",
            "vzProvSubjLbl",
            "vzRsAnyToCons",
            "vzRsAnyToConsIf",
            "vzRsAnyToProv",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-connectivity"])
    _is_creatable: ClassVar[bool] = False
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    match_type: VzMatchT = Field(
        default=VzMatchT.ATLEASTONE,
        validation_alias="matchT",
        serialization_alias="matchT",
        description="Represents the provider label match criteria.",
    )
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    preferred_group_member: VzPrefGrMemb = Field(
        default=VzPrefGrMemb.DISABLED,
        validation_alias="prefGrMemb",
        serialization_alias="prefGrMemb",
        description="Represents parameter used to determine if EPgs can be divided in a the context can be divided in two subgroups.",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
