# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.PolColor import PolColor

from niwaki.models.base import ManagedObject


class vzProvSubjLbl(ManagedObject):
    """ACI Managed Object: ``vzProvSubjLbl`` — Subject Label.

    A subject label is used as classification criteria for subjects being consumed/provided by the endpoint groups (EPGs) participating in the contract. The label identifies a subject being provided by a provider. It can be parented by 2 different methods.

    RN format: ``provsubjlbl-{name}``
    """

    _aci_class: ClassVar[str] = "vzProvSubjLbl"
    _rn_format: ClassVar[str] = "provsubjlbl-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-security"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The provider label name.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    complement: bool = Field(
        default=False,
        alias="isComplement",
        description="Specify the behavior of the label. @@@ 1. true &amp;amp;amp;amp;amp;amp;amp;amp;&amp;amp;amp;amp;amp;amp;amp;amp; parent::MatchT==AND: Then this label should not match for @@@ the compound subject label statement across consumers to be true @@@ 2.",
    )
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    tag: PolColor = Field(
        default=PolColor.ALICE_BLUE, description="Specifies the color of a policy label."
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
