# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import BeforeValidator, Field

from niwaki.models._wire import Flags, parse_flags
from niwaki.models._generated.enums.VzRAction import VzRAction

from niwaki.models.base import ManagedObject


class vzRsDenyRule(ManagedObject):
    """ACI Managed Object: ``vzRsDenyRule`` — Deny Rule.

    A filter is a group of resolvable filter entries. Each filter entry is a combination of network traffic classification properties. Note that this relation is an internal object.

    RN format: ``rsdenyRule-{name}``
    """

    _aci_class: ClassVar[str] = "vzRsDenyRule"
    _rn_format: ClassVar[str] = "rsdenyRule-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _fault_codes: ClassVar[dict[str, str]] = {
        "F1129": "fltVzRsDenyRuleResolveFail",
    }
    _relation_info: ClassVar[dict[str, str | bool]] = {
        "cardinality": "n-to-m",
        "enforceable": True,
        "resolvable": True,
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-security"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            validation_alias="tnVzFilterName",
            serialization_alias="tnVzFilterName",
            description="The filter name.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    directives: Annotated[Flags[VzRAction], BeforeValidator(parse_flags)] = Field(
        default_factory=lambda: frozenset({VzRAction.NONE}),
        description="The filter directives assigned to the taboo contract.",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
