# ruff: noqa
# pyright: reportIncompatibleMethodOverride=false, reportUnnecessaryContains=false
# Generated by niwaki generate_design — do not edit manually.
# Re-generate: uv run python -m niwaki._codegen.generate_design
#
# The pyright/mypy override waivers are deliberate: typed cursors narrow the
# base Cursor signatures (set/bind take the curated kwargs), and same-label
# makers across ancestor mixins resolve by MRO — nearest level wins, exactly
# like the runtime.
#
# Typed cursor classes for the design DSL.  Signatures only — every body
# delegates to the dynamic runtime in niwaki.design._cursor.  Bodies read
# locals() at function entry (arguments only) and prune None values, so a
# parameter reaches the runtime only when the caller provided it.
"""Typed design cursors (generated) — uni domain."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

from niwaki.design._cursor import Cursor, _prune

if TYPE_CHECKING:
    from niwaki.design._generated_cursors._controller import ControllerCursor
    from niwaki.design._generated_cursors._fabric import FabricCursor
    from niwaki.design._generated_cursors._infra import InfraCursor
    from niwaki.design._generated_cursors._tenant import TenantCursor


class _UniMakers(Cursor):
    """Makers declared at the uni level (``polUni``)."""

    __slots__ = ()

    def tenant(
        self,
        name: str,
        *,
        annotation: str | None = None,
        description: str | None = None,
        display_name: str | None = None,
        owner_key: str | None = None,
        owner_tag: str | None = None,
        userdom: str | None = None,
    ) -> TenantCursor:
        """Declare a ``fvTenant`` child under the uni level.

        A policy owner in the virtual fabric. A tenant can be either a private or a shared entity.
        For example, you can create a tenant with contexts and bridge domains shared by other
        tenants. A shared type of tenant is typically named common, default, or infra.

        Args:
            name: The name of the tenant.
            annotation: User annotation. Suggested format orchestrator:value
            description: The description of the tenant.
            owner_key: The key for enabling clients to own their data for entity correlation.
            owner_tag: A tag for enabling clients to add their own data. For example, to
                indicate who created this object.
        """
        params = {
            k: v
            for k, v in locals().items()
            if k
            not in (
                "self",
                "name",
            )
        }
        return cast(
            "TenantCursor",
            self._invoke_maker("tenant", (name,), _prune(params)),
        )

    def infra(
        self,
        *,
        annotation: str | None = None,
        display_name: str | None = None,
        owner_key: str | None = None,
        owner_tag: str | None = None,
        userdom: str | None = None,
    ) -> InfraCursor:
        """Declare a ``infraInfra`` child under the uni level.

        A container for all tenant infra configurations.

        Args:
            annotation: User annotation. Suggested format orchestrator:value
            owner_key: The key for enabling clients to own their data for entity correlation.
            owner_tag: A tag for enabling clients to add their own data. For example, to
                indicate who created this object.
        """
        params = {k: v for k, v in locals().items() if k not in ("self",)}
        return cast(
            "InfraCursor",
            self._invoke_maker("infra", (), _prune(params)),
        )

    def fabric(
        self,
        *,
        annotation: str | None = None,
        name: str | None = None,
        display_name: str | None = None,
        owner_key: str | None = None,
        owner_tag: str | None = None,
        userdom: str | None = None,
    ) -> FabricCursor:
        """Declare a ``fabricInst`` child under the uni level.

        A container object for fabric policies.

        Args:
            annotation: User annotation. Suggested format orchestrator:value
            owner_key: The key for enabling clients to own their data for entity correlation.
            owner_tag: A tag for enabling clients to add their own data. For example, to
                indicate who created this object.
        """
        params = {k: v for k, v in locals().items() if k not in ("self",)}
        return cast(
            "FabricCursor",
            self._invoke_maker("fabric", (), _prune(params)),
        )

    def controller(
        self,
        *,
        annotation: str | None = None,
        name: str | None = None,
        display_name: str | None = None,
        owner_key: str | None = None,
        owner_tag: str | None = None,
        userdom: str | None = None,
    ) -> ControllerCursor:
        """Declare a ``ctrlrInst`` child under the uni level.

        An instance of the controller.

        Args:
            annotation: User annotation. Suggested format orchestrator:value
            owner_key: The key for enabling clients to own their data for entity correlation.
            owner_tag: A tag for enabling clients to add their own data. For example, to
                indicate who created this object.
        """
        params = {k: v for k, v in locals().items() if k not in ("self",)}
        return cast(
            "ControllerCursor",
            self._invoke_maker("controller", (), _prune(params)),
        )

    def phys_dom(
        self,
        name: str,
        *,
        annotation: str | None = None,
        display_name: str | None = None,
        owner_key: str | None = None,
        owner_tag: str | None = None,
        userdom: str | None = None,
    ) -> PhysDomCursor:
        """Declare a ``physDomP`` child under the uni level.

        The physical domain profile stores the physical resources (ports and port-channels) and
        encap resources (VLAN/VXLAN) that should be used for endpoint groups associated with this
        domain.

        Args:
            name: The name of the physical domain.
            annotation: User annotation. Suggested format orchestrator:value
            owner_key: The key for enabling clients to own their data for entity correlation.
            owner_tag: A tag for enabling clients to add their own data. For example, to
                indicate who created this object.
        """
        params = {
            k: v
            for k, v in locals().items()
            if k
            not in (
                "self",
                "name",
            )
        }
        return cast(
            "PhysDomCursor",
            self._invoke_maker("phys_dom", (name,), _prune(params)),
        )

    def l3_dom(
        self,
        name: str,
        *,
        annotation: str | None = None,
        display_name: str | None = None,
        owner_key: str | None = None,
        owner_tag: str | None = None,
        userdom: str | None = None,
    ) -> L3DomCursor:
        """Declare a ``l3extDomP`` child under the uni level.

        The external routed domain profile is a policy for managing the physical infrastructure,
        such as ports/VLANS, that can be used by an L3 routed outside network.

        Args:
            name: The name of the policy.
            annotation: User annotation. Suggested format orchestrator:value
            owner_key: The key for enabling clients to own their data for entity correlation.
            owner_tag: A tag for enabling clients to add their own data. For example, to
                indicate who created this object.
        """
        params = {
            k: v
            for k, v in locals().items()
            if k
            not in (
                "self",
                "name",
            )
        }
        return cast(
            "L3DomCursor",
            self._invoke_maker("l3_dom", (name,), _prune(params)),
        )


class UniCursor(_UniMakers):
    """Typed cursor for ``polUni`` (uni level).

    Position: ``uni``

    Ancestor makers (implicit pop) come from the inherited mixins,
    nearest level first — the MRO mirrors the runtime resolution.
    """

    __slots__ = ()

    def set(
        self,
        *,
        annotation: str | None = None,
        display_name: str | None = None,
        userdom: str | None = None,
    ) -> UniCursor:
        """Set ``polUni`` attributes (merged; validated eagerly)."""
        params = {k: v for k, v in locals().items() if k != "self"}
        Cursor.set(self, **_prune(params))
        return self


class L3DomCursor(_UniMakers):
    """Typed cursor for ``l3extDomP`` (l3_dom level).

    Position: ``uni.l3_dom``

    Ancestor makers (implicit pop) come from the inherited mixins,
    nearest level first — the MRO mirrors the runtime resolution.
    """

    __slots__ = ()

    def set(
        self,
        *,
        annotation: str | None = None,
        display_name: str | None = None,
        owner_key: str | None = None,
        owner_tag: str | None = None,
        userdom: str | None = None,
    ) -> L3DomCursor:
        """Set ``l3extDomP`` attributes (merged; validated eagerly)."""
        params = {k: v for k, v in locals().items() if k != "self"}
        Cursor.set(self, **_prune(params))
        return self

    def bind(
        self,
        *,
        vlan_pool: str | None = None,
    ) -> L3DomCursor:
        """Declare lazy Rs references (resolved at push time)."""
        params = {k: v for k, v in locals().items() if k != "self"}
        Cursor.bind(self, **_prune(params))
        return self

    def bind_dn(
        self,
        *,
        vlan_pool: str | None = None,
    ) -> L3DomCursor:
        """Reference objects outside the design by raw DN."""
        params = {k: v for k, v in locals().items() if k != "self"}
        Cursor.bind_dn(self, **_prune(params))
        return self


class PhysDomCursor(_UniMakers):
    """Typed cursor for ``physDomP`` (phys_dom level).

    Position: ``uni.phys_dom``

    Ancestor makers (implicit pop) come from the inherited mixins,
    nearest level first — the MRO mirrors the runtime resolution.
    """

    __slots__ = ()

    def set(
        self,
        *,
        annotation: str | None = None,
        display_name: str | None = None,
        owner_key: str | None = None,
        owner_tag: str | None = None,
        userdom: str | None = None,
    ) -> PhysDomCursor:
        """Set ``physDomP`` attributes (merged; validated eagerly)."""
        params = {k: v for k, v in locals().items() if k != "self"}
        Cursor.set(self, **_prune(params))
        return self

    def bind(
        self,
        *,
        vlan_pool: str | None = None,
    ) -> PhysDomCursor:
        """Declare lazy Rs references (resolved at push time)."""
        params = {k: v for k, v in locals().items() if k != "self"}
        Cursor.bind(self, **_prune(params))
        return self

    def bind_dn(
        self,
        *,
        vlan_pool: str | None = None,
    ) -> PhysDomCursor:
        """Reference objects outside the design by raw DN."""
        params = {k: v for k, v in locals().items() if k != "self"}
        Cursor.bind_dn(self, **_prune(params))
        return self
