# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class isisRsNhAtt(ManagedObject):
    """ACI Managed Object: ``isisRsNhAtt`` — IS-IS Nexthop Attachment.

    A source relation to the list of next hopss

    RN format: ``rsnhAtt-[{target_dn}]``
    """

    _aci_class: ClassVar[str] = "isisRsNhAtt"
    _rn_format: ClassVar[str] = "rsnhAtt-[{target_dn}]"
    _naming_props: ClassVar[list[str]] = ["target_dn"]
    _fault_codes: ClassVar[dict[str, str]] = {
        "F1016": "fltIsisRsNhAttResolveFail",
    }
    _relation_info: ClassVar[dict[str, str | bool]] = {
        "cardinality": "n-to-m",
        "enforceable": True,
        "resolvable": True,
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["access-protocol", "admin", "fabric-protocol", "tenant-ext-protocol", "tenant-protocol"]
    )
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    target_dn: Annotated[str, Field(validation_alias="tDn", serialization_alias="tDn")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
