# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.StatsThrDir import StatsThrDir

from niwaki.models.base import ManagedObject


class statsThrFloatP(ManagedObject):
    """ACI Managed Object: ``statsThrFloatP`` — Base Threshold Policy Definition.

    The concrete statistical threshold policy for a float data type.

    RN format: ``thrFloat-{property}``
    """

    _aci_class: ClassVar[str] = "statsThrFloatP"
    _rn_format: ClassVar[str] = "thrFloat-{property}"
    _naming_props: ClassVar[list[str]] = ["property"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "ops"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    property: Annotated[str, Field(alias="propId")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    crit_high_reset: str = Field(default="", alias="critHighReset")
    crit_high_set: str = Field(default="", alias="critHighSet")
    crit_low_reset: str = Field(default="", alias="critLowReset")
    crit_low_set: str = Field(default="", alias="critLowSet")
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    threshold_direction: StatsThrDir = Field(default=StatsThrDir.BOTH, alias="direction")
    high_range_end: str = Field(default="", alias="highRangeEnd")
    high_range_start: str = Field(default="", alias="highRangeStart")
    raising_threshold_state: str = Field(default="", alias="highSevState")
    low_range_end: str = Field(default="", alias="lowRangeEnd")
    low_range_start: str = Field(default="", alias="lowRangeStart")
    falling_threshold_state: str = Field(default="", alias="lowSevState")
    major_high_reset: str = Field(default="", alias="majorHighReset")
    major_high_set: str = Field(default="", alias="majorHighSet")
    major_low_reset: str = Field(default="", alias="majorLowReset")
    major_low_set: str = Field(default="", alias="majorLowSet")
    minor_high_reset: str = Field(default="", alias="minorHighReset")
    minor_high_set: str = Field(default="", alias="minorHighSet")
    minor_low_reset: str = Field(default="", alias="minorLowReset")
    minor_low_set: str = Field(default="", alias="minorLowSet")
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    threshold_normal_value: str = Field(default="", alias="normal")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    warn_high_reset: str = Field(default="", alias="warnHighReset")
    warn_high_set: str = Field(default="", alias="warnHighSet")
    warn_low_reset: str = Field(default="", alias="warnLowReset")
    warn_low_set: str = Field(default="", alias="warnLowSet")
