# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.IpNexthopT import IpNexthopT

from niwaki.models.base import ManagedObject


class ipNexthopP(ManagedObject):
    """ACI Managed Object: ``ipNexthopP`` — Nexthop Profile.

    The Nexthop policy for the static route.

    RN format: ``nh-[{next_hop_address}]``
    """

    _aci_class: ClassVar[str] = "ipNexthopP"
    _rn_format: ClassVar[str] = "nh-[{next_hop_address}]"
    _naming_props: ClassVar[list[str]] = ["next_hop_address"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "ipRsNHTrackMember",
            "ipRsNexthopRouteTrack",
            "tagAnnotation",
            "tagExtMngdInst",
            "tagInst",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        [
            "access-connectivity",
            "admin",
            "fabric-connectivity",
            "tenant-connectivity",
            "tenant-ext-connectivity",
        ]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    next_hop_address: Annotated[
        str,
        Field(
            pattern="^[0-9a-fA-F.:/ ]+$",
            alias="nhAddr",
            description="The nexthop IP address for the static route to the outside network.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", description="null")] = (
        ""
    )
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    preference: str = Field(
        default="",
        alias="pref",
        description="Route preference, the administrative distance assigned to this route",
    )
    nexthop_type: IpNexthopT = Field(
        default=IpNexthopT.PREFIX, alias="type", description="Nexthop type"
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
