# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.AaaUserType import AaaUserType

from niwaki.models.base import ManagedObject


class aaaFailedLoginUser(ManagedObject):
    """ACI Managed Object: ``aaaFailedLoginUser`` — User that fail login.

    MO to represent users that fail login

    RN format: ``type-{type_of_user_local_or_remote}-user-{username}``
    """

    _aci_class: ClassVar[str] = "aaaFailedLoginUser"
    _rn_format: ClassVar[str] = "type-{type_of_user_local_or_remote}-user-{username}"
    _naming_props: ClassVar[list[str]] = ["type_of_user_local_or_remote", "username"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaFailedLogin",
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["aaa", "admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    username: Annotated[str, Field(min_length=1, max_length=512, description="username")]
    type_of_user_local_or_remote: AaaUserType = Field(
        default=AaaUserType.LOCAL,
        validation_alias="utype",
        serialization_alias="utype",
        description="user type",
    )

    # ── Create-only (ignored by APIC on modification) ─────────────────────────
    name: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The name of the AAA definition object.",
        ),
    ] = ""

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerKey",
            serialization_alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerTag",
            serialization_alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
