# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class aaaOauthProvider(ManagedObject):
    """ACI Managed Object: ``aaaOauthProvider`` — OAuth 2 Provider.

    RN format: ``oauthprovider-{name}``
    """

    _aci_class: ClassVar[str] = "aaaOauthProvider"
    _rn_format: ClassVar[str] = "oauthprovider-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _secure_props: ClassVar[frozenset[str]] = frozenset(
        ["client_secret", "periodic_server_monitoring_password"]
    )
    _fault_codes: ClassVar[dict[str, str]] = {
        "F4236": "fltAaaOauthProviderOauthProvider_Inoperable",
        "F4237": "fltAaaOauthProviderOauthProviderInoperable",
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "aaaRsSecProvToEpg",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["aaa", "admin"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The name of the object.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    authorization_endpoint_url_of_the_idp: Annotated[
        str,
        Field(
            min_length=1,
            max_length=1000,
            validation_alias="authzEndpoint",
            serialization_alias="authzEndpoint",
        ),
    ] = ""
    issuer_url: Annotated[
        str, Field(max_length=512, validation_alias="baseUrl", serialization_alias="baseUrl")
    ] = ""
    client_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=500,
            validation_alias="clientId",
            serialization_alias="clientId",
            description="The client ID (option code 61).",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    gui_redirect_banner_message: str = Field(
        default="", validation_alias="guiBannerMessage", serialization_alias="guiBannerMessage"
    )
    jwks_endpoint_url_of_the_idp: Annotated[
        str,
        Field(max_length=512, validation_alias="jwksEndpoint", serialization_alias="jwksEndpoint"),
    ] = ""
    client_secret: Annotated[
        str,
        Field(
            validation_alias="key",
            serialization_alias="key",
            repr=False,
            description="The key or password used to uniquely identify this configuration object.",
        ),
    ] = ""
    periodic_server_monitoring_password: Annotated[
        str,
        Field(
            validation_alias="monitoringPassword",
            serialization_alias="monitoringPassword",
            repr=False,
        ),
    ] = ""
    periodic_server_monitoring_username: str = Field(
        default="", validation_alias="monitoringUser", serialization_alias="monitoringUser"
    )
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    enable_use_of_oidc_protocol: bool = Field(
        default=False, validation_alias="oidcEnabled", serialization_alias="oidcEnabled"
    )
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerKey",
            serialization_alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerTag",
            serialization_alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    scope: Annotated[
        str,
        Field(min_length=1, max_length=500, description="The domain applicable to the capability."),
    ] = ""
    timeout_in_seconds: Annotated[
        int,
        Field(
            ge=5,
            le=30,
            validation_alias="timeout",
            serialization_alias="timeout",
            description="The following two properties are also defined in Ep MO. Here they reperesent per server configuration which would take precedence over global configuration defined in Ep MO",
        ),
    ] = 5
    token_endpoint_url_of_the_idp: Annotated[
        str,
        Field(
            min_length=1,
            max_length=1000,
            validation_alias="tokenEndpoint",
            serialization_alias="tokenEndpoint",
        ),
    ] = ""
    certificate_authority: Annotated[
        str,
        Field(
            max_length=16,
            pattern="^[a-zA-Z0-9_.:-]+$",
            validation_alias="tp",
            serialization_alias="tp",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    username_claim_eg_username_email_sub_etc: Annotated[
        str,
        Field(
            min_length=1,
            max_length=500,
            validation_alias="usernameAttribute",
            serialization_alias="usernameAttribute",
        ),
    ] = ""
    verify_token_signature: bool = Field(
        default=False, validation_alias="verifyEnabled", serialization_alias="verifyEnabled"
    )
