# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class aaaRbacAnnotation(ManagedObject):
    """ACI Managed Object: ``aaaRbacAnnotation`` — Annotation to capture rbac info.

    RbacAnnotation is used for capturing rbac properties of any apic object Objects can append rbacannotations as Object->RbacAnnotation which is then checked for domain eligibility

    RN format: ``rbacDom-{domain}``
    """

    _aci_class: ClassVar[str] = "aaaRbacAnnotation"
    _rn_format: ClassVar[str] = "rbacDom-{domain}"
    _naming_props: ClassVar[list[str]] = ["domain"]
    _contains: ClassVar[frozenset[str]] = frozenset({})

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["aaa", "admin"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    domain: Annotated[str, Field(description="The domain of the counts object.")]

    # ── Configurable ───────────────────────────────────────────────────────────
    childregx: Annotated[
        str,
        Field(
            max_length=256,
            pattern="^.*$",
            validation_alias="childRegex",
            serialization_alias="childRegex",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
