# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.AaaSelector import AaaSelector

from niwaki.models.base import ManagedObject


class aaaRbacPortRule(ManagedObject):
    """ACI Managed Object: ``aaaRbacPortRule`` — RBAC rule for port.

    RN format: ``rbacportrule-{name}``
    """

    _aci_class: ClassVar[str] = "aaaRbacPortRule"
    _rn_format: ClassVar[str] = "rbacportrule-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["aaa", "admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    domain: str = ""
    from_module_id: str = Field(default="", alias="fromCard")
    from_port_id: str = Field(default="", alias="fromPort")
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="ownerKey"
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(max_length=64, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="ownerTag"),
    ] = ""
    to_module_id: str = Field(default="", alias="toCard")
    to_port_id: str = Field(default="", alias="toPort")
    selector_type: AaaSelector = Field(default=AaaSelector.ALL, alias="type")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
