# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class aaaRsSecProvToEpg(ManagedObject):
    """ACI Managed Object: ``aaaRsSecProvToEpg`` — Attachable Target Group.

    A source relation to the endpoint group through which the provider server is reachable.

    RN format: ``rsSecProvToEpg``
    """

    _aci_class: ClassVar[str] = "aaaRsSecProvToEpg"
    _rn_format: ClassVar[str] = "rsSecProvToEpg"
    _naming_props: ClassVar[list[str]] = []
    _relation_info: ClassVar[dict[str, str | bool]] = {
        "cardinality": "n-to-1",
        "enforceable": False,
        "resolvable": False,
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["aaa", "admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    target_dn: str = Field(
        default="",
        validation_alias="tDn",
        serialization_alias="tDn",
        description="The distinguished name for the In-band or Out-of-band endpoint group. In-band and Out-of-band management endpoint groups consist of switches (leaves/spines) and APICs that are part of the associated out-of-band or in-band management zone.",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
