# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class infraRsL2NodeAuthPol(ManagedObject):
    """ACI Managed Object: ``infraRsL2NodeAuthPol`` — Node Authentication (802.1x) policy.

    RN format: ``rsl2NodeAuthPol``
    """

    _aci_class: ClassVar[str] = "infraRsL2NodeAuthPol"
    _rn_format: ClassVar[str] = "rsl2NodeAuthPol"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["access-connectivity", "access-equipment", "admin"]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    name: Annotated[
        str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", alias="tnL2NodeAuthPolName")
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
