# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Literal, Annotated
from pydantic import AfterValidator, Field

from niwaki.models._wire import named_number
from niwaki.models._generated.enums.EqptBrkoutMap import EqptBrkoutMap
from niwaki.models._generated.enums.FabricPCAction import FabricPCAction
from niwaki.models._generated.enums.FabricportRole import FabricportRole

from niwaki.models.base import ManagedObject


class infraPortConfig(ManagedObject):
    """ACI Managed Object: ``infraPortConfig`` — Port Configuration.

    RN format: ``portconfnode-{node}-card-{card}-port-{port}-sub-{sub_port}``
    """

    _aci_class: ClassVar[str] = "infraPortConfig"
    _rn_format: ClassVar[str] = "portconfnode-{node}-card-{card}-port-{port}-sub-{sub_port}"
    _naming_props: ClassVar[list[str]] = ["node", "card", "port", "sub_port"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["access-connectivity", "admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    card: Annotated[int, Field(ge=1, le=255)] = 1
    node: Annotated[int, Field(ge=101, le=16000, description="explicit properties")] = 0
    port: Annotated[
        int, Field(ge=1, le=127, description="The service port number for the LDAP service.")
    ] = 1
    sub_port: Annotated[
        int, Field(ge=0, le=64, validation_alias="subPort", serialization_alias="subPort")
    ] = 0

    # ── Configurable ───────────────────────────────────────────────────────────
    configuration_action: FabricPCAction = Field(
        default=FabricPCAction.CONFIGURE,
        validation_alias="action",
        serialization_alias="action",
        description="The action required when the condition is met.",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    associated_group_dn: str = Field(
        default="", validation_alias="assocGrp", serialization_alias="assocGrp"
    )
    breakout_map: EqptBrkoutMap = Field(
        default=EqptBrkoutMap.NONE, validation_alias="brkoutMap", serialization_alias="brkoutMap"
    )
    connected_fex_id: Annotated[
        Annotated[int, Field(ge=0, le=199)] | Literal["unspecified"],
        AfterValidator(named_number({"0": "unspecified"})),
        Field(validation_alias="connectedFex", serialization_alias="connectedFex"),
    ] = "unspecified"
    description: Annotated[
        str, Field(max_length=512, description="The description of this configuration item.")
    ] = ""
    port_channel_member: Annotated[
        str, Field(max_length=512, validation_alias="pcMember", serialization_alias="pcMember")
    ] = ""
    port_role: FabricportRole = Field(
        default=FabricportRole.LEAF,
        validation_alias="role",
        serialization_alias="role",
        description="The system role type.",
    )
    port_shutdown: bool = Field(
        default=False, validation_alias="shutdown", serialization_alias="shutdown"
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
