# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.InfraAdminState import InfraAdminState
from niwaki.models._generated.enums.InfraApplianceFailoverStatus import InfraApplianceFailoverStatus

from niwaki.models.base import ManagedObject


class infraWiNode(ManagedObject):
    """ACI Managed Object: ``infraWiNode`` — Cluster Element.

    The appliances as physical devices that are wired into the cluster.

    RN format: ``node-{cluster_unique_controller_id}``
    """

    _aci_class: ClassVar[str] = "infraWiNode"
    _rn_format: ClassVar[str] = "node-{cluster_unique_controller_id}"
    _naming_props: ClassVar[list[str]] = ["cluster_unique_controller_id"]
    _fault_codes: ClassVar[dict[str, str]] = {
        "F0321": "fltInfraWiNodeHealth",
        "F2595": "fltInfraWiNodeApplianceFailoverStatus",
        "F3906": "fltInfraWiNodePeerNodeUnavailable",
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "infraRsFabricNode",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "fabric-equipment"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    cluster_unique_controller_id: Annotated[
        str, Field(alias="id", description="The ID of a wired node.")
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    administrative_state: InfraAdminState = Field(
        default=InfraAdminState.OUT_OF_SERVICE,
        alias="adminSt",
        description="A value that indicates the administrative state of the cluster. No appliance with the given ID will be admitted into the cluster while it is in an Out of Service state.",
    )
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    appliance_failover_status: InfraApplianceFailoverStatus = Field(
        default=InfraApplianceFailoverStatus.IDLE,
        alias="failoverStatus",
        description="Appliance failover status",
    )
    force_administrative_state_change: bool = Field(default=False, alias="force")
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    routable_ip_address: str = Field(
        default="",
        alias="routableIpAddr",
        description='No controller with given ID will be admitted into the cluster while it is in "out-of-service" state',
    )
    target_motherboard_serial_number: Annotated[
        str,
        Field(
            max_length=512,
            alias="targetMbSn",
            description="Cluster HA target controller's motherboard serial number",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
