# ruff: noqa
# Generated ACI package: dbgac
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

_CLASSES: dict[str, str] = {
    "AnyToEp": "dbgacAnyToEp",
    "EpToAny": "dbgacEpToAny",
    "EpToEp": "dbgacEpToEp",
    "EpToEpg": "dbgacEpToEpg",
    "EpToExt": "dbgacEpToExt",
    "EpgToEp": "dbgacEpgToEp",
    "EpgToEpg": "dbgacEpgToEpg",
    "EpgToIp": "dbgacEpgToIp",
    "ExtToEp": "dbgacExtToEp",
    "Filter": "dbgacFilter",
    "IpToEpg": "dbgacIpToEpg",
    "IpToIp": "dbgacIpToIp",
    "RsAcExtPolToContext": "dbgacRsAcExtPolToContext",
    "RsContext": "dbgacRsContext",
    "RsFromAbsEpg": "dbgacRsFromAbsEpg",
    "RsFromEp": "dbgacRsFromEp",
    "RsFromEpForEpToEpg": "dbgacRsFromEpForEpToEpg",
    "RsFromEpIp": "dbgacRsFromEpIp",
    "RsFromEpIpForEpToEpg": "dbgacRsFromEpIpForEpToEpg",
    "RsFromEpg": "dbgacRsFromEpg",
    "RsFromEsg": "dbgacRsFromEsg",
    "RsToAbsEpg": "dbgacRsToAbsEpg",
    "RsToAbsEpgForEpgToEpg": "dbgacRsToAbsEpgForEpgToEpg",
    "RsToEp": "dbgacRsToEp",
    "RsToEpForEpToEp": "dbgacRsToEpForEpToEp",
    "RsToEpForEpgToEp": "dbgacRsToEpForEpgToEp",
    "RsToEpIp": "dbgacRsToEpIp",
    "RsToEpIpForEpToEp": "dbgacRsToEpIpForEpToEp",
    "RsToEpIpForEpgToEp": "dbgacRsToEpIpForEpgToEp",
    "RsToEpg": "dbgacRsToEpg",
    "RsToEpgForEpgToEpg": "dbgacRsToEpgForEpgToEpg",
    "RsToEsgForEpgToEpg": "dbgacRsToEsgForEpgToEpg",
}


def __getattr__(name: str) -> type:
    full = _CLASSES.get(name)
    if full is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    mod = import_module(f".{full}", __name__)
    cls = getattr(mod, full)
    globals()[name] = cls
    return cls


__all__ = list(_CLASSES)
