# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class dbgacRsFromEsg(ManagedObject):
    """ACI Managed Object: ``dbgacRsFromEsg`` — Source ESG Relation for Atomic Counter Policy.

    Rel Def to Src. Application ESG

    RN format: ``rsfromEsg-[{target_dn}]``
    """

    _aci_class: ClassVar[str] = "dbgacRsFromEsg"
    _rn_format: ClassVar[str] = "rsfromEsg-[{target_dn}]"
    _naming_props: ClassVar[list[str]] = ["target_dn"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToGlobal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-connectivity"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    target_dn: Annotated[
        str, Field(alias="tDn", description="The distinguished name of the target.")
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
