# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class vmmOrchsProvPlanFW(ManagedObject):
    """ACI Managed Object: ``vmmOrchsProvPlanFW`` — Orchestrator Plan Firewall settings.

    RN format: ``fw-{name}``
    """

    _aci_class: ClassVar[str] = "vmmOrchsProvPlanFW"
    _rn_format: ClassVar[str] = "fw-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "vmm-policy"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(min_length=1, max_length=16, pattern="^[a-zA-Z0-9_.:-]+$")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    dev_cluster: str = Field(default="", alias="devCluster")
    dev_mfctr: Annotated[str, Field(max_length=512, alias="devMfctr")] = ""
    dev_mgmt_ip: Annotated[str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="devMgmtIp")] = ""
    ext_epg: str = Field(default="", alias="extEpg")
    int_epg: str = Field(default="", alias="intEpg")
    ip_range: Annotated[str, Field(max_length=512, alias="ipRange")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
