# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class vmmPlInf(ManagedObject):
    """ACI Managed Object: ``vmmPlInf`` — Plugin Specific information.

    RN format: ``plinf-[{epg_p_key}]``
    """

    _aci_class: ClassVar[str] = "vmmPlInf"
    _rn_format: ClassVar[str] = "plinf-[{epg_p_key}]"
    _naming_props: ClassVar[list[str]] = ["epg_p_key"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "vmm-policy"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    epg_p_key: Annotated[
        str,
        Field(
            alias="epgPKey",
            description="The domain name of the endpoint group to which the fault will be delegated.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    encap: Annotated[str, Field(description="The port encapsulation.")] = ""
    name: Annotated[str, Field(max_length=128, description="The name of the object.")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    remote_err_msg: Annotated[str, Field(max_length=256, alias="remoteErrMsg")] = ""
    remote_oper_issues: str = Field(
        default="",
        alias="remoteOperIssues",
        description="The remote operational issues on this object not initiated by APIC.",
    )
    status: str = Field(default="", alias="state", description="The state of the relationship.")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
