# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.MgmtConfigurationMode import MgmtConfigurationMode

from niwaki.models.base import ManagedObject


class mgmtRsInBStNode(ManagedObject):
    """ACI Managed Object: ``mgmtRsInBStNode`` — Out-of-band Static Node.

    RN format: ``rsinBStNode-[{target_dn}]``
    """

    _aci_class: ClassVar[str] = "mgmtRsInBStNode"
    _rn_format: ClassVar[str] = "rsinBStNode-[{target_dn}]"
    _naming_props: ClassVar[list[str]] = ["target_dn"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "mgmtIp",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "tenant-connectivity", "tenant-epg", "tenant-network-profile"]
    )
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    target_dn: Annotated[str, Field(alias="tDn")]

    # ── Configurable ───────────────────────────────────────────────────────────
    address: Annotated[str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="addr")] = ""
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    configuration_mode: MgmtConfigurationMode = Field(
        default=MgmtConfigurationMode.STATIC, alias="configurationMode"
    )
    descr: Annotated[
        str, Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$")
    ] = ""
    gateway: Annotated[str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="gw")] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    v6_addr: Annotated[str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="v6Addr")] = ""
    v6_gw: Annotated[str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="v6Gw")] = ""
