# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.FabricSelector import FabricSelector

from niwaki.models.base import ManagedObject


class mgmtNodeGrp(ManagedObject):
    """ACI Managed Object: ``mgmtNodeGrp`` — Node Management Address.

    The managed node group captures the set of nodes that will participate in the management network. All the nodes, a range of nodes, or a specific node can be selected to participate in a given managed node group.

    RN format: ``mgmtnodegrp-{name}``
    """

    _aci_class: ClassVar[str] = "mgmtNodeGrp"
    _rn_format: ClassVar[str] = "mgmtnodegrp-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "infraNodeBlk",
            "mgmtRsGrp",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["access-connectivity", "admin"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The node group name. This name can be up to 64 alphanumeric characters.",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies a description of the policy definition.",
        ),
    ] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    owner_key: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerKey",
            serialization_alias="ownerKey",
            description="The key for enabling clients to own their data for entity correlation.",
        ),
    ] = ""
    owner_tag: Annotated[
        str,
        Field(
            max_length=64,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="ownerTag",
            serialization_alias="ownerTag",
            description="A tag for enabling clients to add their own data. For example, to indicate who created this object.",
        ),
    ] = ""
    selector_type: FabricSelector = Field(
        default=FabricSelector.ALL, validation_alias="type", serialization_alias="type"
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
