# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.PlannerDomType import PlannerDomType

from niwaki.models.base import ManagedObject


class plannerMatchDom(ManagedObject):
    """ACI Managed Object: ``plannerMatchDom`` — Domain affinity.

    RN format: ``dom-{domain_name}-type-{domain_type}``
    """

    _aci_class: ClassVar[str] = "plannerMatchDom"
    _rn_format: ClassVar[str] = "dom-{domain_name}-type-{domain_type}"
    _naming_props: ClassVar[list[str]] = ["domain_name", "domain_type"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    domain_name: Annotated[
        str,
        Field(min_length=1, max_length=512, alias="name", description="The name of the object."),
    ]
    domain_type: PlannerDomType = Field(
        default=PlannerDomType.L2EXT,
        alias="type",
        description="The specific type of the object or component.",
    )

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
