# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.PlannerGraphNodeType import PlannerGraphNodeType

from niwaki.models.base import ManagedObject


class plannerGraphNode(ManagedObject):
    """ACI Managed Object: ``plannerGraphNode`` — L4-L7 Service.

    Graph Node

    RN format: ``node-{name}``
    """

    _aci_class: ClassVar[str] = "plannerGraphNode"
    _rn_format: ClassVar[str] = "node-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "plannerRsGraphBd",
            "plannerRsGraphCluster",
            "plannerRsGraphL3Out",
            "plannerRsToConsumerBd",
            "plannerRsToConsumerL3Out",
            "plannerRsToProviderBd",
            "plannerRsToProviderL3Out",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(description="Don't allow numbers")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    node_order: Annotated[
        int,
        Field(
            validation_alias="order",
            serialization_alias="order",
            description="Order of this node in the service graph",
        ),
    ] = 0
    node_type: PlannerGraphNodeType = Field(
        default=PlannerGraphNodeType.GOTO_ONE_ARM,
        validation_alias="type",
        serialization_alias="type",
        description="Type of graph node",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
