# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.PlannerPlacementOptions import PlannerPlacementOptions

from niwaki.models.base import ManagedObject


class plannerEpgAny(ManagedObject):
    """ACI Managed Object: ``plannerEpgAny`` — All epgs that need to be placed.

    RN format: ``epgany``
    """

    _aci_class: ClassVar[str] = "plannerEpgAny"
    _rn_format: ClassVar[str] = "epgany"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    new_span: Annotated[int, Field(validation_alias="newSpan", serialization_alias="newSpan")] = 1
    placement_options: PlannerPlacementOptions = Field(
        default=PlannerPlacementOptions.IMPORT_AS_IS,
        validation_alias="placementOptions",
        serialization_alias="placementOptions",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
