# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.PlannerSwitchModel import PlannerSwitchModel

from niwaki.models.base import ManagedObject


class plannerLeafTmpl(ManagedObject):
    """ACI Managed Object: ``plannerLeafTmpl`` — Leaf.

    Leaf Template

    RN format: ``leaf-{name}``
    """

    _aci_class: ClassVar[str] = "plannerLeafTmpl"
    _rn_format: ClassVar[str] = "leaf-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "plannerRsConnectedSpine",
            "plannerRsLeafLabels",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(description="Don't allow numbers")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    count_of_leafs: Annotated[
        int,
        Field(
            ge=1,
            le=4000000000,
            validation_alias="count",
            serialization_alias="count",
            description="Count of leafs",
        ),
    ] = 1
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    model: PlannerSwitchModel = Field(
        default=PlannerSwitchModel.N9K_C9372PX, description="Hardware model of the leaf"
    )
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
