# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class analyticsTCPOptHdrLenBin(ManagedObject):
    """ACI Managed Object: ``analyticsTCPOptHdrLenBin`` — TCP optional header length bin entry.

    TCP options header length bin

    RN format: ``tcpopthdrlenbin-{tcp_option_header_length_bin_id}``
    """

    _aci_class: ClassVar[str] = "analyticsTCPOptHdrLenBin"
    _rn_format: ClassVar[str] = "tcpopthdrlenbin-{tcp_option_header_length_bin_id}"
    _naming_props: ClassVar[list[str]] = ["tcp_option_header_length_bin_id"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    tcp_option_header_length_bin_id: Annotated[
        int,
        Field(
            ge=0, le=6, validation_alias="id", serialization_alias="id", description="Identifier"
        ),
    ] = 0

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
        ),
    ] = ""
    bin_high_value: Annotated[
        int,
        Field(
            ge=0, le=15, validation_alias="hi", serialization_alias="hi", description="High value"
        ),
    ] = 0
    bin_low_value: Annotated[
        int,
        Field(
            ge=0, le=15, validation_alias="lo", serialization_alias="lo", description="Low value"
        ),
    ] = 0
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
