# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class analyticsRsTargetToInstalledAcl(ManagedObject):
    """ACI Managed Object: ``analyticsRsTargetToInstalledAcl`` — Target to ACL MO.

    RN format: ``rstargetToInstalledAcl-[{target_dn}]``
    """

    _aci_class: ClassVar[str] = "analyticsRsTargetToInstalledAcl"
    _rn_format: ClassVar[str] = "rstargetToInstalledAcl-[{target_dn}]"
    _naming_props: ClassVar[list[str]] = ["target_dn"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    target_dn: Annotated[str, Field(alias="tDn")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
