# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.BgpAsnPropagation import BgpAsnPropagation

from niwaki.models.base import ManagedObject


class bgpLocalAsnP(ManagedObject):
    """ACI Managed Object: ``bgpLocalAsnP`` — Local Autonomous System Profile.

    RN format: ``localasn``
    """

    _aci_class: ClassVar[str] = "bgpLocalAsnP"
    _rn_format: ClassVar[str] = "localasn"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagExtMngdInst",
            "tagInst",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "fabric-protocol"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    asn_propagation: BgpAsnPropagation = Field(default=BgpAsnPropagation.NONE, alias="asnPropagate")
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    local_asn: Annotated[int, Field(ge=1, alias="localAsn")] = 0
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
