# ruff: noqa
# Generated ACI package: dbgexp
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

_CLASSES: dict[str, str] = {
    "CoreP": "dbgexpCoreP",
    "CoreStatus": "dbgexpCoreStatus",
    "PolicyStatus": "dbgexpPolicyStatus",
    "PolicyStatusInstance": "dbgexpPolicyStatusInstance",
    "RsData": "dbgexpRsData",
    "RsExportDest": "dbgexpRsExportDest",
    "RsTSOnDScheduler": "dbgexpRsTSOnDScheduler",
    "RsTSScheduler": "dbgexpRsTSScheduler",
    "RsTsODev": "dbgexpRsTsODev",
    "RsTsSrc": "dbgexpRsTsSrc",
    "RsUserCtx": "dbgexpRsUserCtx",
    "SvccoreStatusInstance": "dbgexpSvccoreStatusInstance",
    "TSDomain": "dbgexpTSDomain",
    "TechSupCollect": "dbgexpTechSupCollect",
    "TechSupData": "dbgexpTechSupData",
    "TechSupDataCont": "dbgexpTechSupDataCont",
    "TechSupODev": "dbgexpTechSupODev",
    "TechSupOnD": "dbgexpTechSupOnD",
    "TechSupP": "dbgexpTechSupP",
    "TechSupStatus": "dbgexpTechSupStatus",
    "TechSupTrigCollectLTask": "dbgexpTechSupTrigCollectLTask",
    "TechSupVmm": "dbgexpTechSupVmm",
}


def __getattr__(name: str) -> type:
    full = _CLASSES.get(name)
    if full is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    mod = import_module(f".{full}", __name__)
    cls = getattr(mod, full)
    globals()[name] = cls
    return cls


__all__ = list(_CLASSES)
