# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class dbgexpRsUserCtx(ManagedObject):
    """ACI Managed Object: ``dbgexpRsUserCtx`` — Relation to L3 Context Export Policy.

    A source relation to the tenant context information.

    RN format: ``rsUserCtx``
    """

    _aci_class: ClassVar[str] = "dbgexpRsUserCtx"
    _rn_format: ClassVar[str] = "rsUserCtx"
    _naming_props: ClassVar[list[str]] = []
    _fault_codes: ClassVar[dict[str, str]] = {
        "F0880": "fltDbgexpRsUserCtxResolveFail",
    }
    _relation_info: ClassVar[dict[str, str | bool]] = {
        "cardinality": "n-to-1",
        "enforceable": True,
        "resolvable": True,
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToGlobal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    target_dn: str = Field(default="", validation_alias="tDn", serialization_alias="tDn")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
