# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.DbgexpCollectionType import DbgexpCollectionType
from niwaki.models._generated.enums.DbgexpLocaleType import DbgexpLocaleType

from niwaki.models.base import ManagedObject


class dbgexpTechSupCollect(ManagedObject):
    """ACI Managed Object: ``dbgexpTechSupCollect`` — Per Feature Container for Techsupport Data.

    RN format: ``tsc-[{naming_identifier}]``
    """

    _aci_class: ClassVar[str] = "dbgexpTechSupCollect"
    _rn_format: ClassVar[str] = "tsc-[{naming_identifier}]"
    _naming_props: ClassVar[list[str]] = ["naming_identifier"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    naming_identifier: Annotated[
        str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", alias="ident")
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    file_or_cli_based_collection: DbgexpCollectionType = Field(
        default=DbgexpCollectionType.FILE, alias="collectionType"
    )
    device_on_which_to_collect_data: DbgexpLocaleType = Field(
        default=DbgexpLocaleType.ALL, alias="localeType"
    )
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    filename_or_cli_command: Annotated[str, Field(max_length=1024, alias="value")] = ""
