# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.MonAdminState import MonAdminState
from niwaki.models._generated.enums.SyslogSeverity import SyslogSeverity

from niwaki.models.base import ManagedObject


class nwsSyslogSrc(ManagedObject):
    """ACI Managed Object: ``nwsSyslogSrc`` — Syslog Source for Firewall.

    RN format: ``slsrc-{name}``
    """

    _aci_class: ClassVar[str] = "nwsSyslogSrc"
    _rn_format: ClassVar[str] = "slsrc-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "nwsRsNwsSyslogSrcToDestGroup",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["access-connectivity", "access-protocol", "admin", "custom-port-privilege"]
    )
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]

    # ── Configurable ───────────────────────────────────────────────────────────
    admin_state: MonAdminState = Field(default=MonAdminState.ENABLED, alias="adminState")
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    log_action: str = Field(default="", alias="inclAction")
    min_severity: SyslogSeverity = Field(default=SyslogSeverity.INFORMATION, alias="logLevel")
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    polling_interval: Annotated[int, Field(ge=60, le=86400, alias="pollingInterval")] = 60
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
