"""Vocabulary book generator — drift guard and content contract.

The pages under ``docs/reference/vocabulary/`` are committed generated
artifacts (same rule as ``_generated_cursors.py``): regeneration must match
the working tree, and the content must reflect the live vocabulary tables.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from niwaki._codegen.generate_docs import OUTPUT_DIR, _resolve_edge, render_all
from niwaki.design._cursor import _tables

_PAGES = sorted(render_all())


class TestDrift:
    @pytest.mark.parametrize("filename", _PAGES)
    def test_committed_page_matches_regeneration(self, filename: str) -> None:
        """A stale committed page means someone edited the vocabulary without
        running ``uv run python -m niwaki._codegen.generate_docs``."""
        on_disk = Path(OUTPUT_DIR / filename)
        assert on_disk.exists(), f"{filename} missing — run generate_docs"
        assert on_disk.read_text(encoding="utf-8") == render_all()[filename], (
            f"{filename} is stale — re-run generate_docs"
        )

    def test_no_orphan_pages(self) -> None:
        """Every committed page is produced by the generator."""
        committed = {p.name for p in OUTPUT_DIR.glob("*.md")}
        assert committed == set(_PAGES)


class TestContent:
    def test_every_curated_maker_is_documented(self) -> None:
        makers = _tables().makers
        book = "".join(render_all().values())
        for table in makers.values():
            for label, child in table.items():
                assert f".{label}(" in book, f"maker {label} missing from the book"
                assert f"`{child}`" in book, f"class {child} missing from the book"

    def test_every_bind_alias_is_documented_with_flavor(self) -> None:
        binds = _tables().binds
        book = "".join(render_all().values())
        for owner, table in binds.items():
            for alias, target in table.items():
                edge = _resolve_edge(owner, target)
                assert edge is not None, f"({owner}, {alias}) unresolvable"
                assert f"`{alias}=`" in book or f"bind({alias}=...)" in book

    def test_atomic_classes_carry_the_note(self) -> None:
        pages = render_all()
        assert "Atomic class" in pages["fabric.md"]

    def test_generated_banner_on_every_page(self) -> None:
        for content in render_all().values():
            assert content.startswith("<!--\nGenerated by niwaki generate_docs")

    def test_coverage_matrix_lists_every_position(self) -> None:
        """One row per curated position, and the escape-hatch section exists."""
        from niwaki._codegen.generate_design import _positions

        coverage = render_all()["coverage.md"]
        for key in _positions():
            if not key:  # the polUni root is the page, not a row
                continue
            assert f"| `{key}` |" in coverage, f"position {key} missing from the matrix"
        assert "Not curated yet" in coverage
        assert "vocabulary request" in coverage

    def test_coverage_total_matches_the_positions(self) -> None:
        from niwaki._codegen.generate_design import _positions

        coverage = render_all()["coverage.md"]
        rows = len(_positions()) - 1  # every position except the polUni root
        assert f"**{rows} curated positions**" in coverage
