# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class vnsCCred(ManagedObject):
    """ACI Managed Object: ``vnsCCred`` — Credentials.

    The concrete device access credentials in the L4-L7 device cluster. The concrete device access credentials normally include a password that is not displayed and is stored in encrypted form.

    RN format: ``cCred``
    """

    _aci_class: ClassVar[str] = "vnsCCred"
    _rn_format: ClassVar[str] = "cCred"
    _naming_props: ClassVar[list[str]] = []
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "nw-svc-policy"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    name: Annotated[
        str,
        Field(
            max_length=16,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="The name of the concrete device access credentials in the L4-L7 device cluster. The concrete device access credentials name uniquely identifies the credentials.",
        ),
    ] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    value: Annotated[
        str,
        Field(
            max_length=512,
            description="The value for the concrete device access credentials in the L4-L7 device cluster.",
        ),
    ] = ""
