# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.VnsChassisStateType import VnsChassisStateType
from niwaki.models._generated.enums.VnsTrigState import VnsTrigState

from niwaki.models.base import ManagedObject


class vnsChassisOperInfo(ManagedObject):
    """ACI Managed Object: ``vnsChassisOperInfo`` — Chassis Operational Information.

    RN format: ``chassisOperInfo-[{t_dn}]``
    """

    _aci_class: ClassVar[str] = "vnsChassisOperInfo"
    _rn_format: ClassVar[str] = "chassisOperInfo-[{t_dn}]"
    _naming_props: ClassVar[list[str]] = ["t_dn"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
            "vnsCDevInfo",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "nw-svc-policy"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    t_dn: Annotated[str, Field(alias="tDn")]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    chassis_state: VnsChassisStateType = Field(
        default=VnsChassisStateType.INIT, alias="chassisState"
    )
    trig_re_sync: VnsTrigState = Field(default=VnsTrigState.OFF, alias="trigReSync")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
