# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models.base import ManagedObject


class vnsFWReq(ManagedObject):
    """ACI Managed Object: ``vnsFWReq`` — Normalized Firewall parameters.

    RN format: ``FW_C-{ctrct}-G-{graph}-F-{node}-N-{acl}``
    """

    _aci_class: ClassVar[str] = "vnsFWReq"
    _rn_format: ClassVar[str] = "FW_C-{ctrct}-G-{graph}-F-{node}-N-{acl}"
    _naming_props: ClassVar[list[str]] = ["ctrct", "graph", "node", "acl"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "nw-svc-params"])
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    acl: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]
    ctrct: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]
    graph: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]
    node: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]

    # ── Configurable ───────────────────────────────────────────────────────────
    ace: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    consumer: str = Field(default="", alias="cons")
    destination_from_port: str = Field(default="", alias="dFromPort")
    destination_to_port: str = Field(default="", alias="dToPort")
    acl_destination_type: str = Field(default="", alias="dType")
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    host_network_ip_address: Annotated[str, Field(pattern="^[0-9a-fA-F.:/ ]+$", alias="destIp")] = (
        ""
    )
    external_interface_name: Annotated[
        str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", alias="extIntf")
    ] = ""
    internal_interface_name: Annotated[
        str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", alias="intIntf")
    ] = ""
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    nw_obj_name: Annotated[
        str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$", alias="nwObjName")
    ] = ""
    protocol: str = Field(default="", alias="prot")
    provider: str = Field(default="", alias="prov")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
