# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Literal, Annotated
from pydantic import AfterValidator, Field

from niwaki.models._wire import named_number
from niwaki.models.base import ManagedObject


class vnsLBVSvcGrpSvrReq(ManagedObject):
    """ACI Managed Object: ``vnsLBVSvcGrpSvrReq`` — Normalized LB Service Group Server Configuration..

    RN format: ``LB_SVC_GRP_SVR_C-{ctrct}-G-{graph}-F-{node}-LB_VSVR_NAME-{lb_name}-LB_SVR_NAME-{svr_name}``
    """

    _aci_class: ClassVar[str] = "vnsLBVSvcGrpSvrReq"
    _rn_format: ClassVar[str] = (
        "LB_SVC_GRP_SVR_C-{ctrct}-G-{graph}-F-{node}-LB_VSVR_NAME-{lb_name}-LB_SVR_NAME-{svr_name}"
    )
    _naming_props: ClassVar[list[str]] = ["ctrct", "graph", "node", "lb_name", "svr_name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(
        ["admin", "nw-svc-params", "tenant-epg", "tenant-network-profile"]
    )
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    ctrct: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="contract name, graphInst selector",
        ),
    ]
    graph: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="graph name, graphInst selector",
        ),
    ]
    lb_name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            validation_alias="lbName",
            serialization_alias="lbName",
            description="LB name",
        ),
    ]
    node: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="node name, graphInst selector",
        ),
    ]
    svr_name: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern="^[a-zA-Z0-9_.:-]+$",
            validation_alias="svrName",
            serialization_alias="svrName",
            description="service group server name",
        ),
    ]

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="Specifies the description of a policy component.",
        ),
    ] = ""
    service_group_server_ip: Annotated[
        str,
        Field(
            pattern="^[0-9a-fA-F.:/ ]+$",
            validation_alias="ip",
            serialization_alias="ip",
            description="VIP IP",
        ),
    ] = ""
    name: Annotated[str, Field(max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    service_group_server_port: Annotated[
        Annotated[int, Field(ge=0, le=65535)]
        | Literal["dns", "ftpData", "http", "https", "pop3", "rtsp", "smtp", "ssh", "unspecified"],
        AfterValidator(
            named_number(
                {
                    "0": "unspecified",
                    "110": "pop3",
                    "20": "ftpData",
                    "22": "ssh",
                    "25": "smtp",
                    "443": "https",
                    "53": "dns",
                    "554": "rtsp",
                    "80": "http",
                }
            )
        ),
        Field(
            validation_alias="port",
            serialization_alias="port",
            description="port number for the service group",
        ),
    ] = "unspecified"
    provider: str = Field(
        default="", validation_alias="prov", serialization_alias="prov", description="provider Dn"
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
