# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.FvSwitchingModeT import FvSwitchingModeT

from niwaki.models.base import ManagedObject


class vnsRsALDevToDomP(ManagedObject):
    """ACI Managed Object: ``vnsRsALDevToDomP`` — Relation from L4-L7 Devices to a Vmm Domain.

    A source relation to the VMM domain profile.

    RN format: ``rsALDevToDomP``
    """

    _aci_class: ClassVar[str] = "vnsRsALDevToDomP"
    _rn_format: ClassVar[str] = "rsALDevToDomP"
    _naming_props: ClassVar[list[str]] = []
    _fault_codes: ClassVar[dict[str, str]] = {
        "F1081": "fltVnsRsALDevToDomPResolveFail",
    }
    _relation_info: ClassVar[dict[str, str | bool]] = {
        "cardinality": "n-to-1",
        "enforceable": True,
        "resolvable": True,
    }
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "faultInst",
            "tagAnnotation",
            "tagExtMngdInst",
            "tagInst",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "RelationshipToLocal"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "nw-svc-policy"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = True
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    switching_mode: FvSwitchingModeT = Field(
        default=FvSwitchingModeT.NATIVE,
        validation_alias="switchingMode",
        serialization_alias="switchingMode",
    )
    target_dn: str = Field(
        default="",
        validation_alias="tDn",
        serialization_alias="tDn",
        description="The distinguished name for the relation from the virtual device to the VLAN namespace (VMM domain). The virtual device should point to the VLAN namespace (VMM domain) pointed to by this relation.",
    )
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
