# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class ActionType(StrEnum):
    CLEAR = "clear"
    COLLECT = "collect"
    INSTALL = "install"
    INTERFACE_IN_SERVICE = "interface-in-service"
    LOCATE = "locate"
    POWEROFF = "poweroff"
    RELOAD = "reload"
    RESET = "reset"
    TEST = "test"

    @classmethod
    def _missing_(cls, value: object) -> ActionType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "clear",
            "2": "reset",
            "3": "reload",
            "4": "locate",
            "5": "install",
            "6": "test",
            "7": "collect",
            "8": "interface-in-service",
            "9": "poweroff",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
