# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class AnalyticsIPFiltAct(StrEnum):
    DENY = "deny"
    """Filtering action state is Deny"""
    PERMIT = "permit"
    """Filtering action state is Permit"""

    @classmethod
    def _missing_(cls, value: object) -> AnalyticsIPFiltAct | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "deny",
            "1": "permit",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
