# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class ArpOpcode(StrEnum):
    REPLY = "reply"
    REQ = "req"
    UNSPECIFIED = "unspecified"

    @classmethod
    def _missing_(cls, value: object) -> ArpOpcode | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "unspecified",
            "1": "req",
            "2": "reply",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
