# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class BgpConnectivityType(StrEnum):
    TENANT = "tenant"
    """Connectivity to the tenant network"""
    MULTIPOD = "multipod"
    """Connectivity to the MPOD fabric"""
    MULTISITE = "multisite"
    """Connectivity to the MSITE fabric"""

    @classmethod
    def _missing_(cls, value: object) -> BgpConnectivityType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "tenant",
            "2": "multipod",
            "4": "multisite",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
