# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class BgpDomAfCtrl(StrEnum):
    HOST_RT_LEAK = "host-rt-leak"

    @classmethod
    def _missing_(cls, value: object) -> BgpDomAfCtrl | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "host-rt-leak",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
