# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class BgpTrustCtrlT(StrEnum):
    TRUSTED = "trusted"
    UNTRUSTED = "untrusted"

    @classmethod
    def _missing_(cls, value: object) -> BgpTrustCtrlT | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "untrusted",
            "2": "trusted",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
