# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class DatetimeTimeZoneUTC(StrEnum):
    N120_AMERICA_BAHIA = "n120_America-Bahia"
    N120_AMERICA_GODTHAB = "n120_America-Godthab"
    N120_AMERICA_MIQUELON = "n120_America-Miquelon"
    N120_AMERICA_MONTEVIDEO = "n120_America-Montevideo"
    N120_AMERICA_NORONHA = "n120_America-Noronha"
    N120_AMERICA_SAO_PAULO = "n120_America-Sao_Paulo"
    N120_ATLANTIC_SOUTH_GEORGIA = "n120_Atlantic-South_Georgia"
    N150_AMERICA_ST_JOHNS = "n150_America-St_Johns"
    N180_AMERICA_ARAGUAINA = "n180_America-Araguaina"
    N180_AMERICA_ARGENTINA_BUENOS_AIRES = "n180_America-Argentina-Buenos_Aires"
    N180_AMERICA_ARGENTINA_CATAMARCA = "n180_America-Argentina-Catamarca"
    N180_AMERICA_ARGENTINA_CORDOBA = "n180_America-Argentina-Cordoba"
    N180_AMERICA_ARGENTINA_JUJUY = "n180_America-Argentina-Jujuy"
    N180_AMERICA_ARGENTINA_LA_RIOJA = "n180_America-Argentina-La_Rioja"
    N180_AMERICA_ARGENTINA_MENDOZA = "n180_America-Argentina-Mendoza"
    N180_AMERICA_ARGENTINA_RIO_GALLEGOS = "n180_America-Argentina-Rio_Gallegos"
    N180_AMERICA_ARGENTINA_SALTA = "n180_America-Argentina-Salta"
    N180_AMERICA_ARGENTINA_SAN_JUAN = "n180_America-Argentina-San_Juan"
    N180_AMERICA_ARGENTINA_SAN_LUIS = "n180_America-Argentina-San_Luis"
    N180_AMERICA_ARGENTINA_TUCUMAN = "n180_America-Argentina-Tucuman"
    N180_AMERICA_ARGENTINA_USHUAIA = "n180_America-Argentina-Ushuaia"
    N180_AMERICA_ASUNCION = "n180_America-Asuncion"
    N180_AMERICA_BELEM = "n180_America-Belem"
    N180_AMERICA_CAMPO_GRANDE = "n180_America-Campo_Grande"
    N180_AMERICA_CAYENNE = "n180_America-Cayenne"
    N180_AMERICA_CUIABA = "n180_America-Cuiaba"
    N180_AMERICA_FORTALEZA = "n180_America-Fortaleza"
    N180_AMERICA_GLACE_BAY = "n180_America-Glace_Bay"
    N180_AMERICA_GOOSE_BAY = "n180_America-Goose_Bay"
    N180_AMERICA_HALIFAX = "n180_America-Halifax"
    N180_AMERICA_MACEIO = "n180_America-Maceio"
    N180_AMERICA_MONCTON = "n180_America-Moncton"
    N180_AMERICA_PARAMARIBO = "n180_America-Paramaribo"
    N180_AMERICA_RECIFE = "n180_America-Recife"
    N180_AMERICA_SANTAREM = "n180_America-Santarem"
    N180_AMERICA_SANTIAGO = "n180_America-Santiago"
    N180_AMERICA_THULE = "n180_America-Thule"
    N180_ANTARCTICA_PALMER = "n180_Antarctica-Palmer"
    N180_ANTARCTICA_ROTHERA = "n180_Antarctica-Rothera"
    N180_ATLANTIC_BERMUDA = "n180_Atlantic-Bermuda"
    N180_ATLANTIC_STANLEY = "n180_Atlantic-Stanley"
    N240_AMERICA_ANGUILLA = "n240_America-Anguilla"
    N240_AMERICA_ANTIGUA = "n240_America-Antigua"
    N240_AMERICA_ARUBA = "n240_America-Aruba"
    N240_AMERICA_BARBADOS = "n240_America-Barbados"
    N240_AMERICA_BLANC_SABLON = "n240_America-Blanc_Sablon"
    N240_AMERICA_BOA_VISTA = "n240_America-Boa_Vista"
    N240_AMERICA_CURACAO = "n240_America-Curacao"
    N240_AMERICA_DETROIT = "n240_America-Detroit"
    N240_AMERICA_DOMINICA = "n240_America-Dominica"
    N240_AMERICA_EIRUNEPE = "n240_America-Eirunepe"
    N240_AMERICA_GRAND_TURK = "n240_America-Grand_Turk"
    N240_AMERICA_GRENADA = "n240_America-Grenada"
    N240_AMERICA_GUADELOUPE = "n240_America-Guadeloupe"
    N240_AMERICA_GUYANA = "n240_America-Guyana"
    N240_AMERICA_HAVANA = "n240_America-Havana"
    N240_AMERICA_INDIANA_INDIANAPOLIS = "n240_America-Indiana-Indianapolis"
    N240_AMERICA_INDIANA_MARENGO = "n240_America-Indiana-Marengo"
    N240_AMERICA_INDIANA_PETERSBURG = "n240_America-Indiana-Petersburg"
    N240_AMERICA_INDIANA_VEVAY = "n240_America-Indiana-Vevay"
    N240_AMERICA_INDIANA_VINCENNES = "n240_America-Indiana-Vincennes"
    N240_AMERICA_INDIANA_WINAMAC = "n240_America-Indiana-Winamac"
    N240_AMERICA_IQALUIT = "n240_America-Iqaluit"
    N240_AMERICA_KENTUCKY_LOUISVILLE = "n240_America-Kentucky-Louisville"
    N240_AMERICA_KENTUCKY_MONTICELLO = "n240_America-Kentucky-Monticello"
    N240_AMERICA_KRALENDIJK = "n240_America-Kralendijk"
    N240_AMERICA_LA_PAZ = "n240_America-La_Paz"
    N240_AMERICA_LOWER_PRINCES = "n240_America-Lower_Princes"
    N240_AMERICA_MANAUS = "n240_America-Manaus"
    N240_AMERICA_MARIGOT = "n240_America-Marigot"
    N240_AMERICA_MARTINIQUE = "n240_America-Martinique"
    N240_AMERICA_MONTREAL = "n240_America-Montreal"
    N240_AMERICA_MONTSERRAT = "n240_America-Montserrat"
    N240_AMERICA_NASSAU = "n240_America-Nassau"
    N240_AMERICA_NEW_YORK = "n240_America-New_York"
    N240_AMERICA_NIPIGON = "n240_America-Nipigon"
    N240_AMERICA_PANGNIRTUNG = "n240_America-Pangnirtung"
    N240_AMERICA_PORT_AU_PRINCE = "n240_America-Port_au_Prince"
    N240_AMERICA_PORT_OF_SPAIN = "n240_America-Port_of_Spain"
    N240_AMERICA_PORTO_VELHO = "n240_America-Porto_Velho"
    N240_AMERICA_PUERTO_RICO = "n240_America-Puerto_Rico"
    N240_AMERICA_RIO_BRANCO = "n240_America-Rio_Branco"
    N240_AMERICA_SANTO_DOMINGO = "n240_America-Santo_Domingo"
    N240_AMERICA_ST_BARTHELEMY = "n240_America-St_Barthelemy"
    N240_AMERICA_ST_KITTS = "n240_America-St_Kitts"
    N240_AMERICA_ST_LUCIA = "n240_America-St_Lucia"
    N240_AMERICA_ST_THOMAS = "n240_America-St_Thomas"
    N240_AMERICA_ST_VINCENT = "n240_America-St_Vincent"
    N240_AMERICA_THUNDER_BAY = "n240_America-Thunder_Bay"
    N240_AMERICA_TORONTO = "n240_America-Toronto"
    N240_AMERICA_TORTOLA = "n240_America-Tortola"
    N270_AMERICA_CARACAS = "n270_America-Caracas"
    N300_AMERICA_ATIKOKAN = "n300_America-Atikokan"
    N300_AMERICA_BAHIA_BANDERAS = "n300_America-Bahia_Banderas"
    N300_AMERICA_BOGOTA = "n300_America-Bogota"
    N300_AMERICA_CANCUN = "n300_America-Cancun"
    N300_AMERICA_CAYMAN = "n300_America-Cayman"
    N300_AMERICA_CHICAGO = "n300_America-Chicago"
    N300_AMERICA_GUAYAQUIL = "n300_America-Guayaquil"
    N300_AMERICA_INDIANA_KNOX = "n300_America-Indiana-Knox"
    N300_AMERICA_INDIANA_TELL_CITY = "n300_America-Indiana-Tell_City"
    N300_AMERICA_JAMAICA = "n300_America-Jamaica"
    N300_AMERICA_LIMA = "n300_America-Lima"
    N300_AMERICA_MATAMOROS = "n300_America-Matamoros"
    N300_AMERICA_MENOMINEE = "n300_America-Menominee"
    N300_AMERICA_MERIDA = "n300_America-Merida"
    N300_AMERICA_MEXICO_CITY = "n300_America-Mexico_City"
    N300_AMERICA_MONTERREY = "n300_America-Monterrey"
    N300_AMERICA_NORTH_DAKOTA_BEULAH = "n300_America-North_Dakota-Beulah"
    N300_AMERICA_NORTH_DAKOTA_CENTER = "n300_America-North_Dakota-Center"
    N300_AMERICA_NORTH_DAKOTA_NEW_SALEM = "n300_America-North_Dakota-New_Salem"
    N300_AMERICA_PANAMA = "n300_America-Panama"
    N300_AMERICA_RAINY_RIVER = "n300_America-Rainy_River"
    N300_AMERICA_RANKIN_INLET = "n300_America-Rankin_Inlet"
    N300_AMERICA_RESOLUTE = "n300_America-Resolute"
    N300_AMERICA_WINNIPEG = "n300_America-Winnipeg"
    N300_PACIFIC_EASTER = "n300_Pacific-Easter"
    N360_AMERICA_BELIZE = "n360_America-Belize"
    N360_AMERICA_BOISE = "n360_America-Boise"
    N360_AMERICA_CAMBRIDGE_BAY = "n360_America-Cambridge_Bay"
    N360_AMERICA_CHIHUAHUA = "n360_America-Chihuahua"
    N360_AMERICA_COSTA_RICA = "n360_America-Costa_Rica"
    N360_AMERICA_DENVER = "n360_America-Denver"
    N360_AMERICA_EDMONTON = "n360_America-Edmonton"
    N360_AMERICA_EL_SALVADOR = "n360_America-El_Salvador"
    N360_AMERICA_GUATEMALA = "n360_America-Guatemala"
    N360_AMERICA_INUVIK = "n360_America-Inuvik"
    N360_AMERICA_MANAGUA = "n360_America-Managua"
    N360_AMERICA_MAZATLAN = "n360_America-Mazatlan"
    N360_AMERICA_OJINAGA = "n360_America-Ojinaga"
    N360_AMERICA_REGINA = "n360_America-Regina"
    N360_AMERICA_SHIPROCK = "n360_America-Shiprock"
    N360_AMERICA_SWIFT_CURRENT = "n360_America-Swift_Current"
    N360_AMERICA_TEGUCIGALPA = "n360_America-Tegucigalpa"
    N360_AMERICA_YELLOWKNIFE = "n360_America-Yellowknife"
    N360_PACIFIC_GALAPAGOS = "n360_Pacific-Galapagos"
    N420_AMERICA_CRESTON = "n420_America-Creston"
    N420_AMERICA_DAWSON = "n420_America-Dawson"
    N420_AMERICA_DAWSON_CREEK = "n420_America-Dawson_Creek"
    N420_AMERICA_HERMOSILLO = "n420_America-Hermosillo"
    N420_AMERICA_LOS_ANGELES = "n420_America-Los_Angeles"
    N420_AMERICA_PHOENIX = "n420_America-Phoenix"
    N420_AMERICA_SANTA_ISABEL = "n420_America-Santa_Isabel"
    N420_AMERICA_TIJUANA = "n420_America-Tijuana"
    N420_AMERICA_VANCOUVER = "n420_America-Vancouver"
    N420_AMERICA_WHITEHORSE = "n420_America-Whitehorse"
    N480_AMERICA_ANCHORAGE = "n480_America-Anchorage"
    N480_AMERICA_JUNEAU = "n480_America-Juneau"
    N480_AMERICA_METLAKATLA = "n480_America-Metlakatla"
    N480_AMERICA_NOME = "n480_America-Nome"
    N480_AMERICA_SITKA = "n480_America-Sitka"
    N480_AMERICA_YAKUTAT = "n480_America-Yakutat"
    N480_PACIFIC_PITCAIRN = "n480_Pacific-Pitcairn"
    N540_AMERICA_ADAK = "n540_America-Adak"
    N540_PACIFIC_GAMBIER = "n540_Pacific-Gambier"
    N570_PACIFIC_MARQUESAS = "n570_Pacific-Marquesas"
    N600_PACIFIC_HONOLULU = "n600_Pacific-Honolulu"
    N600_PACIFIC_JOHNSTON = "n600_Pacific-Johnston"
    N600_PACIFIC_RAROTONGA = "n600_Pacific-Rarotonga"
    N600_PACIFIC_TAHITI = "n600_Pacific-Tahiti"
    N60_ATLANTIC_CAPE_VERDE = "n60_Atlantic-Cape_Verde"
    N660_PACIFIC_MIDWAY = "n660_Pacific-Midway"
    N660_PACIFIC_NIUE = "n660_Pacific-Niue"
    N660_PACIFIC_PAGO_PAGO = "n660_Pacific-Pago_Pago"
    P0_AFRICA_ABIDJAN = "p0_Africa-Abidjan"
    P0_AFRICA_ACCRA = "p0_Africa-Accra"
    P0_AFRICA_BAMAKO = "p0_Africa-Bamako"
    P0_AFRICA_BANJUL = "p0_Africa-Banjul"
    P0_AFRICA_BISSAU = "p0_Africa-Bissau"
    P0_AFRICA_CONAKRY = "p0_Africa-Conakry"
    P0_AFRICA_DAKAR = "p0_Africa-Dakar"
    P0_AFRICA_EL_AAIUN = "p0_Africa-El_Aaiun"
    P0_AFRICA_FREETOWN = "p0_Africa-Freetown"
    P0_AFRICA_LOME = "p0_Africa-Lome"
    P0_AFRICA_MONROVIA = "p0_Africa-Monrovia"
    P0_AFRICA_NOUAKCHOTT = "p0_Africa-Nouakchott"
    P0_AFRICA_OUAGADOUGOU = "p0_Africa-Ouagadougou"
    P0_AFRICA_SAO_TOME = "p0_Africa-Sao_Tome"
    P0_AMERICA_DANMARKSHAVN = "p0_America-Danmarkshavn"
    P0_AMERICA_SCORESBYSUND = "p0_America-Scoresbysund"
    P0_ATLANTIC_AZORES = "p0_Atlantic-Azores"
    P0_ATLANTIC_REYKJAVIK = "p0_Atlantic-Reykjavik"
    P0_ATLANTIC_ST_HELENA = "p0_Atlantic-St_Helena"
    P0_UTC = "p0_UTC"
    P120_AFRICA_BLANTYRE = "p120_Africa-Blantyre"
    P120_AFRICA_BUJUMBURA = "p120_Africa-Bujumbura"
    P120_AFRICA_CAIRO = "p120_Africa-Cairo"
    P120_AFRICA_CEUTA = "p120_Africa-Ceuta"
    P120_AFRICA_GABORONE = "p120_Africa-Gaborone"
    P120_AFRICA_HARARE = "p120_Africa-Harare"
    P120_AFRICA_JOHANNESBURG = "p120_Africa-Johannesburg"
    P120_AFRICA_KIGALI = "p120_Africa-Kigali"
    P120_AFRICA_LUBUMBASHI = "p120_Africa-Lubumbashi"
    P120_AFRICA_LUSAKA = "p120_Africa-Lusaka"
    P120_AFRICA_MAPUTO = "p120_Africa-Maputo"
    P120_AFRICA_MASERU = "p120_Africa-Maseru"
    P120_AFRICA_MBABANE = "p120_Africa-Mbabane"
    P120_AFRICA_TRIPOLI = "p120_Africa-Tripoli"
    P120_AFRICA_WINDHOEK = "p120_Africa-Windhoek"
    P120_ARCTIC_LONGYEARBYEN = "p120_Arctic-Longyearbyen"
    P120_EUROPE_AMSTERDAM = "p120_Europe-Amsterdam"
    P120_EUROPE_ANDORRA = "p120_Europe-Andorra"
    P120_EUROPE_BELGRADE = "p120_Europe-Belgrade"
    P120_EUROPE_BERLIN = "p120_Europe-Berlin"
    P120_EUROPE_BRATISLAVA = "p120_Europe-Bratislava"
    P120_EUROPE_BRUSSELS = "p120_Europe-Brussels"
    P120_EUROPE_BUDAPEST = "p120_Europe-Budapest"
    P120_EUROPE_COPENHAGEN = "p120_Europe-Copenhagen"
    P120_EUROPE_GIBRALTAR = "p120_Europe-Gibraltar"
    P120_EUROPE_LJUBLJANA = "p120_Europe-Ljubljana"
    P120_EUROPE_LUXEMBOURG = "p120_Europe-Luxembourg"
    P120_EUROPE_MADRID = "p120_Europe-Madrid"
    P120_EUROPE_MALTA = "p120_Europe-Malta"
    P120_EUROPE_MONACO = "p120_Europe-Monaco"
    P120_EUROPE_OSLO = "p120_Europe-Oslo"
    P120_EUROPE_PARIS = "p120_Europe-Paris"
    P120_EUROPE_PODGORICA = "p120_Europe-Podgorica"
    P120_EUROPE_PRAGUE = "p120_Europe-Prague"
    P120_EUROPE_ROME = "p120_Europe-Rome"
    P120_EUROPE_SAN_MARINO = "p120_Europe-San_Marino"
    P120_EUROPE_SARAJEVO = "p120_Europe-Sarajevo"
    P120_EUROPE_SKOPJE = "p120_Europe-Skopje"
    P120_EUROPE_STOCKHOLM = "p120_Europe-Stockholm"
    P120_EUROPE_TIRANE = "p120_Europe-Tirane"
    P120_EUROPE_VADUZ = "p120_Europe-Vaduz"
    P120_EUROPE_VATICAN = "p120_Europe-Vatican"
    P120_EUROPE_VIENNA = "p120_Europe-Vienna"
    P120_EUROPE_WARSAW = "p120_Europe-Warsaw"
    P120_EUROPE_ZAGREB = "p120_Europe-Zagreb"
    P120_EUROPE_ZURICH = "p120_Europe-Zurich"
    P180_AFRICA_ADDIS_ABABA = "p180_Africa-Addis_Ababa"
    P180_AFRICA_ASMARA = "p180_Africa-Asmara"
    P180_AFRICA_DAR_ES_SALAAM = "p180_Africa-Dar_es_Salaam"
    P180_AFRICA_DJIBOUTI = "p180_Africa-Djibouti"
    P180_AFRICA_JUBA = "p180_Africa-Juba"
    P180_AFRICA_KAMPALA = "p180_Africa-Kampala"
    P180_AFRICA_KHARTOUM = "p180_Africa-Khartoum"
    P180_AFRICA_MOGADISHU = "p180_Africa-Mogadishu"
    P180_AFRICA_NAIROBI = "p180_Africa-Nairobi"
    P180_ANTARCTICA_SYOWA = "p180_Antarctica-Syowa"
    P180_ASIA_ADEN = "p180_Asia-Aden"
    P180_ASIA_AMMAN = "p180_Asia-Amman"
    P180_ASIA_BAGHDAD = "p180_Asia-Baghdad"
    P180_ASIA_BAHRAIN = "p180_Asia-Bahrain"
    P180_ASIA_BEIRUT = "p180_Asia-Beirut"
    P180_ASIA_DAMASCUS = "p180_Asia-Damascus"
    P180_ASIA_GAZA = "p180_Asia-Gaza"
    P180_ASIA_HEBRON = "p180_Asia-Hebron"
    P180_ASIA_JERUSALEM = "p180_Asia-Jerusalem"
    P180_ASIA_KUWAIT = "p180_Asia-Kuwait"
    P180_ASIA_NICOSIA = "p180_Asia-Nicosia"
    P180_ASIA_QATAR = "p180_Asia-Qatar"
    P180_ASIA_RIYADH = "p180_Asia-Riyadh"
    P180_EUROPE_ATHENS = "p180_Europe-Athens"
    P180_EUROPE_BUCHAREST = "p180_Europe-Bucharest"
    P180_EUROPE_CHISINAU = "p180_Europe-Chisinau"
    P180_EUROPE_HELSINKI = "p180_Europe-Helsinki"
    P180_EUROPE_ISTANBUL = "p180_Europe-Istanbul"
    P180_EUROPE_KALININGRAD = "p180_Europe-Kaliningrad"
    P180_EUROPE_KIEV = "p180_Europe-Kiev"
    P180_EUROPE_MARIEHAMN = "p180_Europe-Mariehamn"
    P180_EUROPE_MINSK = "p180_Europe-Minsk"
    P180_EUROPE_RIGA = "p180_Europe-Riga"
    P180_EUROPE_SIMFEROPOL = "p180_Europe-Simferopol"
    P180_EUROPE_SOFIA = "p180_Europe-Sofia"
    P180_EUROPE_TALLINN = "p180_Europe-Tallinn"
    P180_EUROPE_UZHGOROD = "p180_Europe-Uzhgorod"
    P180_EUROPE_VILNIUS = "p180_Europe-Vilnius"
    P180_EUROPE_ZAPOROZHYE = "p180_Europe-Zaporozhye"
    P180_INDIAN_ANTANANARIVO = "p180_Indian-Antananarivo"
    P180_INDIAN_COMORO = "p180_Indian-Comoro"
    P180_INDIAN_MAYOTTE = "p180_Indian-Mayotte"
    P240_ASIA_DUBAI = "p240_Asia-Dubai"
    P240_ASIA_MUSCAT = "p240_Asia-Muscat"
    P240_ASIA_TBILISI = "p240_Asia-Tbilisi"
    P240_ASIA_YEREVAN = "p240_Asia-Yerevan"
    P240_EUROPE_MOSCOW = "p240_Europe-Moscow"
    P240_EUROPE_SAMARA = "p240_Europe-Samara"
    P240_EUROPE_VOLGOGRAD = "p240_Europe-Volgograd"
    P240_INDIAN_MAHE = "p240_Indian-Mahe"
    P240_INDIAN_MAURITIUS = "p240_Indian-Mauritius"
    P240_INDIAN_REUNION = "p240_Indian-Reunion"
    P270_ASIA_KABUL = "p270_Asia-Kabul"
    P270_ASIA_TEHRAN = "p270_Asia-Tehran"
    P300_ANTARCTICA_MAWSON = "p300_Antarctica-Mawson"
    P300_ASIA_AQTAU = "p300_Asia-Aqtau"
    P300_ASIA_AQTOBE = "p300_Asia-Aqtobe"
    P300_ASIA_ASHGABAT = "p300_Asia-Ashgabat"
    P300_ASIA_BAKU = "p300_Asia-Baku"
    P300_ASIA_DUSHANBE = "p300_Asia-Dushanbe"
    P300_ASIA_KARACHI = "p300_Asia-Karachi"
    P300_ASIA_ORAL = "p300_Asia-Oral"
    P300_ASIA_SAMARKAND = "p300_Asia-Samarkand"
    P300_ASIA_TASHKENT = "p300_Asia-Tashkent"
    P300_INDIAN_KERGUELEN = "p300_Indian-Kerguelen"
    P300_INDIAN_MALDIVES = "p300_Indian-Maldives"
    P330_ASIA_COLOMBO = "p330_Asia-Colombo"
    P330_ASIA_KOLKATA = "p330_Asia-Kolkata"
    P345_ASIA_KATHMANDU = "p345_Asia-Kathmandu"
    P360_ANTARCTICA_VOSTOK = "p360_Antarctica-Vostok"
    P360_ASIA_ALMATY = "p360_Asia-Almaty"
    P360_ASIA_BISHKEK = "p360_Asia-Bishkek"
    P360_ASIA_DHAKA = "p360_Asia-Dhaka"
    P360_ASIA_QYZYLORDA = "p360_Asia-Qyzylorda"
    P360_ASIA_THIMPHU = "p360_Asia-Thimphu"
    P360_ASIA_YEKATERINBURG = "p360_Asia-Yekaterinburg"
    P360_INDIAN_CHAGOS = "p360_Indian-Chagos"
    P390_ASIA_RANGOON = "p390_Asia-Rangoon"
    P390_INDIAN_COCOS = "p390_Indian-Cocos"
    P420_ANTARCTICA_DAVIS = "p420_Antarctica-Davis"
    P420_ASIA_BANGKOK = "p420_Asia-Bangkok"
    P420_ASIA_HO_CHI_MINH = "p420_Asia-Ho_Chi_Minh"
    P420_ASIA_HOVD = "p420_Asia-Hovd"
    P420_ASIA_JAKARTA = "p420_Asia-Jakarta"
    P420_ASIA_NOVOKUZNETSK = "p420_Asia-Novokuznetsk"
    P420_ASIA_NOVOSIBIRSK = "p420_Asia-Novosibirsk"
    P420_ASIA_OMSK = "p420_Asia-Omsk"
    P420_ASIA_PHNOM_PENH = "p420_Asia-Phnom_Penh"
    P420_ASIA_PONTIANAK = "p420_Asia-Pontianak"
    P420_ASIA_VIENTIANE = "p420_Asia-Vientiane"
    P420_INDIAN_CHRISTMAS = "p420_Indian-Christmas"
    P480_ANTARCTICA_CASEY = "p480_Antarctica-Casey"
    P480_ASIA_BRUNEI = "p480_Asia-Brunei"
    P480_ASIA_CHOIBALSAN = "p480_Asia-Choibalsan"
    P480_ASIA_CHONGQING = "p480_Asia-Chongqing"
    P480_ASIA_HARBIN = "p480_Asia-Harbin"
    P480_ASIA_HONG_KONG = "p480_Asia-Hong_Kong"
    P480_ASIA_KASHGAR = "p480_Asia-Kashgar"
    P480_ASIA_KRASNOYARSK = "p480_Asia-Krasnoyarsk"
    P480_ASIA_KUALA_LUMPUR = "p480_Asia-Kuala_Lumpur"
    P480_ASIA_KUCHING = "p480_Asia-Kuching"
    P480_ASIA_MACAU = "p480_Asia-Macau"
    P480_ASIA_MAKASSAR = "p480_Asia-Makassar"
    P480_ASIA_MANILA = "p480_Asia-Manila"
    P480_ASIA_SHANGHAI = "p480_Asia-Shanghai"
    P480_ASIA_SINGAPORE = "p480_Asia-Singapore"
    P480_ASIA_TAIPEI = "p480_Asia-Taipei"
    P480_ASIA_ULAANBAATAR = "p480_Asia-Ulaanbaatar"
    P480_ASIA_URUMQI = "p480_Asia-Urumqi"
    P480_AUSTRALIA_PERTH = "p480_Australia-Perth"
    P525_AUSTRALIA_EUCLA = "p525_Australia-Eucla"
    P540_ASIA_DILI = "p540_Asia-Dili"
    P540_ASIA_IRKUTSK = "p540_Asia-Irkutsk"
    P540_ASIA_JAYAPURA = "p540_Asia-Jayapura"
    P540_ASIA_PYONGYANG = "p540_Asia-Pyongyang"
    P540_ASIA_SEOUL = "p540_Asia-Seoul"
    P540_ASIA_TOKYO = "p540_Asia-Tokyo"
    P540_PACIFIC_PALAU = "p540_Pacific-Palau"
    P570_AUSTRALIA_DARWIN = "p570_Australia-Darwin"
    P600_ANTARCTICA_DUMONTDURVILLE = "p600_Antarctica-DumontDUrville"
    P600_ASIA_YAKUTSK = "p600_Asia-Yakutsk"
    P600_AUSTRALIA_BRISBANE = "p600_Australia-Brisbane"
    P600_AUSTRALIA_LINDEMAN = "p600_Australia-Lindeman"
    P600_PACIFIC_CHUUK = "p600_Pacific-Chuuk"
    P600_PACIFIC_GUAM = "p600_Pacific-Guam"
    P600_PACIFIC_PORT_MORESBY = "p600_Pacific-Port_Moresby"
    P600_PACIFIC_SAIPAN = "p600_Pacific-Saipan"
    P60_AFRICA_ALGIERS = "p60_Africa-Algiers"
    P60_AFRICA_BANGUI = "p60_Africa-Bangui"
    P60_AFRICA_BRAZZAVILLE = "p60_Africa-Brazzaville"
    P60_AFRICA_CASABLANCA = "p60_Africa-Casablanca"
    P60_AFRICA_DOUALA = "p60_Africa-Douala"
    P60_AFRICA_KINSHASA = "p60_Africa-Kinshasa"
    P60_AFRICA_LAGOS = "p60_Africa-Lagos"
    P60_AFRICA_LIBREVILLE = "p60_Africa-Libreville"
    P60_AFRICA_LUANDA = "p60_Africa-Luanda"
    P60_AFRICA_MALABO = "p60_Africa-Malabo"
    P60_AFRICA_NDJAMENA = "p60_Africa-Ndjamena"
    P60_AFRICA_NIAMEY = "p60_Africa-Niamey"
    P60_AFRICA_PORTO_NOVO = "p60_Africa-Porto_Novo"
    P60_AFRICA_TUNIS = "p60_Africa-Tunis"
    P60_ATLANTIC_CANARY = "p60_Atlantic-Canary"
    P60_ATLANTIC_FAROE = "p60_Atlantic-Faroe"
    P60_ATLANTIC_MADEIRA = "p60_Atlantic-Madeira"
    P60_EUROPE_DUBLIN = "p60_Europe-Dublin"
    P60_EUROPE_GUERNSEY = "p60_Europe-Guernsey"
    P60_EUROPE_ISLE_OF_MAN = "p60_Europe-Isle_of_Man"
    P60_EUROPE_JERSEY = "p60_Europe-Jersey"
    P60_EUROPE_LISBON = "p60_Europe-Lisbon"
    P60_EUROPE_LONDON = "p60_Europe-London"
    P630_AUSTRALIA_ADELAIDE = "p630_Australia-Adelaide"
    P630_AUSTRALIA_BROKEN_HILL = "p630_Australia-Broken_Hill"
    P660_ANTARCTICA_MACQUARIE = "p660_Antarctica-Macquarie"
    P660_ASIA_SAKHALIN = "p660_Asia-Sakhalin"
    P660_ASIA_VLADIVOSTOK = "p660_Asia-Vladivostok"
    P660_AUSTRALIA_CURRIE = "p660_Australia-Currie"
    P660_AUSTRALIA_HOBART = "p660_Australia-Hobart"
    P660_AUSTRALIA_LORD_HOWE = "p660_Australia-Lord_Howe"
    P660_AUSTRALIA_MELBOURNE = "p660_Australia-Melbourne"
    P660_AUSTRALIA_SYDNEY = "p660_Australia-Sydney"
    P660_PACIFIC_EFATE = "p660_Pacific-Efate"
    P660_PACIFIC_GUADALCANAL = "p660_Pacific-Guadalcanal"
    P660_PACIFIC_KOSRAE = "p660_Pacific-Kosrae"
    P660_PACIFIC_NOUMEA = "p660_Pacific-Noumea"
    P660_PACIFIC_POHNPEI = "p660_Pacific-Pohnpei"
    P690_PACIFIC_NORFOLK = "p690_Pacific-Norfolk"
    P720_ASIA_ANADYR = "p720_Asia-Anadyr"
    P720_ASIA_KAMCHATKA = "p720_Asia-Kamchatka"
    P720_ASIA_MAGADAN = "p720_Asia-Magadan"
    P720_PACIFIC_FUNAFUTI = "p720_Pacific-Funafuti"
    P720_PACIFIC_KWAJALEIN = "p720_Pacific-Kwajalein"
    P720_PACIFIC_MAJURO = "p720_Pacific-Majuro"
    P720_PACIFIC_NAURU = "p720_Pacific-Nauru"
    P720_PACIFIC_TARAWA = "p720_Pacific-Tarawa"
    P720_PACIFIC_WAKE = "p720_Pacific-Wake"
    P720_PACIFIC_WALLIS = "p720_Pacific-Wallis"
    P780_ANTARCTICA_MCMURDO = "p780_Antarctica-McMurdo"
    P780_ANTARCTICA_SOUTH_POLE = "p780_Antarctica-South_Pole"
    P780_PACIFIC_AUCKLAND = "p780_Pacific-Auckland"
    P780_PACIFIC_ENDERBURY = "p780_Pacific-Enderbury"
    P780_PACIFIC_FAKAOFO = "p780_Pacific-Fakaofo"
    P780_PACIFIC_FIJI = "p780_Pacific-Fiji"
    P780_PACIFIC_TONGATAPU = "p780_Pacific-Tongatapu"
    P825_PACIFIC_CHATHAM = "p825_Pacific-Chatham"
    P840_PACIFIC_APIA = "p840_Pacific-Apia"
    P840_PACIFIC_KIRITIMATI = "p840_Pacific-Kiritimati"

    @classmethod
    def _missing_(cls, value: object) -> DatetimeTimeZoneUTC | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "p0_UTC",
            "1": "p120_Europe-Andorra",
            "10": "p420_Antarctica-Davis",
            "100": "n300_America-Rainy_River",
            "101": "n300_America-Rankin_Inlet",
            "102": "n360_America-Regina",
            "103": "n300_America-Resolute",
            "104": "n150_America-St_Johns",
            "105": "n360_America-Swift_Current",
            "106": "n240_America-Thunder_Bay",
            "107": "n240_America-Toronto",
            "108": "n420_America-Vancouver",
            "109": "n420_America-Whitehorse",
            "11": "p600_Antarctica-DumontDUrville",
            "110": "n300_America-Winnipeg",
            "111": "n360_America-Yellowknife",
            "112": "p390_Indian-Cocos",
            "113": "p60_Africa-Kinshasa",
            "114": "p120_Africa-Lubumbashi",
            "115": "p60_Africa-Bangui",
            "116": "p60_Africa-Brazzaville",
            "117": "p120_Europe-Zurich",
            "118": "p0_Africa-Abidjan",
            "119": "n600_Pacific-Rarotonga",
            "12": "p660_Antarctica-Macquarie",
            "120": "n180_America-Santiago",
            "121": "n300_Pacific-Easter",
            "122": "p60_Africa-Douala",
            "123": "p480_Asia-Chongqing",
            "124": "p480_Asia-Harbin",
            "125": "p480_Asia-Kashgar",
            "126": "p480_Asia-Shanghai",
            "127": "p480_Asia-Urumqi",
            "128": "n300_America-Bogota",
            "129": "n360_America-Costa_Rica",
            "13": "p300_Antarctica-Mawson",
            "130": "n240_America-Havana",
            "131": "n60_Atlantic-Cape_Verde",
            "132": "n240_America-Curacao",
            "133": "p420_Indian-Christmas",
            "134": "p180_Asia-Nicosia",
            "135": "p120_Europe-Prague",
            "136": "p120_Europe-Berlin",
            "137": "p180_Africa-Djibouti",
            "138": "p120_Europe-Copenhagen",
            "139": "n240_America-Dominica",
            "14": "p780_Antarctica-McMurdo",
            "140": "n240_America-Santo_Domingo",
            "141": "p60_Africa-Algiers",
            "142": "n300_America-Guayaquil",
            "143": "n360_Pacific-Galapagos",
            "144": "p180_Europe-Tallinn",
            "145": "p120_Africa-Cairo",
            "146": "p0_Africa-El_Aaiun",
            "147": "p180_Africa-Asmara",
            "148": "p120_Africa-Ceuta",
            "149": "p60_Atlantic-Canary",
            "15": "n180_Antarctica-Palmer",
            "150": "p120_Europe-Madrid",
            "151": "p180_Africa-Addis_Ababa",
            "152": "p180_Europe-Helsinki",
            "153": "p780_Pacific-Fiji",
            "154": "n180_Atlantic-Stanley",
            "155": "p600_Pacific-Chuuk",
            "156": "p660_Pacific-Kosrae",
            "157": "p660_Pacific-Pohnpei",
            "158": "p60_Atlantic-Faroe",
            "159": "p120_Europe-Paris",
            "16": "n180_Antarctica-Rothera",
            "160": "p60_Africa-Libreville",
            "161": "p60_Europe-London",
            "162": "n240_America-Grenada",
            "163": "p240_Asia-Tbilisi",
            "164": "n180_America-Cayenne",
            "165": "p60_Europe-Guernsey",
            "166": "p0_Africa-Accra",
            "167": "p120_Europe-Gibraltar",
            "168": "p0_America-Danmarkshavn",
            "169": "n120_America-Godthab",
            "17": "p780_Antarctica-South_Pole",
            "170": "p0_America-Scoresbysund",
            "171": "n180_America-Thule",
            "172": "p0_Africa-Banjul",
            "173": "p0_Africa-Conakry",
            "174": "n240_America-Guadeloupe",
            "175": "p60_Africa-Malabo",
            "176": "p180_Europe-Athens",
            "177": "n120_Atlantic-South_Georgia",
            "178": "n360_America-Guatemala",
            "179": "p600_Pacific-Guam",
            "18": "p180_Antarctica-Syowa",
            "180": "p0_Africa-Bissau",
            "181": "n240_America-Guyana",
            "182": "p480_Asia-Hong_Kong",
            "183": "n360_America-Tegucigalpa",
            "184": "p120_Europe-Zagreb",
            "185": "n240_America-Port_au_Prince",
            "186": "p120_Europe-Budapest",
            "187": "p420_Asia-Jakarta",
            "188": "p540_Asia-Jayapura",
            "189": "p480_Asia-Makassar",
            "19": "p360_Antarctica-Vostok",
            "190": "p420_Asia-Pontianak",
            "191": "p60_Europe-Dublin",
            "192": "p180_Asia-Jerusalem",
            "193": "p60_Europe-Isle_of_Man",
            "194": "p330_Asia-Kolkata",
            "195": "p360_Indian-Chagos",
            "196": "p180_Asia-Baghdad",
            "197": "p270_Asia-Tehran",
            "198": "p0_Atlantic-Reykjavik",
            "199": "p120_Europe-Rome",
            "2": "p240_Asia-Dubai",
            "20": "n180_America-Argentina-Buenos_Aires",
            "200": "p60_Europe-Jersey",
            "201": "n300_America-Jamaica",
            "202": "p180_Asia-Amman",
            "203": "p540_Asia-Tokyo",
            "204": "p180_Africa-Nairobi",
            "205": "p360_Asia-Bishkek",
            "206": "p420_Asia-Phnom_Penh",
            "207": "p780_Pacific-Enderbury",
            "208": "p840_Pacific-Kiritimati",
            "209": "p720_Pacific-Tarawa",
            "21": "n180_America-Argentina-Catamarca",
            "210": "p180_Indian-Comoro",
            "211": "n240_America-St_Kitts",
            "212": "p540_Asia-Pyongyang",
            "213": "p540_Asia-Seoul",
            "214": "p180_Asia-Kuwait",
            "215": "n300_America-Cayman",
            "216": "p360_Asia-Almaty",
            "217": "p300_Asia-Aqtau",
            "218": "p300_Asia-Aqtobe",
            "219": "p300_Asia-Oral",
            "22": "n180_America-Argentina-Cordoba",
            "220": "p360_Asia-Qyzylorda",
            "221": "p420_Asia-Vientiane",
            "222": "p180_Asia-Beirut",
            "223": "n240_America-St_Lucia",
            "224": "p120_Europe-Vaduz",
            "225": "p330_Asia-Colombo",
            "226": "p0_Africa-Monrovia",
            "227": "p120_Africa-Maseru",
            "228": "p180_Europe-Vilnius",
            "229": "p120_Europe-Luxembourg",
            "23": "n180_America-Argentina-Jujuy",
            "230": "p180_Europe-Riga",
            "231": "p120_Africa-Tripoli",
            "232": "p60_Africa-Casablanca",
            "233": "p120_Europe-Monaco",
            "234": "p180_Europe-Chisinau",
            "235": "p120_Europe-Podgorica",
            "236": "n240_America-Marigot",
            "237": "p180_Indian-Antananarivo",
            "238": "p720_Pacific-Kwajalein",
            "239": "p720_Pacific-Majuro",
            "24": "n180_America-Argentina-La_Rioja",
            "240": "p120_Europe-Skopje",
            "241": "p0_Africa-Bamako",
            "242": "p390_Asia-Rangoon",
            "243": "p480_Asia-Choibalsan",
            "244": "p420_Asia-Hovd",
            "245": "p480_Asia-Ulaanbaatar",
            "246": "p480_Asia-Macau",
            "247": "p600_Pacific-Saipan",
            "248": "n240_America-Martinique",
            "249": "p0_Africa-Nouakchott",
            "25": "n180_America-Argentina-Mendoza",
            "250": "n240_America-Montserrat",
            "251": "p120_Europe-Malta",
            "252": "p240_Indian-Mauritius",
            "253": "p300_Indian-Maldives",
            "254": "p120_Africa-Blantyre",
            "255": "n300_America-Bahia_Banderas",
            "256": "n300_America-Cancun",
            "257": "n360_America-Chihuahua",
            "258": "n420_America-Hermosillo",
            "259": "n300_America-Matamoros",
            "26": "n180_America-Argentina-Rio_Gallegos",
            "260": "n360_America-Mazatlan",
            "261": "n300_America-Merida",
            "262": "n300_America-Mexico_City",
            "263": "n300_America-Monterrey",
            "264": "n360_America-Ojinaga",
            "265": "n420_America-Santa_Isabel",
            "266": "n420_America-Tijuana",
            "267": "p480_Asia-Kuala_Lumpur",
            "268": "p480_Asia-Kuching",
            "269": "p120_Africa-Maputo",
            "27": "n180_America-Argentina-Salta",
            "270": "p120_Africa-Windhoek",
            "271": "p660_Pacific-Noumea",
            "272": "p60_Africa-Niamey",
            "273": "p690_Pacific-Norfolk",
            "274": "p60_Africa-Lagos",
            "275": "n360_America-Managua",
            "276": "p120_Europe-Amsterdam",
            "277": "p120_Europe-Oslo",
            "278": "p345_Asia-Kathmandu",
            "279": "p720_Pacific-Nauru",
            "28": "n180_America-Argentina-San_Juan",
            "280": "n660_Pacific-Niue",
            "281": "p780_Pacific-Auckland",
            "282": "p825_Pacific-Chatham",
            "283": "p240_Asia-Muscat",
            "284": "n300_America-Panama",
            "285": "n300_America-Lima",
            "286": "n540_Pacific-Gambier",
            "287": "n570_Pacific-Marquesas",
            "288": "n600_Pacific-Tahiti",
            "289": "p600_Pacific-Port_Moresby",
            "29": "n180_America-Argentina-San_Luis",
            "290": "p480_Asia-Manila",
            "291": "p300_Asia-Karachi",
            "292": "p120_Europe-Warsaw",
            "293": "n120_America-Miquelon",
            "294": "n480_Pacific-Pitcairn",
            "295": "n240_America-Puerto_Rico",
            "296": "p180_Asia-Gaza",
            "297": "p180_Asia-Hebron",
            "298": "p0_Atlantic-Azores",
            "299": "p60_Atlantic-Madeira",
            "3": "p270_Asia-Kabul",
            "30": "n180_America-Argentina-Tucuman",
            "300": "p60_Europe-Lisbon",
            "301": "p540_Pacific-Palau",
            "302": "n180_America-Asuncion",
            "303": "p180_Asia-Qatar",
            "304": "p240_Indian-Reunion",
            "305": "p180_Europe-Bucharest",
            "306": "p120_Europe-Belgrade",
            "307": "p720_Asia-Anadyr",
            "308": "p540_Asia-Irkutsk",
            "309": "p720_Asia-Kamchatka",
            "31": "n180_America-Argentina-Ushuaia",
            "310": "p480_Asia-Krasnoyarsk",
            "311": "p720_Asia-Magadan",
            "312": "p420_Asia-Novokuznetsk",
            "313": "p420_Asia-Novosibirsk",
            "314": "p420_Asia-Omsk",
            "315": "p660_Asia-Sakhalin",
            "316": "p660_Asia-Vladivostok",
            "317": "p600_Asia-Yakutsk",
            "318": "p360_Asia-Yekaterinburg",
            "319": "p180_Europe-Kaliningrad",
            "32": "n660_Pacific-Pago_Pago",
            "320": "p240_Europe-Moscow",
            "321": "p240_Europe-Samara",
            "322": "p240_Europe-Volgograd",
            "323": "p120_Africa-Kigali",
            "324": "p180_Asia-Riyadh",
            "325": "p660_Pacific-Guadalcanal",
            "326": "p240_Indian-Mahe",
            "327": "p180_Africa-Khartoum",
            "328": "p120_Europe-Stockholm",
            "329": "p480_Asia-Singapore",
            "33": "p120_Europe-Vienna",
            "330": "p0_Atlantic-St_Helena",
            "331": "p120_Europe-Ljubljana",
            "332": "p120_Arctic-Longyearbyen",
            "333": "p120_Europe-Bratislava",
            "334": "p0_Africa-Freetown",
            "335": "p120_Europe-San_Marino",
            "336": "p0_Africa-Dakar",
            "337": "p180_Africa-Mogadishu",
            "338": "n180_America-Paramaribo",
            "339": "p180_Africa-Juba",
            "34": "p630_Australia-Adelaide",
            "340": "p0_Africa-Sao_Tome",
            "341": "n360_America-El_Salvador",
            "342": "n240_America-Lower_Princes",
            "343": "p180_Asia-Damascus",
            "344": "p120_Africa-Mbabane",
            "345": "n240_America-Grand_Turk",
            "346": "p60_Africa-Ndjamena",
            "347": "p300_Indian-Kerguelen",
            "348": "p0_Africa-Lome",
            "349": "p420_Asia-Bangkok",
            "35": "p600_Australia-Brisbane",
            "350": "p300_Asia-Dushanbe",
            "351": "p780_Pacific-Fakaofo",
            "352": "p540_Asia-Dili",
            "353": "p300_Asia-Ashgabat",
            "354": "p60_Africa-Tunis",
            "355": "p780_Pacific-Tongatapu",
            "356": "p180_Europe-Istanbul",
            "357": "n240_America-Port_of_Spain",
            "358": "p720_Pacific-Funafuti",
            "359": "p480_Asia-Taipei",
            "36": "p630_Australia-Broken_Hill",
            "360": "p180_Africa-Dar_es_Salaam",
            "361": "p180_Europe-Kiev",
            "362": "p180_Europe-Simferopol",
            "363": "p180_Europe-Uzhgorod",
            "364": "p180_Europe-Zaporozhye",
            "365": "p180_Africa-Kampala",
            "366": "n600_Pacific-Johnston",
            "367": "n660_Pacific-Midway",
            "368": "p720_Pacific-Wake",
            "369": "n540_America-Adak",
            "37": "p660_Australia-Currie",
            "370": "n480_America-Anchorage",
            "371": "n360_America-Boise",
            "372": "n300_America-Chicago",
            "373": "n360_America-Denver",
            "374": "n240_America-Detroit",
            "375": "n240_America-Indiana-Indianapolis",
            "376": "n300_America-Indiana-Knox",
            "377": "n240_America-Indiana-Marengo",
            "378": "n240_America-Indiana-Petersburg",
            "379": "n300_America-Indiana-Tell_City",
            "38": "p570_Australia-Darwin",
            "380": "n240_America-Indiana-Vevay",
            "381": "n240_America-Indiana-Vincennes",
            "382": "n240_America-Indiana-Winamac",
            "383": "n480_America-Juneau",
            "384": "n240_America-Kentucky-Louisville",
            "385": "n240_America-Kentucky-Monticello",
            "386": "n420_America-Los_Angeles",
            "387": "n300_America-Menominee",
            "388": "n480_America-Metlakatla",
            "389": "n240_America-New_York",
            "39": "p525_Australia-Eucla",
            "390": "n480_America-Nome",
            "391": "n300_America-North_Dakota-Beulah",
            "392": "n300_America-North_Dakota-Center",
            "393": "n300_America-North_Dakota-New_Salem",
            "394": "n420_America-Phoenix",
            "395": "n360_America-Shiprock",
            "396": "n480_America-Sitka",
            "397": "n480_America-Yakutat",
            "398": "n600_Pacific-Honolulu",
            "399": "n120_America-Montevideo",
            "4": "n240_America-Antigua",
            "40": "p660_Australia-Hobart",
            "400": "p300_Asia-Samarkand",
            "401": "p300_Asia-Tashkent",
            "402": "p120_Europe-Vatican",
            "403": "n240_America-St_Vincent",
            "404": "n270_America-Caracas",
            "405": "n240_America-Tortola",
            "406": "n240_America-St_Thomas",
            "407": "p420_Asia-Ho_Chi_Minh",
            "408": "p660_Pacific-Efate",
            "409": "p720_Pacific-Wallis",
            "41": "p600_Australia-Lindeman",
            "410": "p840_Pacific-Apia",
            "411": "p180_Asia-Aden",
            "412": "p180_Indian-Mayotte",
            "413": "p120_Africa-Johannesburg",
            "414": "p120_Africa-Lusaka",
            "415": "p120_Africa-Harare",
            "42": "p660_Australia-Lord_Howe",
            "43": "p660_Australia-Melbourne",
            "44": "p480_Australia-Perth",
            "45": "p660_Australia-Sydney",
            "46": "n240_America-Aruba",
            "47": "p180_Europe-Mariehamn",
            "48": "p300_Asia-Baku",
            "49": "p120_Europe-Sarajevo",
            "5": "n240_America-Anguilla",
            "50": "n240_America-Barbados",
            "51": "p360_Asia-Dhaka",
            "52": "p120_Europe-Brussels",
            "53": "p0_Africa-Ouagadougou",
            "54": "p180_Europe-Sofia",
            "55": "p180_Asia-Bahrain",
            "56": "p120_Africa-Bujumbura",
            "57": "p60_Africa-Porto_Novo",
            "58": "n240_America-St_Barthelemy",
            "59": "n180_Atlantic-Bermuda",
            "6": "p120_Europe-Tirane",
            "60": "p480_Asia-Brunei",
            "61": "n240_America-La_Paz",
            "62": "n240_America-Kralendijk",
            "63": "n180_America-Araguaina",
            "64": "n120_America-Bahia",
            "65": "n180_America-Belem",
            "66": "n240_America-Boa_Vista",
            "67": "n180_America-Campo_Grande",
            "68": "n180_America-Cuiaba",
            "69": "n240_America-Eirunepe",
            "7": "p240_Asia-Yerevan",
            "70": "n180_America-Fortaleza",
            "71": "n180_America-Maceio",
            "72": "n240_America-Manaus",
            "73": "n120_America-Noronha",
            "74": "n240_America-Porto_Velho",
            "75": "n180_America-Recife",
            "76": "n240_America-Rio_Branco",
            "77": "n180_America-Santarem",
            "78": "n120_America-Sao_Paulo",
            "79": "n240_America-Nassau",
            "8": "p60_Africa-Luanda",
            "80": "p360_Asia-Thimphu",
            "81": "p120_Africa-Gaborone",
            "82": "p180_Europe-Minsk",
            "83": "n360_America-Belize",
            "84": "n300_America-Atikokan",
            "85": "n240_America-Blanc_Sablon",
            "86": "n360_America-Cambridge_Bay",
            "87": "n420_America-Creston",
            "88": "n420_America-Dawson",
            "89": "n420_America-Dawson_Creek",
            "9": "p480_Antarctica-Casey",
            "90": "n360_America-Edmonton",
            "91": "n180_America-Glace_Bay",
            "92": "n180_America-Goose_Bay",
            "93": "n180_America-Halifax",
            "94": "n360_America-Inuvik",
            "95": "n240_America-Iqaluit",
            "96": "n180_America-Moncton",
            "97": "n240_America-Montreal",
            "98": "n240_America-Nipigon",
            "99": "n240_America-Pangnirtung",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
