# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class DppType(StrEnum):
    _1R2C = "1R2C"
    _2R3C = "2R3C"

    @classmethod
    def _missing_(cls, value: object) -> DppType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "1R2C",
            "2": "2R3C",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
