# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class FabricNodeControlBitMask(StrEnum):
    NONE = "None"
    DOM = "Dom"

    @classmethod
    def _missing_(cls, value: object) -> FabricNodeControlBitMask | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "None",
            "1": "Dom",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
