# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class FhsAdminSt(StrEnum):
    DISABLED = "disabled"
    """disable"""
    ENABLED_BOTH = "enabled-both"
    """enable both"""
    ENABLED_IPV4 = "enabled-ipv4"
    """enable IPv4 only"""
    ENABLED_IPV6 = "enabled-ipv6"
    """enable IPv6 only"""

    @classmethod
    def _missing_(cls, value: object) -> FhsAdminSt | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "enabled-both",
            "1": "enabled-ipv4",
            "2": "enabled-ipv6",
            "3": "disabled",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
