# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class FteLatencyUnit(StrEnum):
    MICRO_SEC = "micro-sec"
    """micro sec"""
    MILLI_SEC = "milli-sec"
    """milli sec"""

    @classmethod
    def _missing_(cls, value: object) -> FteLatencyUnit | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "micro-sec",
            "1": "milli-sec",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
