# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class FvMode(StrEnum):
    NATIVE = "native"
    REGULAR = "regular"
    UNTAGGED = "untagged"

    @classmethod
    def _missing_(cls, value: object) -> FvMode | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "regular",
            "1": "native",
            "2": "untagged",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
