# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class HcipsecEncapsulationType(StrEnum):
    ESP = "esp"

    @classmethod
    def _missing_(cls, value: object) -> HcipsecEncapsulationType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "esp",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
