# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class InfraAdminState(StrEnum):
    IN_SERVICE = "in-service"
    OUT_OF_SERVICE = "out-of-service"

    @classmethod
    def _missing_(cls, value: object) -> InfraAdminState | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "out-of-service",
            "2": "in-service",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
