# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class L1DACRateZR(StrEnum):
    _1X1 = "1x1"

    @classmethod
    def _missing_(cls, value: object) -> L1DACRateZR | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "1x1",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
