# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class L1Layer(StrEnum):
    LAYER2 = "Layer2"
    LAYER3 = "Layer3"

    @classmethod
    def _missing_(cls, value: object) -> L1Layer | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "Layer2",
            "2": "Layer3",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
