# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class L2qiqL2ProtTunMaskT(StrEnum):
    NONE = "none"
    STP = "stp"
    LLDP = "lldp"
    CDP = "cdp"
    LACP = "lacp"
    VTP = "vtp"

    @classmethod
    def _missing_(cls, value: object) -> L2qiqL2ProtTunMaskT | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "none",
            "1": "stp",
            "16": "vtp",
            "2": "lldp",
            "4": "cdp",
            "8": "lacp",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
