# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class LicenseFeatureMode(StrEnum):
    ADVANCED = "advanced"
    BASIC = "basic"
    NONE = "none"
    SINGLE = "single"

    @classmethod
    def _missing_(cls, value: object) -> LicenseFeatureMode | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "none",
            "1": "single",
            "2": "basic",
            "3": "advanced",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
