# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class MdpDomainType(StrEnum):
    ACI = "ACI"

    @classmethod
    def _missing_(cls, value: object) -> MdpDomainType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "ACI",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
