# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class NwInstCtrl2(StrEnum):
    STATEFUL_HA = "stateful-ha"
    PDU_PER_VLAN = "pdu-per-vlan"
    """Enable sending of MCP PDU per vlan on a port"""

    @classmethod
    def _missing_(cls, value: object) -> NwInstCtrl2 | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "1": "stateful-ha",
            "256": "pdu-per-vlan",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
