# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class OspfAuthT(StrEnum):
    MD5 = "md5"
    """MD5"""
    NONE = "none"
    """None"""
    SIMPLE = "simple"
    """Simple"""

    @classmethod
    def _missing_(cls, value: object) -> OspfAuthT | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "none",
            "1": "simple",
            "2": "md5",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
