# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class PlannerGraphNodeType(StrEnum):
    GOTHROUGH = "gothrough"
    GOTO_ONE_ARM = "goto-one-arm"
    GOTO_TWO_ARM = "goto-two-arm"

    @classmethod
    def _missing_(cls, value: object) -> PlannerGraphNodeType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "goto-one-arm",
            "1": "goto-two-arm",
            "2": "gothrough",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
