# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class PoePoliceAct(StrEnum):
    ERR_DIS = "err-dis"
    """Error Disable"""
    LOG = "log"
    """Log"""
    NONE = "none"

    @classmethod
    def _missing_(cls, value: object) -> PoePoliceAct | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "none",
            "1": "err-dis",
            "2": "log",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
