# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class RtdmcAuthT(StrEnum):
    AH_MD5 = "ah-md5"
    """MD5 HMAC"""
    NONE = "none"

    @classmethod
    def _missing_(cls, value: object) -> RtdmcAuthT | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "none",
            "1": "ah-md5",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
