# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class SpanForwardingType(StrEnum):
    BOTH = "both"
    ROUTED = "routed"
    SWITCHED = "switched"

    @classmethod
    def _missing_(cls, value: object) -> SpanForwardingType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "both",
            "1": "switched",
            "2": "routed",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
