# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class TopoctrlMssTypes(StrEnum):
    GLOBAL = "Global"
    """Global"""
    MSITERL = "MsiteRl"
    """Msite w RLs Only"""
    RLONLY = "RlOnly"
    """RL Only"""
    DISABLE = "disable"
    """Disable"""

    @classmethod
    def _missing_(cls, value: object) -> TopoctrlMssTypes | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "disable",
            "1": "RlOnly",
            "2": "MsiteRl",
            "3": "Global",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
