# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class TroubleshootStatus(StrEnum):
    FAILED = "failed"
    PENDING = "pending"
    SUCCESS = "success"

    @classmethod
    def _missing_(cls, value: object) -> TroubleshootStatus | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "success",
            "1": "failed",
            "2": "pending",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
