# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class VnsConnDir(StrEnum):
    CONSUMER = "consumer"
    PROVIDER = "provider"
    UNKNOWN = "unknown"

    @classmethod
    def _missing_(cls, value: object) -> VnsConnDir | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "consumer",
            "1": "unknown",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
