# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class VnsFuncTemplateType(StrEnum):
    ADC_ONE_ARM = "ADC_ONE_ARM"
    ADC_TWO_ARM = "ADC_TWO_ARM"
    CLOUD_NATIVE_FW = "CLOUD_NATIVE_FW"
    CLOUD_NATIVE_LB = "CLOUD_NATIVE_LB"
    CLOUD_VENDOR_FW = "CLOUD_VENDOR_FW"
    CLOUD_VENDOR_LB = "CLOUD_VENDOR_LB"
    FW_ROUTED = "FW_ROUTED"
    FW_TRANS = "FW_TRANS"
    OTHER = "OTHER"

    @classmethod
    def _missing_(cls, value: object) -> VnsFuncTemplateType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "FW_TRANS",
            "1": "FW_ROUTED",
            "2": "ADC_ONE_ARM",
            "3": "ADC_TWO_ARM",
            "4": "OTHER",
            "5": "CLOUD_NATIVE_LB",
            "6": "CLOUD_VENDOR_LB",
            "7": "CLOUD_NATIVE_FW",
            "8": "CLOUD_VENDOR_FW",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
