# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class VnsLDevType(StrEnum):
    CLOUD = "CLOUD"
    PHYSICAL = "PHYSICAL"
    VIRTUAL = "VIRTUAL"

    @classmethod
    def _missing_(cls, value: object) -> VnsLDevType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "PHYSICAL",
            "1": "VIRTUAL",
            "2": "CLOUD",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
