# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class VnsNodeFuncType(StrEnum):
    GOTHROUGH = "GoThrough"
    GOTO = "GoTo"
    L1 = "L1"
    L2 = "L2"
    NONE = "None"

    @classmethod
    def _missing_(cls, value: object) -> VnsNodeFuncType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "None",
            "1": "GoTo",
            "2": "GoThrough",
            "3": "L2",
            "4": "L1",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
