# ruff: noqa
# Generated by niwaki generate_enums — do not edit manually.
from __future__ import annotations

from enum import StrEnum


class VnsUITemplateType(StrEnum):
    NDO_IMPLICIT_TEMPLATE = "NDO_IMPLICIT_TEMPLATE"
    ONE_NODE_ADC_ONE_ARM = "ONE_NODE_ADC_ONE_ARM"
    ONE_NODE_ADC_ONE_ARM_L3EXT = "ONE_NODE_ADC_ONE_ARM_L3EXT"
    ONE_NODE_ADC_TWO_ARM = "ONE_NODE_ADC_TWO_ARM"
    ONE_NODE_FW_ROUTED = "ONE_NODE_FW_ROUTED"
    ONE_NODE_FW_TRANS = "ONE_NODE_FW_TRANS"
    TWO_NODE_FW_ROUTED_ADC_ONE_ARM = "TWO_NODE_FW_ROUTED_ADC_ONE_ARM"
    TWO_NODE_FW_ROUTED_ADC_ONE_ARM_L3EXT = "TWO_NODE_FW_ROUTED_ADC_ONE_ARM_L3EXT"
    TWO_NODE_FW_ROUTED_ADC_TWO_ARM = "TWO_NODE_FW_ROUTED_ADC_TWO_ARM"
    TWO_NODE_FW_TRANS_ADC_ONE_ARM = "TWO_NODE_FW_TRANS_ADC_ONE_ARM"
    TWO_NODE_FW_TRANS_ADC_ONE_ARM_L3EXT = "TWO_NODE_FW_TRANS_ADC_ONE_ARM_L3EXT"
    TWO_NODE_FW_TRANS_ADC_TWO_ARM = "TWO_NODE_FW_TRANS_ADC_TWO_ARM"
    UNSPECIFIED = "UNSPECIFIED"

    @classmethod
    def _missing_(cls, value: object) -> VnsUITemplateType | None:
        """Accept numeric aliases used in ACI schema (hex or decimal)."""
        _aliases: dict[str, str] = {
            "0": "ONE_NODE_FW_TRANS",
            "1": "ONE_NODE_FW_ROUTED",
            "11": "ONE_NODE_ADC_ONE_ARM_L3EXT",
            "2": "ONE_NODE_ADC_ONE_ARM",
            "21": "TWO_NODE_FW_TRANS_ADC_ONE_ARM_L3EXT",
            "22": "TWO_NODE_FW_ROUTED_ADC_ONE_ARM_L3EXT",
            "23": "NDO_IMPLICIT_TEMPLATE",
            "3": "ONE_NODE_ADC_TWO_ARM",
            "4": "TWO_NODE_FW_TRANS_ADC_ONE_ARM",
            "5": "TWO_NODE_FW_ROUTED_ADC_ONE_ARM",
            "6": "TWO_NODE_FW_TRANS_ADC_TWO_ARM",
            "7": "TWO_NODE_FW_ROUTED_ADC_TWO_ARM",
            "8": "UNSPECIFIED",
        }
        if isinstance(value, str) and value in _aliases:
            return cls(_aliases[value])
        return None
