# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.OrchsnodeType import OrchsnodeType
from niwaki.models._generated.enums.OrchsresourcePoolVersion import OrchsresourcePoolVersion

from niwaki.models.base import ManagedObject


class orchsLDevVipCfg(ManagedObject):
    """ACI Managed Object: ``orchsLDevVipCfg`` — Orchestrated Device Config.

    This is used to store orchestration specific properties like Microsoft Azure Pack

    RN format: ``lls-{node_type}``
    """

    _aci_class: ClassVar[str] = "orchsLDevVipCfg"
    _rn_format: ClassVar[str] = "lls-{node_type}"
    _naming_props: ClassVar[list[str]] = ["node_type"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "orchsLDevVipAttr",
            "tagAnnotation",
            "tagTag",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin", "tenant-epg"])
    _is_creatable: ClassVar[bool] = True
    _is_observable: ClassVar[bool] = False
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = False
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    node_type: OrchsnodeType = Field(
        default=OrchsnodeType.ADC, validation_alias="nodeType", serialization_alias="nodeType"
    )

    # ── Configurable ───────────────────────────────────────────────────────────
    annotation: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9_.:-]+$",
            description="User annotation. Suggested format orchestrator:value",
        ),
    ] = ""
    description: Annotated[
        str,
        Field(
            max_length=128,
            pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$",
            validation_alias="descr",
            serialization_alias="descr",
            description="The description of this configuration item.",
        ),
    ] = ""
    display_name: Annotated[
        str,
        Field(
            max_length=63,
            pattern="^[a-zA-Z0-9_.-]+$",
            validation_alias="nameAlias",
            serialization_alias="nameAlias",
        ),
    ] = ""
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    version: OrchsresourcePoolVersion = Field(
        default=OrchsresourcePoolVersion.CLASSIC,
        description="The version of the compatibility catalog.",
    )
