# ruff: noqa
# Generated by niwaki codegen — do not edit manually.
from __future__ import annotations

from typing import ClassVar, Annotated
from pydantic import Field

from niwaki.models._generated.enums.ConfigImportMode import ConfigImportMode
from niwaki.models._generated.enums.TrigExecState import TrigExecState

from niwaki.models.base import ManagedObject


class configRollbackP(ManagedObject):
    """ACI Managed Object: ``configRollbackP`` — Configuration Snapshot Rollback Policy.

    RN format: ``snprlb-{name}``
    """

    _aci_class: ClassVar[str] = "configRollbackP"
    _rn_format: ClassVar[str] = "snprlb-{name}"
    _naming_props: ClassVar[list[str]] = ["name"]
    _contains: ClassVar[frozenset[str]] = frozenset(
        {
            "aaaRbacAnnotation",
            "configRsRemotePath",
            "tagAnnotation",
            "tagTag",
            "trigRsTriggerable",
        }
    )

    # ── Semantic metadata (from APIC schema) ───────────────────────────────────
    _mo_category: ClassVar[str] = "Regular"
    _write_access: ClassVar[frozenset[str]] = frozenset(["admin"])
    _is_observable: ClassVar[bool] = True
    _is_faultable: ClassVar[bool] = False
    _is_health_scorable: ClassVar[bool] = True
    _has_stats: ClassVar[bool] = False

    # ── Naming (required) ──────────────────────────────────────────────────────
    name: Annotated[str, Field(min_length=1, max_length=64, pattern="^[a-zA-Z0-9_.:-]+$")]

    # ── Configurable ───────────────────────────────────────────────────────────
    administrative_state: TrigExecState = Field(default=TrigExecState.UNTRIGGERED, alias="adminSt")
    annotation: Annotated[str, Field(max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
    description: Annotated[
        str,
        Field(max_length=128, pattern="^[a-zA-Z0-9\\\\!#$%()*,-./:;@ _{|}~?&+]+$", alias="descr"),
    ] = ""
    import_mode: ConfigImportMode = Field(default=ConfigImportMode.ATOMIC, alias="mode")
    display_name: Annotated[
        str, Field(max_length=63, pattern="^[a-zA-Z0-9_.-]+$", alias="nameAlias")
    ] = ""
    preview_mode_nothing_is_applied: bool = Field(default=False, alias="preview")
    snapshot: bool = False
    snapshot_one: str = Field(default="", alias="snapshotOneDn")
    snapshot_two: str = Field(default="", alias="snapshotTwoDn")
    userdom: Annotated[str, Field(max_length=1024, pattern="^[a-zA-Z0-9_.:-]+$")] = ""
